/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.motorph.ui;

import com.motorph.dao.CsvEmployeeDAO;
import com.motorph.model.Employee;
import com.motorph.model.Payslip;
import com.motorph.service.EmployeeService;
import com.motorph.util.GuiUtil;

/**
 *
 * @author Lenovo
 */
public class EmployeePayslipUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EmployeePayslipUI.class.getName());
    private EmployeeService empService;
    /**
     * Creates new form EmployeePayslipFrame
     */
    public EmployeePayslipUI(Payslip payslip) {
        initComponents();
        
        this.empService = new EmployeeService(new CsvEmployeeDAO());
        
        populateEmployeeDetails(payslip);
        populateSalaryCalculations(payslip);
    }
    
    private void populateEmployeeDetails(Payslip payslip) {
        employeePylENameFld.setText(payslip.getEmployeeName());
        employeePylENumberFld.setText(payslip.getEmployeeNumber());
        employeePylPrlDateFld.setText(payslip.getPeriodStart() + " - " + payslip.getPeriodEnd());
        employeePylPrlPeriodFld.setText("Nothin yet");
        
    }
    
    private void populateSalaryCalculations(Payslip payslip) {
        
        Employee emp = empService.findEmployee(payslip.getEmployeeNumber());
        
        employeePylBasicSalaryFld.setText(String.valueOf(emp.getBasicSalary()));
        employeePylOvertimeFld.setText("");
        employeePylHrsWorkedFld.setText("");
        employeePylRiceSubsidyFld.setText(String.valueOf(payslip.getAllowanceBreakdown().getRiceSubsidy()));
        employeePylPhnAllowanceFld.setText(String.valueOf(payslip.getAllowanceBreakdown().getPhoneAllowance()));
        employeePylCltAllowanceFld.setText(String.valueOf(payslip.getAllowanceBreakdown().getClothingAllowance()));
       
        employeePylTGrossFld.setText("");

        employeePylSSSFld.setText(String.valueOf(payslip.getDeductionBreakdown().getSss()));
        employeePylWithtaxFld.setText("");
        employeePylPhilHealthFld.setText(String.valueOf(payslip.getDeductionBreakdown().getPhilHealth()));
        employeePylPagIbigFld.setText(String.valueOf(payslip.getDeductionBreakdown().getPagIbig()));
      
        employeePylUndertimeFld.setText("");
      
        employeePylTDeductionFld.setText(String.valueOf(payslip.getDeductionBreakdown().getTotal()));

        employeePylNetPayFld.setText(String.valueOf(payslip.getNetPay()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        employeePylSidebarPnl = new javax.swing.JPanel();
        employeePylMainDashboardBtn = new javax.swing.JButton();
        employeePylMotorPHIconImgLbl = new javax.swing.JLabel();
        employeePylPrlDateFld = new javax.swing.JTextField();
        employeePylPrlPeriodLbl = new javax.swing.JLabel();
        employeePylENameFld = new javax.swing.JTextField();
        employeePylENameLbl = new javax.swing.JLabel();
        employeePylENumberLbl = new javax.swing.JLabel();
        employeePylSCalculatorBrdrPnl = new javax.swing.JPanel();
        employeePylSCalculatorLbl = new javax.swing.JLabel();
        employeePylTGrossBrdrPnl = new javax.swing.JPanel();
        employeePylEarningLbl = new javax.swing.JLabel();
        employeePylBasicSalaryLbl = new javax.swing.JLabel();
        employeePylOvertimeLbl = new javax.swing.JLabel();
        employeePylHrsWorkedLbl = new javax.swing.JLabel();
        employeePylBenefitLbl = new javax.swing.JLabel();
        employeePylRiceSubsidyLbl = new javax.swing.JLabel();
        employeePylPhnAllowanceLbl = new javax.swing.JLabel();
        employeePylCltAllowanceLbl = new javax.swing.JLabel();
        employeePylBasicSalaryFld = new javax.swing.JTextField();
        employeePylOvertimeFld = new javax.swing.JTextField();
        employeePylHrsWorkedFld = new javax.swing.JTextField();
        employeePylRiceSubsidyFld = new javax.swing.JTextField();
        employeePylPhnAllowanceFld = new javax.swing.JTextField();
        employeePylCltAllowanceFld = new javax.swing.JTextField();
        employeePylTGrossFld = new javax.swing.JTextField();
        employeePylTGrossLbl = new javax.swing.JLabel();
        employeePylHourlyRateLbl = new javax.swing.JLabel();
        employeePylHourlyRateFld = new javax.swing.JTextField();
        employeePylTDeductionBrdrPnl = new javax.swing.JPanel();
        employeePylDeductionLbl = new javax.swing.JLabel();
        employeePylSSSLbl = new javax.swing.JLabel();
        employeePylWithtaxLbl = new javax.swing.JLabel();
        employeePylPhilHealthLbl = new javax.swing.JLabel();
        employeePylUndertimeLbl = new javax.swing.JLabel();
        employeePylSSSFld = new javax.swing.JTextField();
        employeePylWithtaxFld = new javax.swing.JTextField();
        employeePylPhilHealthFld = new javax.swing.JTextField();
        employeePylUndertimeFld = new javax.swing.JTextField();
        employeePylTDeductionFld = new javax.swing.JTextField();
        employeePylTDeductionLbl = new javax.swing.JLabel();
        employeePylPagIbigFld = new javax.swing.JTextField();
        employeePylPagIbigLbl = new javax.swing.JLabel();
        employeePylNetPayLbl = new javax.swing.JLabel();
        employeePylNetPayFld = new javax.swing.JTextField();
        employeePylPrlDateLbl = new javax.swing.JLabel();
        employeePylENumberFld = new javax.swing.JTextField();
        employeePylPylPnl = new javax.swing.JPanel();
        employeePylPylLbl = new javax.swing.JLabel();
        employeePylPrlPeriodFld = new javax.swing.JTextField();
        employeePylFADisputeBtn = new javax.swing.JButton();
        employeePylBackBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        employeePylSidebarPnl.setBackground(new java.awt.Color(30, 58, 138));
        employeePylSidebarPnl.setPreferredSize(new java.awt.Dimension(262, 700));

        employeePylMainDashboardBtn.setBackground(new java.awt.Color(30, 42, 56));
        employeePylMainDashboardBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        employeePylMainDashboardBtn.setForeground(new java.awt.Color(255, 255, 255));
        employeePylMainDashboardBtn.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        employeePylMainDashboardBtn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        employeePylMainDashboardBtn.setLabel("Main Dashboard");
        employeePylMainDashboardBtn.addActionListener(this::employeePylMainDashboardBtnActionPerformed);

        employeePylMotorPHIconImgLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/motorph/img/MotorPHIconImg.png"))); // NOI18N

        javax.swing.GroupLayout employeePylSidebarPnlLayout = new javax.swing.GroupLayout(employeePylSidebarPnl);
        employeePylSidebarPnl.setLayout(employeePylSidebarPnlLayout);
        employeePylSidebarPnlLayout.setHorizontalGroup(
            employeePylSidebarPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeePylSidebarPnlLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(employeePylMainDashboardBtn))
            .addGroup(employeePylSidebarPnlLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(employeePylMotorPHIconImgLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        employeePylSidebarPnlLayout.setVerticalGroup(
            employeePylSidebarPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeePylSidebarPnlLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(employeePylMotorPHIconImgLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(454, 454, 454)
                .addComponent(employeePylMainDashboardBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        employeePylMainDashboardBtn.getAccessibleContext().setAccessibleName("employeePylMainDashboardBtn");
        employeePylMotorPHIconImgLbl.getAccessibleContext().setAccessibleName("employeePylMotorPHIconImgLbl");

        employeePylPrlDateFld.setForeground(new java.awt.Color(31, 41, 55));
        employeePylPrlDateFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        employeePylPrlDateFld.setCaretColor(new java.awt.Color(31, 41, 55));
        employeePylPrlDateFld.setDisabledTextColor(new java.awt.Color(31, 41, 55));
        employeePylPrlDateFld.setEnabled(false);
        employeePylPrlDateFld.addActionListener(this::employeePylPrlDateFldActionPerformed);

        employeePylPrlPeriodLbl.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        employeePylPrlPeriodLbl.setForeground(new java.awt.Color(31, 41, 55));
        employeePylPrlPeriodLbl.setText("Payroll Period");

        employeePylENameFld.setForeground(new java.awt.Color(31, 41, 55));
        employeePylENameFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        employeePylENameFld.setCaretColor(new java.awt.Color(31, 41, 55));
        employeePylENameFld.setDisabledTextColor(new java.awt.Color(31, 41, 55));
        employeePylENameFld.setEnabled(false);
        employeePylENameFld.addActionListener(this::employeePylENameFldActionPerformed);

        employeePylENameLbl.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        employeePylENameLbl.setForeground(new java.awt.Color(31, 41, 55));
        employeePylENameLbl.setText("Employee Name");

        employeePylENumberLbl.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        employeePylENumberLbl.setForeground(new java.awt.Color(31, 41, 55));
        employeePylENumberLbl.setText("Employee #");

        employeePylSCalculatorBrdrPnl.setBackground(new java.awt.Color(146, 192, 253));
        employeePylSCalculatorBrdrPnl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        employeePylSCalculatorBrdrPnl.setForeground(new java.awt.Color(146, 192, 253));
        employeePylSCalculatorBrdrPnl.setPreferredSize(new java.awt.Dimension(710, 408));

        employeePylSCalculatorLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        employeePylSCalculatorLbl.setForeground(new java.awt.Color(31, 41, 55));
        employeePylSCalculatorLbl.setText("Salary Calculator");

        employeePylTGrossBrdrPnl.setBackground(new java.awt.Color(233, 233, 233));
        employeePylTGrossBrdrPnl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        employeePylTGrossBrdrPnl.setForeground(new java.awt.Color(30, 58, 138));

        employeePylEarningLbl.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        employeePylEarningLbl.setForeground(new java.awt.Color(31, 41, 55));
        employeePylEarningLbl.setText("Earning");

        employeePylBasicSalaryLbl.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        employeePylBasicSalaryLbl.setForeground(new java.awt.Color(31, 41, 55));
        employeePylBasicSalaryLbl.setText("Basic Salary");

        employeePylOvertimeLbl.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        employeePylOvertimeLbl.setForeground(new java.awt.Color(31, 41, 55));
        employeePylOvertimeLbl.setText("Overtime");

        employeePylHrsWorkedLbl.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        employeePylHrsWorkedLbl.setForeground(new java.awt.Color(31, 41, 55));
        employeePylHrsWorkedLbl.setText("Hour/s Worked");

        employeePylBenefitLbl.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        employeePylBenefitLbl.setForeground(new java.awt.Color(31, 41, 55));
        employeePylBenefitLbl.setText("Benefit");

        employeePylRiceSubsidyLbl.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        employeePylRiceSubsidyLbl.setForeground(new java.awt.Color(31, 41, 55));
        employeePylRiceSubsidyLbl.setText("Rice Subsidy");

        employeePylPhnAllowanceLbl.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        employeePylPhnAllowanceLbl.setForeground(new java.awt.Color(31, 41, 55));
        employeePylPhnAllowanceLbl.setText("Phone Allowance");

        employeePylCltAllowanceLbl.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        employeePylCltAllowanceLbl.setForeground(new java.awt.Color(31, 41, 55));
        employeePylCltAllowanceLbl.setText("Clothing Allowance");

        employeePylBasicSalaryFld.setForeground(new java.awt.Color(31, 41, 55));
        employeePylBasicSalaryFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        employeePylBasicSalaryFld.setCaretColor(new java.awt.Color(31, 41, 55));
        employeePylBasicSalaryFld.setDisabledTextColor(new java.awt.Color(31, 41, 55));
        employeePylBasicSalaryFld.setEnabled(false);
        employeePylBasicSalaryFld.addActionListener(this::employeePylBasicSalaryFldActionPerformed);

        employeePylOvertimeFld.setForeground(new java.awt.Color(31, 41, 55));
        employeePylOvertimeFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        employeePylOvertimeFld.setCaretColor(new java.awt.Color(31, 41, 55));
        employeePylOvertimeFld.setDisabledTextColor(new java.awt.Color(31, 41, 55));
        employeePylOvertimeFld.setEnabled(false);
        employeePylOvertimeFld.addActionListener(this::employeePylOvertimeFldActionPerformed);

        employeePylHrsWorkedFld.setForeground(new java.awt.Color(31, 41, 55));
        employeePylHrsWorkedFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        employeePylHrsWorkedFld.setCaretColor(new java.awt.Color(31, 41, 55));
        employeePylHrsWorkedFld.setDisabledTextColor(new java.awt.Color(31, 41, 55));
        employeePylHrsWorkedFld.setEnabled(false);
        employeePylHrsWorkedFld.addActionListener(this::employeePylHrsWorkedFldActionPerformed);

        employeePylRiceSubsidyFld.setForeground(new java.awt.Color(31, 41, 55));
        employeePylRiceSubsidyFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        employeePylRiceSubsidyFld.setCaretColor(new java.awt.Color(31, 41, 55));
        employeePylRiceSubsidyFld.setDisabledTextColor(new java.awt.Color(31, 41, 55));
        employeePylRiceSubsidyFld.setEnabled(false);
        employeePylRiceSubsidyFld.addActionListener(this::employeePylRiceSubsidyFldActionPerformed);

        employeePylPhnAllowanceFld.setForeground(new java.awt.Color(31, 41, 55));
        employeePylPhnAllowanceFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        employeePylPhnAllowanceFld.setCaretColor(new java.awt.Color(31, 41, 55));
        employeePylPhnAllowanceFld.setDisabledTextColor(new java.awt.Color(31, 41, 55));
        employeePylPhnAllowanceFld.setEnabled(false);
        employeePylPhnAllowanceFld.addActionListener(this::employeePylPhnAllowanceFldActionPerformed);

        employeePylCltAllowanceFld.setForeground(new java.awt.Color(31, 41, 55));
        employeePylCltAllowanceFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        employeePylCltAllowanceFld.setCaretColor(new java.awt.Color(31, 41, 55));
        employeePylCltAllowanceFld.setDisabledTextColor(new java.awt.Color(31, 41, 55));
        employeePylCltAllowanceFld.setEnabled(false);
        employeePylCltAllowanceFld.addActionListener(this::employeePylCltAllowanceFldActionPerformed);

        employeePylTGrossFld.setForeground(new java.awt.Color(31, 41, 55));
        employeePylTGrossFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        employeePylTGrossFld.setCaretColor(new java.awt.Color(31, 41, 55));
        employeePylTGrossFld.setDisabledTextColor(new java.awt.Color(31, 41, 55));
        employeePylTGrossFld.setEnabled(false);
        employeePylTGrossFld.addActionListener(this::employeePylTGrossFldActionPerformed);

        employeePylTGrossLbl.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        employeePylTGrossLbl.setForeground(new java.awt.Color(31, 41, 55));
        employeePylTGrossLbl.setText("Total Gross");

        employeePylHourlyRateLbl.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        employeePylHourlyRateLbl.setForeground(new java.awt.Color(31, 41, 55));
        employeePylHourlyRateLbl.setText("Hourly Rate");

        employeePylHourlyRateFld.setForeground(new java.awt.Color(31, 41, 55));
        employeePylHourlyRateFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        employeePylHourlyRateFld.setCaretColor(new java.awt.Color(31, 41, 55));
        employeePylHourlyRateFld.setDisabledTextColor(new java.awt.Color(31, 41, 55));
        employeePylHourlyRateFld.setEnabled(false);
        employeePylHourlyRateFld.addActionListener(this::employeePylHourlyRateFldActionPerformed);

        javax.swing.GroupLayout employeePylTGrossBrdrPnlLayout = new javax.swing.GroupLayout(employeePylTGrossBrdrPnl);
        employeePylTGrossBrdrPnl.setLayout(employeePylTGrossBrdrPnlLayout);
        employeePylTGrossBrdrPnlLayout.setHorizontalGroup(
            employeePylTGrossBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, employeePylTGrossBrdrPnlLayout.createSequentialGroup()
                .addGroup(employeePylTGrossBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, employeePylTGrossBrdrPnlLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addGroup(employeePylTGrossBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(employeePylEarningLbl)
                            .addComponent(employeePylBenefitLbl))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, employeePylTGrossBrdrPnlLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(employeePylTGrossBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(employeePylTGrossBrdrPnlLayout.createSequentialGroup()
                                .addComponent(employeePylHourlyRateLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(employeePylHourlyRateFld, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(employeePylTGrossBrdrPnlLayout.createSequentialGroup()
                                .addComponent(employeePylOvertimeLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(employeePylOvertimeFld, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(employeePylTGrossBrdrPnlLayout.createSequentialGroup()
                                .addComponent(employeePylBasicSalaryLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(employeePylBasicSalaryFld, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(employeePylTGrossBrdrPnlLayout.createSequentialGroup()
                                .addComponent(employeePylHrsWorkedLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                                .addComponent(employeePylHrsWorkedFld, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(employeePylTGrossBrdrPnlLayout.createSequentialGroup()
                                .addComponent(employeePylRiceSubsidyLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(employeePylRiceSubsidyFld, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, employeePylTGrossBrdrPnlLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(employeePylTGrossLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(employeePylTGrossFld, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, employeePylTGrossBrdrPnlLayout.createSequentialGroup()
                                .addComponent(employeePylCltAllowanceLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(employeePylCltAllowanceFld, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, employeePylTGrossBrdrPnlLayout.createSequentialGroup()
                                .addComponent(employeePylPhnAllowanceLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(employeePylPhnAllowanceFld, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(26, 26, 26))
        );
        employeePylTGrossBrdrPnlLayout.setVerticalGroup(
            employeePylTGrossBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeePylTGrossBrdrPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(employeePylEarningLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(employeePylTGrossBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employeePylBasicSalaryLbl)
                    .addComponent(employeePylBasicSalaryFld, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(employeePylTGrossBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employeePylOvertimeLbl)
                    .addComponent(employeePylOvertimeFld, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(employeePylTGrossBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employeePylHrsWorkedLbl)
                    .addComponent(employeePylHrsWorkedFld, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(employeePylTGrossBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employeePylHourlyRateLbl)
                    .addComponent(employeePylHourlyRateFld, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(employeePylBenefitLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(employeePylTGrossBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(employeePylRiceSubsidyFld, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeePylRiceSubsidyLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(employeePylTGrossBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employeePylPhnAllowanceFld, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeePylPhnAllowanceLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(employeePylTGrossBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employeePylCltAllowanceFld, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeePylCltAllowanceLbl))
                .addGap(28, 28, 28)
                .addGroup(employeePylTGrossBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employeePylTGrossLbl)
                    .addComponent(employeePylTGrossFld, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        employeePylEarningLbl.getAccessibleContext().setAccessibleName("employeePylEarningLbl");
        employeePylBasicSalaryLbl.getAccessibleContext().setAccessibleName("employeePylBasicSalaryLbl");
        employeePylOvertimeLbl.getAccessibleContext().setAccessibleName("employeePylOvertimeLbl");
        employeePylHrsWorkedLbl.getAccessibleContext().setAccessibleName("employeePylHrsWorkedLbl");
        employeePylBenefitLbl.getAccessibleContext().setAccessibleName("employeePylBenefitLbl");
        employeePylRiceSubsidyLbl.getAccessibleContext().setAccessibleName("employeePylRiceSubsidyLbl");
        employeePylPhnAllowanceLbl.getAccessibleContext().setAccessibleName("employeePylPhnAllowanceLbl");
        employeePylCltAllowanceLbl.getAccessibleContext().setAccessibleName("employeePylCltAllowanceLbl");
        employeePylBasicSalaryFld.getAccessibleContext().setAccessibleName("employeePylBasicSalaryFld");
        employeePylOvertimeFld.getAccessibleContext().setAccessibleName("employeePylOvertimeFld");
        employeePylHrsWorkedFld.getAccessibleContext().setAccessibleName("employeePylHrsWorkedFld");
        employeePylRiceSubsidyFld.getAccessibleContext().setAccessibleName("employeePylRiceSubsidyFld");
        employeePylPhnAllowanceFld.getAccessibleContext().setAccessibleName("employeePylPhnAllowanceFld");
        employeePylCltAllowanceFld.getAccessibleContext().setAccessibleName("employeePylCltAllowanceFld");
        employeePylTGrossFld.getAccessibleContext().setAccessibleName("employeePylTGrossFld");
        employeePylTGrossLbl.getAccessibleContext().setAccessibleName("employeePylTGrossLbl");
        employeePylHourlyRateLbl.getAccessibleContext().setAccessibleName("employeePylHourlyRateLbl");
        employeePylHourlyRateFld.getAccessibleContext().setAccessibleName("employeePylHourlyRateFld");

        employeePylTDeductionBrdrPnl.setBackground(new java.awt.Color(233, 233, 233));
        employeePylTDeductionBrdrPnl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        employeePylTDeductionBrdrPnl.setForeground(new java.awt.Color(30, 58, 138));

        employeePylDeductionLbl.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        employeePylDeductionLbl.setForeground(new java.awt.Color(31, 41, 55));
        employeePylDeductionLbl.setText("Deduction");

        employeePylSSSLbl.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        employeePylSSSLbl.setForeground(new java.awt.Color(31, 41, 55));
        employeePylSSSLbl.setText("SSS");

        employeePylWithtaxLbl.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        employeePylWithtaxLbl.setForeground(new java.awt.Color(31, 41, 55));
        employeePylWithtaxLbl.setText("Withholding Tax");

        employeePylPhilHealthLbl.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        employeePylPhilHealthLbl.setForeground(new java.awt.Color(31, 41, 55));
        employeePylPhilHealthLbl.setText("PhilHealth");

        employeePylUndertimeLbl.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        employeePylUndertimeLbl.setForeground(new java.awt.Color(31, 41, 55));
        employeePylUndertimeLbl.setText("Undertime");

        employeePylSSSFld.setForeground(new java.awt.Color(31, 41, 55));
        employeePylSSSFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        employeePylSSSFld.setCaretColor(new java.awt.Color(31, 41, 55));
        employeePylSSSFld.setDisabledTextColor(new java.awt.Color(31, 41, 55));
        employeePylSSSFld.setEnabled(false);
        employeePylSSSFld.addActionListener(this::employeePylSSSFldActionPerformed);

        employeePylWithtaxFld.setForeground(new java.awt.Color(31, 41, 55));
        employeePylWithtaxFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        employeePylWithtaxFld.setCaretColor(new java.awt.Color(31, 41, 55));
        employeePylWithtaxFld.setDisabledTextColor(new java.awt.Color(31, 41, 55));
        employeePylWithtaxFld.setEnabled(false);
        employeePylWithtaxFld.addActionListener(this::employeePylWithtaxFldActionPerformed);

        employeePylPhilHealthFld.setForeground(new java.awt.Color(31, 41, 55));
        employeePylPhilHealthFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        employeePylPhilHealthFld.setCaretColor(new java.awt.Color(31, 41, 55));
        employeePylPhilHealthFld.setDisabledTextColor(new java.awt.Color(31, 41, 55));
        employeePylPhilHealthFld.setEnabled(false);
        employeePylPhilHealthFld.addActionListener(this::employeePylPhilHealthFldActionPerformed);

        employeePylUndertimeFld.setForeground(new java.awt.Color(31, 41, 55));
        employeePylUndertimeFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        employeePylUndertimeFld.setCaretColor(new java.awt.Color(31, 41, 55));
        employeePylUndertimeFld.setDisabledTextColor(new java.awt.Color(31, 41, 55));
        employeePylUndertimeFld.setEnabled(false);
        employeePylUndertimeFld.addActionListener(this::employeePylUndertimeFldActionPerformed);

        employeePylTDeductionFld.setForeground(new java.awt.Color(31, 41, 55));
        employeePylTDeductionFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        employeePylTDeductionFld.setCaretColor(new java.awt.Color(31, 41, 55));
        employeePylTDeductionFld.setDisabledTextColor(new java.awt.Color(31, 41, 55));
        employeePylTDeductionFld.setEnabled(false);
        employeePylTDeductionFld.addActionListener(this::employeePylTDeductionFldActionPerformed);

        employeePylTDeductionLbl.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        employeePylTDeductionLbl.setForeground(new java.awt.Color(31, 41, 55));
        employeePylTDeductionLbl.setText("Total Deduction");

        employeePylPagIbigFld.setForeground(new java.awt.Color(31, 41, 55));
        employeePylPagIbigFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        employeePylPagIbigFld.setCaretColor(new java.awt.Color(31, 41, 55));
        employeePylPagIbigFld.setDisabledTextColor(new java.awt.Color(31, 41, 55));
        employeePylPagIbigFld.setEnabled(false);
        employeePylPagIbigFld.addActionListener(this::employeePylPagIbigFldActionPerformed);

        employeePylPagIbigLbl.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        employeePylPagIbigLbl.setForeground(new java.awt.Color(31, 41, 55));
        employeePylPagIbigLbl.setText("Pag-Ibig");

        javax.swing.GroupLayout employeePylTDeductionBrdrPnlLayout = new javax.swing.GroupLayout(employeePylTDeductionBrdrPnl);
        employeePylTDeductionBrdrPnl.setLayout(employeePylTDeductionBrdrPnlLayout);
        employeePylTDeductionBrdrPnlLayout.setHorizontalGroup(
            employeePylTDeductionBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, employeePylTDeductionBrdrPnlLayout.createSequentialGroup()
                .addGroup(employeePylTDeductionBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, employeePylTDeductionBrdrPnlLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(employeePylDeductionLbl)
                        .addGap(0, 97, Short.MAX_VALUE))
                    .addGroup(employeePylTDeductionBrdrPnlLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(employeePylTDeductionLbl)
                        .addGap(18, 18, 18)
                        .addComponent(employeePylTDeductionFld, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, employeePylTDeductionBrdrPnlLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(employeePylTDeductionBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(employeePylTDeductionBrdrPnlLayout.createSequentialGroup()
                                .addComponent(employeePylPagIbigLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(employeePylPagIbigFld, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(employeePylTDeductionBrdrPnlLayout.createSequentialGroup()
                                .addComponent(employeePylUndertimeLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(employeePylUndertimeFld, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(employeePylTDeductionBrdrPnlLayout.createSequentialGroup()
                                .addComponent(employeePylSSSLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(employeePylSSSFld, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(employeePylTDeductionBrdrPnlLayout.createSequentialGroup()
                                .addComponent(employeePylPhilHealthLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(employeePylPhilHealthFld, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(employeePylTDeductionBrdrPnlLayout.createSequentialGroup()
                                .addComponent(employeePylWithtaxLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(employeePylWithtaxFld, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(20, 20, 20))
        );
        employeePylTDeductionBrdrPnlLayout.setVerticalGroup(
            employeePylTDeductionBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, employeePylTDeductionBrdrPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(employeePylDeductionLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(employeePylTDeductionBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employeePylSSSLbl)
                    .addComponent(employeePylSSSFld, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(employeePylTDeductionBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employeePylPagIbigFld, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeePylPagIbigLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(employeePylTDeductionBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employeePylPhilHealthLbl)
                    .addComponent(employeePylPhilHealthFld, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(employeePylTDeductionBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employeePylWithtaxLbl)
                    .addComponent(employeePylWithtaxFld, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(employeePylTDeductionBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employeePylUndertimeLbl)
                    .addComponent(employeePylUndertimeFld, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(employeePylTDeductionBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employeePylTDeductionFld, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeePylTDeductionLbl))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        employeePylDeductionLbl.getAccessibleContext().setAccessibleName("employeePylDeductionLbl");
        employeePylSSSLbl.getAccessibleContext().setAccessibleName("employeePylSSSLbl");
        employeePylWithtaxLbl.getAccessibleContext().setAccessibleName("employeePylWithtaxLbl");
        employeePylPhilHealthLbl.getAccessibleContext().setAccessibleName("employeePylPhilHealthLbl");
        employeePylUndertimeLbl.getAccessibleContext().setAccessibleName("employeePylUndertimeLbl");
        employeePylSSSFld.getAccessibleContext().setAccessibleName("employeePylSSSFld");
        employeePylWithtaxFld.getAccessibleContext().setAccessibleName("employeePylWithtaxFld");
        employeePylPhilHealthFld.getAccessibleContext().setAccessibleName("employeePylPhilHealthFld");
        employeePylUndertimeFld.getAccessibleContext().setAccessibleName("employeePylUndertimeFld");
        employeePylTDeductionFld.getAccessibleContext().setAccessibleName("employeePylTDeductionFld");
        employeePylTDeductionLbl.getAccessibleContext().setAccessibleName("employeePylTDeductionLbl");
        employeePylPagIbigFld.getAccessibleContext().setAccessibleName("employeePylPagIbigFld");
        employeePylPagIbigLbl.getAccessibleContext().setAccessibleName("employeePylPagIbigLbl");

        employeePylNetPayLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        employeePylNetPayLbl.setForeground(new java.awt.Color(31, 41, 55));
        employeePylNetPayLbl.setText("Net Pay");

        employeePylNetPayFld.setBackground(new java.awt.Color(34, 197, 94));
        employeePylNetPayFld.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        employeePylNetPayFld.setForeground(new java.awt.Color(255, 255, 255));
        employeePylNetPayFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        employeePylNetPayFld.setCaretColor(new java.awt.Color(255, 255, 255));
        employeePylNetPayFld.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        employeePylNetPayFld.setEnabled(false);
        employeePylNetPayFld.addActionListener(this::employeePylNetPayFldActionPerformed);

        javax.swing.GroupLayout employeePylSCalculatorBrdrPnlLayout = new javax.swing.GroupLayout(employeePylSCalculatorBrdrPnl);
        employeePylSCalculatorBrdrPnl.setLayout(employeePylSCalculatorBrdrPnlLayout);
        employeePylSCalculatorBrdrPnlLayout.setHorizontalGroup(
            employeePylSCalculatorBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeePylSCalculatorBrdrPnlLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(employeePylTGrossBrdrPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(employeePylSCalculatorBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(employeePylTDeductionBrdrPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, employeePylSCalculatorBrdrPnlLayout.createSequentialGroup()
                        .addComponent(employeePylNetPayLbl)
                        .addGap(46, 46, 46)
                        .addComponent(employeePylNetPayFld, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, employeePylSCalculatorBrdrPnlLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(employeePylSCalculatorLbl)
                .addGap(283, 283, 283))
        );
        employeePylSCalculatorBrdrPnlLayout.setVerticalGroup(
            employeePylSCalculatorBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeePylSCalculatorBrdrPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(employeePylSCalculatorLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(employeePylSCalculatorBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(employeePylSCalculatorBrdrPnlLayout.createSequentialGroup()
                        .addComponent(employeePylTDeductionBrdrPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addGroup(employeePylSCalculatorBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(employeePylNetPayLbl)
                            .addComponent(employeePylNetPayFld, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(employeePylTGrossBrdrPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        employeePylSCalculatorLbl.getAccessibleContext().setAccessibleName("employeePylSCalculatorLbl");
        employeePylTGrossBrdrPnl.getAccessibleContext().setAccessibleName("employeePylTGrossBrdrPnl");
        employeePylTDeductionBrdrPnl.getAccessibleContext().setAccessibleName("employeePylTDeductionBrdrPnl");
        employeePylNetPayLbl.getAccessibleContext().setAccessibleName("employeePylNetPayLbl");
        employeePylNetPayFld.getAccessibleContext().setAccessibleName("employeePylNetPayFld");

        employeePylPrlDateLbl.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        employeePylPrlDateLbl.setForeground(new java.awt.Color(31, 41, 55));
        employeePylPrlDateLbl.setText("Payroll Date");

        employeePylENumberFld.setForeground(new java.awt.Color(31, 41, 55));
        employeePylENumberFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        employeePylENumberFld.setCaretColor(new java.awt.Color(31, 41, 55));
        employeePylENumberFld.setDisabledTextColor(new java.awt.Color(31, 41, 55));
        employeePylENumberFld.setEnabled(false);
        employeePylENumberFld.addActionListener(this::employeePylENumberFldActionPerformed);

        employeePylPylPnl.setBackground(new java.awt.Color(30, 58, 138));
        employeePylPylPnl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        employeePylPylPnl.setForeground(new java.awt.Color(30, 58, 138));

        employeePylPylLbl.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        employeePylPylLbl.setForeground(new java.awt.Color(255, 255, 255));
        employeePylPylLbl.setText(" Payslip ");

        javax.swing.GroupLayout employeePylPylPnlLayout = new javax.swing.GroupLayout(employeePylPylPnl);
        employeePylPylPnl.setLayout(employeePylPylPnlLayout);
        employeePylPylPnlLayout.setHorizontalGroup(
            employeePylPylPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeePylPylPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(employeePylPylLbl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        employeePylPylPnlLayout.setVerticalGroup(
            employeePylPylPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(employeePylPylLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        employeePylPylLbl.getAccessibleContext().setAccessibleName("employeePylPylLbl");

        employeePylPrlPeriodFld.setForeground(new java.awt.Color(31, 41, 55));
        employeePylPrlPeriodFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        employeePylPrlPeriodFld.setCaretColor(new java.awt.Color(31, 41, 55));
        employeePylPrlPeriodFld.setDisabledTextColor(new java.awt.Color(31, 41, 55));
        employeePylPrlPeriodFld.setEnabled(false);
        employeePylPrlPeriodFld.addActionListener(this::employeePylPrlPeriodFldActionPerformed);

        employeePylFADisputeBtn.setBackground(new java.awt.Color(239, 68, 68));
        employeePylFADisputeBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        employeePylFADisputeBtn.setForeground(new java.awt.Color(255, 255, 255));
        employeePylFADisputeBtn.setText("File A Dispute");
        employeePylFADisputeBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        employeePylFADisputeBtn.addActionListener(this::employeePylFADisputeBtnActionPerformed);

        employeePylBackBtn.setBackground(new java.awt.Color(30, 58, 138));
        employeePylBackBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        employeePylBackBtn.setForeground(new java.awt.Color(255, 255, 255));
        employeePylBackBtn.setText("Back");
        employeePylBackBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        employeePylBackBtn.addActionListener(this::employeePylBackBtnActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(employeePylSidebarPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(46, 46, 46)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(employeePylENameLbl)
                                .addComponent(employeePylENumberLbl))
                            .addGap(30, 30, 30)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(employeePylENumberFld, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(employeePylENameFld, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(37, 37, 37)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(employeePylPrlDateLbl)
                                    .addGap(39, 39, 39)
                                    .addComponent(employeePylPrlDateFld, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(employeePylPrlPeriodLbl)
                                    .addGap(28, 28, 28)
                                    .addComponent(employeePylPrlPeriodFld, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(employeePylBackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(employeePylPylPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(employeePylSCalculatorBrdrPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 709, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(298, 298, 298)
                        .addComponent(employeePylFADisputeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(employeePylPylPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(employeePylPrlDateFld, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(employeePylPrlDateLbl)
                            .addComponent(employeePylENumberFld, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(employeePylENumberLbl))))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(employeePylPrlPeriodFld, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(employeePylPrlPeriodLbl)
                            .addComponent(employeePylENameFld, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(employeePylENameLbl))))
                .addGap(18, 18, 18)
                .addComponent(employeePylSCalculatorBrdrPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(employeePylFADisputeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(employeePylBackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
            .addComponent(employeePylSidebarPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        employeePylSidebarPnl.getAccessibleContext().setAccessibleName("employeePylSidebarPnl");
        employeePylPrlDateFld.getAccessibleContext().setAccessibleName("employeePylPrlDateFld");
        employeePylPrlPeriodLbl.getAccessibleContext().setAccessibleName("employeePylPrlPeriodLbl");
        employeePylENameFld.getAccessibleContext().setAccessibleName("employeePylENameFld");
        employeePylENameLbl.getAccessibleContext().setAccessibleName("employeePylENameLbl");
        employeePylENumberLbl.getAccessibleContext().setAccessibleName("employeePylENumberLbl");
        employeePylSCalculatorBrdrPnl.getAccessibleContext().setAccessibleName("employeePylSCalculatorBrdrPnl");
        employeePylPrlDateLbl.getAccessibleContext().setAccessibleName("employeePylPrlDateLbl");
        employeePylENumberFld.getAccessibleContext().setAccessibleName("employeePylENumberFld");
        employeePylPylPnl.getAccessibleContext().setAccessibleName("employeePylPylPnl");
        employeePylPrlPeriodFld.getAccessibleContext().setAccessibleName("employeePylPrlPeriodFld");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void employeePylMainDashboardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeePylMainDashboardBtnActionPerformed
        // TODO add your handling code here:
        GuiUtil.openFrame(this);
    }//GEN-LAST:event_employeePylMainDashboardBtnActionPerformed

    private void employeePylPrlDateFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeePylPrlDateFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeePylPrlDateFldActionPerformed

    private void employeePylENameFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeePylENameFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeePylENameFldActionPerformed

    private void employeePylBasicSalaryFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeePylBasicSalaryFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeePylBasicSalaryFldActionPerformed

    private void employeePylOvertimeFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeePylOvertimeFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeePylOvertimeFldActionPerformed

    private void employeePylHrsWorkedFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeePylHrsWorkedFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeePylHrsWorkedFldActionPerformed

    private void employeePylRiceSubsidyFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeePylRiceSubsidyFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeePylRiceSubsidyFldActionPerformed

    private void employeePylPhnAllowanceFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeePylPhnAllowanceFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeePylPhnAllowanceFldActionPerformed

    private void employeePylCltAllowanceFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeePylCltAllowanceFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeePylCltAllowanceFldActionPerformed

    private void employeePylTGrossFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeePylTGrossFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeePylTGrossFldActionPerformed

    private void employeePylSSSFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeePylSSSFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeePylSSSFldActionPerformed

    private void employeePylWithtaxFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeePylWithtaxFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeePylWithtaxFldActionPerformed

    private void employeePylPhilHealthFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeePylPhilHealthFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeePylPhilHealthFldActionPerformed

    private void employeePylPagIbigFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeePylPagIbigFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeePylPagIbigFldActionPerformed

    private void employeePylUndertimeFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeePylUndertimeFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeePylUndertimeFldActionPerformed

    private void employeePylTDeductionFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeePylTDeductionFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeePylTDeductionFldActionPerformed

    private void employeePylNetPayFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeePylNetPayFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeePylNetPayFldActionPerformed

    private void employeePylENumberFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeePylENumberFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeePylENumberFldActionPerformed

    private void employeePylPrlPeriodFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeePylPrlPeriodFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeePylPrlPeriodFldActionPerformed

    private void employeePylHourlyRateFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeePylHourlyRateFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeePylHourlyRateFldActionPerformed

    private void employeePylFADisputeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeePylFADisputeBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeePylFADisputeBtnActionPerformed

    private void employeePylBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeePylBackBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeePylBackBtnActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton employeePylBackBtn;
    private javax.swing.JTextField employeePylBasicSalaryFld;
    private javax.swing.JLabel employeePylBasicSalaryLbl;
    private javax.swing.JLabel employeePylBenefitLbl;
    private javax.swing.JTextField employeePylCltAllowanceFld;
    private javax.swing.JLabel employeePylCltAllowanceLbl;
    private javax.swing.JLabel employeePylDeductionLbl;
    private javax.swing.JTextField employeePylENameFld;
    private javax.swing.JLabel employeePylENameLbl;
    private javax.swing.JTextField employeePylENumberFld;
    private javax.swing.JLabel employeePylENumberLbl;
    private javax.swing.JLabel employeePylEarningLbl;
    private javax.swing.JButton employeePylFADisputeBtn;
    private javax.swing.JTextField employeePylHourlyRateFld;
    private javax.swing.JLabel employeePylHourlyRateLbl;
    private javax.swing.JTextField employeePylHrsWorkedFld;
    private javax.swing.JLabel employeePylHrsWorkedLbl;
    private javax.swing.JButton employeePylMainDashboardBtn;
    private javax.swing.JLabel employeePylMotorPHIconImgLbl;
    private javax.swing.JTextField employeePylNetPayFld;
    private javax.swing.JLabel employeePylNetPayLbl;
    private javax.swing.JTextField employeePylOvertimeFld;
    private javax.swing.JLabel employeePylOvertimeLbl;
    private javax.swing.JTextField employeePylPagIbigFld;
    private javax.swing.JLabel employeePylPagIbigLbl;
    private javax.swing.JTextField employeePylPhilHealthFld;
    private javax.swing.JLabel employeePylPhilHealthLbl;
    private javax.swing.JTextField employeePylPhnAllowanceFld;
    private javax.swing.JLabel employeePylPhnAllowanceLbl;
    private javax.swing.JTextField employeePylPrlDateFld;
    private javax.swing.JLabel employeePylPrlDateLbl;
    private javax.swing.JTextField employeePylPrlPeriodFld;
    private javax.swing.JLabel employeePylPrlPeriodLbl;
    private javax.swing.JLabel employeePylPylLbl;
    private javax.swing.JPanel employeePylPylPnl;
    private javax.swing.JTextField employeePylRiceSubsidyFld;
    private javax.swing.JLabel employeePylRiceSubsidyLbl;
    private javax.swing.JPanel employeePylSCalculatorBrdrPnl;
    private javax.swing.JLabel employeePylSCalculatorLbl;
    private javax.swing.JTextField employeePylSSSFld;
    private javax.swing.JLabel employeePylSSSLbl;
    private javax.swing.JPanel employeePylSidebarPnl;
    private javax.swing.JPanel employeePylTDeductionBrdrPnl;
    private javax.swing.JTextField employeePylTDeductionFld;
    private javax.swing.JLabel employeePylTDeductionLbl;
    private javax.swing.JPanel employeePylTGrossBrdrPnl;
    private javax.swing.JTextField employeePylTGrossFld;
    private javax.swing.JLabel employeePylTGrossLbl;
    private javax.swing.JTextField employeePylUndertimeFld;
    private javax.swing.JLabel employeePylUndertimeLbl;
    private javax.swing.JTextField employeePylWithtaxFld;
    private javax.swing.JLabel employeePylWithtaxLbl;
    // End of variables declaration//GEN-END:variables
}
