/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.motorph.ui;

/**
 *
 * @author Lenovo
 */
public class EmployeeDisputeUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EmployeeDisputeUI.class.getName());

    /**
     * Creates new form EmployeeDisputeFrame
     */
    public EmployeeDisputeUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        employeeDisputeSidebarPnl = new javax.swing.JPanel();
        employeeDisputeDDetailsBtn = new javax.swing.JButton();
        employeeDisputeMainDashboardBtn = new javax.swing.JButton();
        employeeDisputeMotorPHIconImgLbl = new javax.swing.JLabel();
        employeeDisputeDListBtn = new javax.swing.JButton();
        employeeDDetailsPnl = new javax.swing.JPanel();
        employeeDisputeDDetailsLbl = new javax.swing.JLabel();
        employeeDisputeDFormBrdrPnl = new javax.swing.JPanel();
        employeeDisputeDFormPnl = new javax.swing.JPanel();
        employeeDisputeDFormLbl = new javax.swing.JLabel();
        employeeDisputeFADisputeBrdrPnl = new javax.swing.JPanel();
        employeeDisputeFADisputePnl = new javax.swing.JPanel();
        employeeDisputeFADisputeLbl = new javax.swing.JLabel();
        employeeDisputeTTypeCbx = new javax.swing.JComboBox<>();
        employeeDisputeReasonLbl = new javax.swing.JLabel();
        employeeDisputeReasonFld = new javax.swing.JTextField();
        employeeDisputeSubmitBtn = new javax.swing.JButton();
        employeeDisputeDateDtChsr = new com.toedter.calendar.JDateChooser();
        employeeDisputeDateLbl = new javax.swing.JLabel();
        employeeDisputeRecordBrdrPnl = new javax.swing.JPanel();
        employeeDisputeRecordsScrlPnl = new javax.swing.JScrollPane();
        employeeDisputeRecordsTbl = new javax.swing.JTable();
        employeeDisputeRecordsLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1000, 700));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
        });

        employeeDisputeSidebarPnl.setBackground(new java.awt.Color(30, 58, 138));

        employeeDisputeDDetailsBtn.setBackground(new java.awt.Color(30, 42, 56));
        employeeDisputeDDetailsBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        employeeDisputeDDetailsBtn.setForeground(new java.awt.Color(255, 255, 255));
        employeeDisputeDDetailsBtn.setText("Dispute Details");
        employeeDisputeDDetailsBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        employeeDisputeDDetailsBtn.addActionListener(this::employeeDisputeDDetailsBtnActionPerformed);

        employeeDisputeMainDashboardBtn.setBackground(new java.awt.Color(30, 42, 56));
        employeeDisputeMainDashboardBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        employeeDisputeMainDashboardBtn.setForeground(new java.awt.Color(255, 255, 255));
        employeeDisputeMainDashboardBtn.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        employeeDisputeMainDashboardBtn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        employeeDisputeMainDashboardBtn.setLabel("Main Dashboard");
        employeeDisputeMainDashboardBtn.addActionListener(this::employeeDisputeMainDashboardBtnActionPerformed);

        employeeDisputeMotorPHIconImgLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/motorph/img/MotorPHIconImg.png"))); // NOI18N

        employeeDisputeDListBtn.setBackground(new java.awt.Color(30, 42, 56));
        employeeDisputeDListBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        employeeDisputeDListBtn.setForeground(new java.awt.Color(255, 255, 255));
        employeeDisputeDListBtn.setText("Dispute List");
        employeeDisputeDListBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        employeeDisputeDListBtn.addActionListener(this::employeeDisputeDListBtnActionPerformed);

        javax.swing.GroupLayout employeeDisputeSidebarPnlLayout = new javax.swing.GroupLayout(employeeDisputeSidebarPnl);
        employeeDisputeSidebarPnl.setLayout(employeeDisputeSidebarPnlLayout);
        employeeDisputeSidebarPnlLayout.setHorizontalGroup(
            employeeDisputeSidebarPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeeDisputeSidebarPnlLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(employeeDisputeMainDashboardBtn))
            .addGroup(employeeDisputeSidebarPnlLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(employeeDisputeSidebarPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(employeeDisputeDListBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeeDisputeDDetailsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(employeeDisputeSidebarPnlLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(employeeDisputeMotorPHIconImgLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        employeeDisputeSidebarPnlLayout.setVerticalGroup(
            employeeDisputeSidebarPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeeDisputeSidebarPnlLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(employeeDisputeSidebarPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(employeeDisputeSidebarPnlLayout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(employeeDisputeDDetailsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(employeeDisputeMotorPHIconImgLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(employeeDisputeDListBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 355, Short.MAX_VALUE)
                .addComponent(employeeDisputeMainDashboardBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        employeeDisputeDDetailsBtn.getAccessibleContext().setAccessibleName("employeeDisputeDDetailsBtn");
        employeeDisputeMainDashboardBtn.getAccessibleContext().setAccessibleName("employeeDisputeMainDashboardBtn");
        employeeDisputeMotorPHIconImgLbl.getAccessibleContext().setAccessibleName("employeeDisputeMotorPHIconImgLbl");
        employeeDisputeDListBtn.getAccessibleContext().setAccessibleName("employeeDisputeDListBtn");

        employeeDDetailsPnl.setBackground(new java.awt.Color(30, 58, 138));
        employeeDDetailsPnl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        employeeDDetailsPnl.setForeground(new java.awt.Color(30, 58, 138));
        employeeDDetailsPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        employeeDisputeDDetailsLbl.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        employeeDisputeDDetailsLbl.setForeground(new java.awt.Color(255, 255, 255));
        employeeDisputeDDetailsLbl.setText(" Dispute Details");
        employeeDDetailsPnl.add(employeeDisputeDDetailsLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 1, 200, 46));
        employeeDisputeDDetailsLbl.getAccessibleContext().setAccessibleName("employeeDisputeDDetailsLbl");

        employeeDisputeDFormBrdrPnl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 2, true));

        employeeDisputeDFormPnl.setBackground(new java.awt.Color(30, 58, 138));
        employeeDisputeDFormPnl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        employeeDisputeDFormPnl.setForeground(new java.awt.Color(30, 58, 138));
        employeeDisputeDFormPnl.setPreferredSize(new java.awt.Dimension(126, 40));

        employeeDisputeDFormLbl.setBackground(new java.awt.Color(255, 255, 255));
        employeeDisputeDFormLbl.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        employeeDisputeDFormLbl.setForeground(new java.awt.Color(255, 255, 255));
        employeeDisputeDFormLbl.setText("Dispute Form");
        employeeDisputeDFormLbl.setToolTipText("");

        javax.swing.GroupLayout employeeDisputeDFormPnlLayout = new javax.swing.GroupLayout(employeeDisputeDFormPnl);
        employeeDisputeDFormPnl.setLayout(employeeDisputeDFormPnlLayout);
        employeeDisputeDFormPnlLayout.setHorizontalGroup(
            employeeDisputeDFormPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, employeeDisputeDFormPnlLayout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(employeeDisputeDFormLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        employeeDisputeDFormPnlLayout.setVerticalGroup(
            employeeDisputeDFormPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeeDisputeDFormPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(employeeDisputeDFormLbl)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        employeeDisputeDFormLbl.getAccessibleContext().setAccessibleName("employeeDisputeDFormLbl");

        employeeDisputeFADisputeBrdrPnl.setBackground(new java.awt.Color(233, 233, 233));
        employeeDisputeFADisputeBrdrPnl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        employeeDisputeFADisputeBrdrPnl.setForeground(new java.awt.Color(178, 178, 178));

        employeeDisputeFADisputePnl.setBackground(new java.awt.Color(146, 192, 253));
        employeeDisputeFADisputePnl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        employeeDisputeFADisputePnl.setForeground(new java.awt.Color(30, 58, 138));
        employeeDisputeFADisputePnl.setPreferredSize(new java.awt.Dimension(126, 40));

        employeeDisputeFADisputeLbl.setBackground(new java.awt.Color(255, 255, 255));
        employeeDisputeFADisputeLbl.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        employeeDisputeFADisputeLbl.setForeground(new java.awt.Color(31, 41, 55));
        employeeDisputeFADisputeLbl.setText("File A Dispute");
        employeeDisputeFADisputeLbl.setToolTipText("");

        javax.swing.GroupLayout employeeDisputeFADisputePnlLayout = new javax.swing.GroupLayout(employeeDisputeFADisputePnl);
        employeeDisputeFADisputePnl.setLayout(employeeDisputeFADisputePnlLayout);
        employeeDisputeFADisputePnlLayout.setHorizontalGroup(
            employeeDisputeFADisputePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeeDisputeFADisputePnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(employeeDisputeFADisputeLbl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        employeeDisputeFADisputePnlLayout.setVerticalGroup(
            employeeDisputeFADisputePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, employeeDisputeFADisputePnlLayout.createSequentialGroup()
                .addComponent(employeeDisputeFADisputeLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addContainerGap())
        );

        employeeDisputeFADisputeLbl.getAccessibleContext().setAccessibleName("employeeDisputeFADisputeLbl");

        employeeDisputeTTypeCbx.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        employeeDisputeTTypeCbx.setForeground(new java.awt.Color(31, 41, 55));
        employeeDisputeTTypeCbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose", "HR", "IT" }));
        employeeDisputeTTypeCbx.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        employeeDisputeTTypeCbx.addActionListener(this::employeeDisputeTTypeCbxActionPerformed);

        employeeDisputeReasonLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        employeeDisputeReasonLbl.setForeground(new java.awt.Color(31, 41, 55));
        employeeDisputeReasonLbl.setText("Reason");

        employeeDisputeReasonFld.setForeground(new java.awt.Color(31, 41, 55));
        employeeDisputeReasonFld.setText(" ");
        employeeDisputeReasonFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        employeeDisputeReasonFld.addActionListener(this::employeeDisputeReasonFldActionPerformed);

        employeeDisputeSubmitBtn.setBackground(new java.awt.Color(59, 130, 246));
        employeeDisputeSubmitBtn.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        employeeDisputeSubmitBtn.setForeground(new java.awt.Color(255, 255, 255));
        employeeDisputeSubmitBtn.setText("Submit");
        employeeDisputeSubmitBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(30, 42, 56)));
        employeeDisputeSubmitBtn.addActionListener(this::employeeDisputeSubmitBtnActionPerformed);

        employeeDisputeDateDtChsr.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        employeeDisputeDateDtChsr.setForeground(new java.awt.Color(31, 41, 55));

        employeeDisputeDateLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        employeeDisputeDateLbl.setForeground(new java.awt.Color(31, 41, 55));
        employeeDisputeDateLbl.setText("Date");

        javax.swing.GroupLayout employeeDisputeFADisputeBrdrPnlLayout = new javax.swing.GroupLayout(employeeDisputeFADisputeBrdrPnl);
        employeeDisputeFADisputeBrdrPnl.setLayout(employeeDisputeFADisputeBrdrPnlLayout);
        employeeDisputeFADisputeBrdrPnlLayout.setHorizontalGroup(
            employeeDisputeFADisputeBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeeDisputeFADisputeBrdrPnlLayout.createSequentialGroup()
                .addGap(18, 20, Short.MAX_VALUE)
                .addGroup(employeeDisputeFADisputeBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(employeeDisputeReasonLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeeDisputeReasonFld, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(employeeDisputeFADisputeBrdrPnlLayout.createSequentialGroup()
                        .addGroup(employeeDisputeFADisputeBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(employeeDisputeFADisputePnl, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(employeeDisputeDateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(employeeDisputeFADisputeBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(employeeDisputeDateDtChsr, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(employeeDisputeFADisputeBrdrPnlLayout.createSequentialGroup()
                                .addComponent(employeeDisputeTTypeCbx, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(207, 207, 207)
                                .addComponent(employeeDisputeSubmitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        employeeDisputeFADisputeBrdrPnlLayout.setVerticalGroup(
            employeeDisputeFADisputeBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeeDisputeFADisputeBrdrPnlLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(employeeDisputeFADisputeBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(employeeDisputeFADisputePnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeeDisputeSubmitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeeDisputeTTypeCbx, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(employeeDisputeFADisputeBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(employeeDisputeDateDtChsr, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeeDisputeDateLbl))
                .addGap(5, 5, 5)
                .addComponent(employeeDisputeReasonLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(employeeDisputeReasonFld, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        employeeDisputeFADisputePnl.getAccessibleContext().setAccessibleName("employeeDisputeFADisputePnl");
        employeeDisputeTTypeCbx.getAccessibleContext().setAccessibleName("employeeDisputeTTypeCbx");
        employeeDisputeReasonLbl.getAccessibleContext().setAccessibleName("employeeDisputeReasonLbl");
        employeeDisputeReasonFld.getAccessibleContext().setAccessibleName("employeeDisputeReasonFld");
        employeeDisputeSubmitBtn.getAccessibleContext().setAccessibleName("employeeDisputeSubmitBtn");
        employeeDisputeDateDtChsr.getAccessibleContext().setAccessibleName("employeeDisputeDateDtChsr");
        employeeDisputeDateLbl.getAccessibleContext().setAccessibleName("employeeDisputeDateLbl");

        javax.swing.GroupLayout employeeDisputeDFormBrdrPnlLayout = new javax.swing.GroupLayout(employeeDisputeDFormBrdrPnl);
        employeeDisputeDFormBrdrPnl.setLayout(employeeDisputeDFormBrdrPnlLayout);
        employeeDisputeDFormBrdrPnlLayout.setHorizontalGroup(
            employeeDisputeDFormBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeeDisputeDFormBrdrPnlLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(employeeDisputeFADisputeBrdrPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, employeeDisputeDFormBrdrPnlLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(employeeDisputeDFormPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(257, 257, 257))
        );
        employeeDisputeDFormBrdrPnlLayout.setVerticalGroup(
            employeeDisputeDFormBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, employeeDisputeDFormBrdrPnlLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(employeeDisputeDFormPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(employeeDisputeFADisputeBrdrPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        employeeDisputeDFormPnl.getAccessibleContext().setAccessibleName("employeeDisputeDFormPnl");
        employeeDisputeFADisputeBrdrPnl.getAccessibleContext().setAccessibleName("employeeDisputeFADisputeBrdrPnl");

        employeeDisputeRecordBrdrPnl.setBackground(new java.awt.Color(178, 178, 178));
        employeeDisputeRecordBrdrPnl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 2, true));
        employeeDisputeRecordBrdrPnl.setForeground(new java.awt.Color(30, 42, 56));

        employeeDisputeRecordsScrlPnl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));

        employeeDisputeRecordsTbl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        employeeDisputeRecordsTbl.setForeground(new java.awt.Color(30, 42, 56));
        employeeDisputeRecordsTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Date", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        employeeDisputeRecordsTbl.setEnabled(false);
        employeeDisputeRecordsTbl.setGridColor(new java.awt.Color(178, 178, 178));
        employeeDisputeRecordsTbl.setMinimumSize(new java.awt.Dimension(75, 100));
        employeeDisputeRecordsTbl.setSelectionForeground(new java.awt.Color(30, 42, 56));
        employeeDisputeRecordsScrlPnl.setViewportView(employeeDisputeRecordsTbl);
        employeeDisputeRecordsTbl.getAccessibleContext().setAccessibleName("employeeDisputeRecordsTbl");

        employeeDisputeRecordsLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        employeeDisputeRecordsLbl.setText("Records");

        javax.swing.GroupLayout employeeDisputeRecordBrdrPnlLayout = new javax.swing.GroupLayout(employeeDisputeRecordBrdrPnl);
        employeeDisputeRecordBrdrPnl.setLayout(employeeDisputeRecordBrdrPnlLayout);
        employeeDisputeRecordBrdrPnlLayout.setHorizontalGroup(
            employeeDisputeRecordBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeeDisputeRecordBrdrPnlLayout.createSequentialGroup()
                .addGroup(employeeDisputeRecordBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(employeeDisputeRecordBrdrPnlLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(employeeDisputeRecordsScrlPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 667, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(employeeDisputeRecordBrdrPnlLayout.createSequentialGroup()
                        .addGap(307, 307, 307)
                        .addComponent(employeeDisputeRecordsLbl)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        employeeDisputeRecordBrdrPnlLayout.setVerticalGroup(
            employeeDisputeRecordBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeeDisputeRecordBrdrPnlLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(employeeDisputeRecordsLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(employeeDisputeRecordsScrlPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        employeeDisputeRecordsScrlPnl.getAccessibleContext().setAccessibleName("employeeDisputeRecordsScrlPnl");
        employeeDisputeRecordsLbl.getAccessibleContext().setAccessibleName("employeeDisputeRecordsLbl");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(employeeDisputeSidebarPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(employeeDDetailsPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeeDisputeDFormBrdrPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(employeeDisputeRecordBrdrPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(employeeDDetailsPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(employeeDisputeRecordBrdrPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(employeeDisputeDFormBrdrPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
            .addComponent(employeeDisputeSidebarPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        employeeDisputeSidebarPnl.getAccessibleContext().setAccessibleName("employeeDisputeSidebarPnl");
        employeeDDetailsPnl.getAccessibleContext().setAccessibleName("employeeDDetailsPnl");
        employeeDisputeDFormBrdrPnl.getAccessibleContext().setAccessibleName("employeeDisputeDFormBrdrPnl");
        employeeDisputeRecordBrdrPnl.getAccessibleContext().setAccessibleName("employeeDisputeRecordBrdrPnl");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void employeeDisputeDDetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeDisputeDDetailsBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeDisputeDDetailsBtnActionPerformed

    private void employeeDisputeMainDashboardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeDisputeMainDashboardBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
        new MainAdminDashboardUI().setVisible(true);
    }//GEN-LAST:event_employeeDisputeMainDashboardBtnActionPerformed

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentHidden

    private void employeeDisputeTTypeCbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeDisputeTTypeCbxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeDisputeTTypeCbxActionPerformed

    private void employeeDisputeReasonFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeDisputeReasonFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeDisputeReasonFldActionPerformed

    private void employeeDisputeSubmitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeDisputeSubmitBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeDisputeSubmitBtnActionPerformed

    private void employeeDisputeDListBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeDisputeDListBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeDisputeDListBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EmployeeDisputeUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel employeeDDetailsPnl;
    private javax.swing.JButton employeeDisputeDDetailsBtn;
    private javax.swing.JLabel employeeDisputeDDetailsLbl;
    private javax.swing.JPanel employeeDisputeDFormBrdrPnl;
    private javax.swing.JLabel employeeDisputeDFormLbl;
    private javax.swing.JPanel employeeDisputeDFormPnl;
    private javax.swing.JButton employeeDisputeDListBtn;
    private com.toedter.calendar.JDateChooser employeeDisputeDateDtChsr;
    private javax.swing.JLabel employeeDisputeDateLbl;
    private javax.swing.JPanel employeeDisputeFADisputeBrdrPnl;
    private javax.swing.JLabel employeeDisputeFADisputeLbl;
    private javax.swing.JPanel employeeDisputeFADisputePnl;
    private javax.swing.JButton employeeDisputeMainDashboardBtn;
    private javax.swing.JLabel employeeDisputeMotorPHIconImgLbl;
    private javax.swing.JTextField employeeDisputeReasonFld;
    private javax.swing.JLabel employeeDisputeReasonLbl;
    private javax.swing.JPanel employeeDisputeRecordBrdrPnl;
    private javax.swing.JLabel employeeDisputeRecordsLbl;
    private javax.swing.JScrollPane employeeDisputeRecordsScrlPnl;
    private javax.swing.JTable employeeDisputeRecordsTbl;
    private javax.swing.JPanel employeeDisputeSidebarPnl;
    private javax.swing.JButton employeeDisputeSubmitBtn;
    private javax.swing.JComboBox<String> employeeDisputeTTypeCbx;
    // End of variables declaration//GEN-END:variables
}
