/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.motorph.ui;

import com.motorph.dao.CsvEmployeeDAO;
import com.motorph.model.Employee;
import com.motorph.model.Payslip;
import com.motorph.service.EmployeeService;

/**
 *
 * @author Lenovo
 */
public class EmployeePayslipUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EmployeePayslipUI.class.getName());
    private EmployeeService empService;
    /**
     * Creates new form EmployeePayslipFrame
     */
    public EmployeePayslipUI(Payslip payslip) {
        initComponents();
        
        this.empService = new EmployeeService(new CsvEmployeeDAO());
        
        populateEmployeeDetails(payslip);
        populateSalaryCalculations(payslip);
    }
    
    private void populateEmployeeDetails(Payslip payslip) {
        employeePylENameFld.setText(payslip.getEmployeeName());
        employeePylENumberFld.setText(payslip.getEmployeeNumber());
        employeePylPositionFld.setText(payslip.getPosition());
        employeePylPrlDateFld.setText(payslip.getPeriodStart() + " - " + payslip.getPeriodEnd());
        employeePylPrlPeriodFld.setText("Nothin yet");
        employeePylStatusFld.setText("IDK");
        
    }
    
    private void populateSalaryCalculations(Payslip payslip) {
        
        Employee emp = empService.findEmployee(payslip.getEmployeeNumber());
        
        employeePylBasicSalaryFld.setText(String.valueOf(emp.getBasicSalary()));
        employeePylOvertimeFld.setText("");
        employeePylHolidayFld.setText("");
        employeePylRiceSubsidyFld.setText(String.valueOf(payslip.getAllowanceBreakdown().getRiceSubsidy()));
        employeePylPhnAllowanceFld.setText(String.valueOf(payslip.getAllowanceBreakdown().getPhoneAllowance()));
        employeePylCltAllowanceFld.setText(String.valueOf(payslip.getAllowanceBreakdown().getClothingAllowance()));
        employeePylBonusTypeFld.setText("");
        employeePylTGrossFld.setText("");

        employeePylSSSFld.setText(String.valueOf(payslip.getDeductionBreakdown().getSss()));
        employeePylTINFld.setText("");
        employeePylPhilHealthFld.setText(String.valueOf(payslip.getDeductionBreakdown().getPhilHealth()));
        employeePylPagIbigFld.setText(String.valueOf(payslip.getDeductionBreakdown().getPagIbig()));
        employeePylLateFld.setText("");
        employeePylUndertimeFld.setText("");
        employeePylAbsentFld.setText("");
        employeePylTDeductionFld.setText(String.valueOf(payslip.getDeductionBreakdown().getTotal()));

        employeePylNetPayFld.setText(String.valueOf(payslip.getNetPay()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        employeePylSidebarPnl = new javax.swing.JPanel();
        employeePylPylRecordBtn = new javax.swing.JButton();
        employeePylMainDashboardBtn = new javax.swing.JButton();
        employeePylMotorPHIconImgLbl = new javax.swing.JLabel();
        employeePylPylBtn = new javax.swing.JButton();
        employeePylPrlDisputeBtn = new javax.swing.JButton();
        employeePylPrlDateFld = new javax.swing.JTextField();
        employeePylPrlPeriodLbl = new javax.swing.JLabel();
        employeePylENameFld = new javax.swing.JTextField();
        employeePylENameLbl = new javax.swing.JLabel();
        employeePylENumberLbl = new javax.swing.JLabel();
        employeePylCalculatorBrdrPnl = new javax.swing.JPanel();
        employeePylCalculatorLbl = new javax.swing.JLabel();
        employeePylTGrossBrdrPnl = new javax.swing.JPanel();
        employeePylEarningLbl = new javax.swing.JLabel();
        employeePylBasicSalaryLbl = new javax.swing.JLabel();
        employeePylOvertimeLbl = new javax.swing.JLabel();
        employeePylHolidayLbl = new javax.swing.JLabel();
        employeePylBenefitLbl = new javax.swing.JLabel();
        employeePylRiceSubsidyLbl = new javax.swing.JLabel();
        employeePylPhnAllowanceLbl = new javax.swing.JLabel();
        employeePylCltAllowanceLbl = new javax.swing.JLabel();
        employeePylBonusLbl = new javax.swing.JLabel();
        employeePylBonusTypeCbx = new javax.swing.JComboBox<>();
        employeePylBasicSalaryFld = new javax.swing.JTextField();
        employeePylOvertimeFld = new javax.swing.JTextField();
        employeePylHolidayFld = new javax.swing.JTextField();
        employeePylRiceSubsidyFld = new javax.swing.JTextField();
        employeePylPhnAllowanceFld = new javax.swing.JTextField();
        employeePylCltAllowanceFld = new javax.swing.JTextField();
        employeePylBonusTypeFld = new javax.swing.JTextField();
        employeePylTGrossFld = new javax.swing.JTextField();
        employeePylTGrossLbl = new javax.swing.JLabel();
        employeePylTDeductionBrdrPnl = new javax.swing.JPanel();
        employeePylDeductionLbl = new javax.swing.JLabel();
        employeePylSSSLbl = new javax.swing.JLabel();
        employeePylTINLbl = new javax.swing.JLabel();
        employeePylPhilHealthLbl = new javax.swing.JLabel();
        employeePylPagIbigLbl = new javax.swing.JLabel();
        employeePylLateLbl = new javax.swing.JLabel();
        employeePylUndertimeLbl = new javax.swing.JLabel();
        employeePylSSSFld = new javax.swing.JTextField();
        employeePylTINFld = new javax.swing.JTextField();
        employeePylPhilHealthFld = new javax.swing.JTextField();
        employeePylPagIbigFld = new javax.swing.JTextField();
        employeePylLateFld = new javax.swing.JTextField();
        employeePylUndertimeFld = new javax.swing.JTextField();
        employeePylAbsentLbl = new javax.swing.JLabel();
        employeePylAbsentFld = new javax.swing.JTextField();
        employeePylTDeductionFld = new javax.swing.JTextField();
        employeePylTDeductionLbl = new javax.swing.JLabel();
        employeePylNetPayLbl = new javax.swing.JLabel();
        employeePylNetPayFld = new javax.swing.JTextField();
        employeePylPrlDateLbl = new javax.swing.JLabel();
        employeePylPDFBtn = new javax.swing.JButton();
        employeePylENumberFld = new javax.swing.JTextField();
        employeePylEPylPnl = new javax.swing.JPanel();
        employeePylEPylLbl = new javax.swing.JLabel();
        employeePylPrlPeriodFld = new javax.swing.JTextField();
        employeePylSearchPnl = new javax.swing.JPanel();
        employeePylEntENumberFld = new javax.swing.JTextField();
        employeePylSearchIconImgLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        employeePylSidebarPnl.setBackground(new java.awt.Color(30, 58, 138));
        employeePylSidebarPnl.setPreferredSize(new java.awt.Dimension(262, 700));

        employeePylPylRecordBtn.setBackground(new java.awt.Color(30, 42, 56));
        employeePylPylRecordBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        employeePylPylRecordBtn.setForeground(new java.awt.Color(255, 255, 255));
        employeePylPylRecordBtn.setText("Payslip Record");
        employeePylPylRecordBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        employeePylPylRecordBtn.addActionListener(this::employeePylPylRecordBtnActionPerformed);

        employeePylMainDashboardBtn.setBackground(new java.awt.Color(30, 42, 56));
        employeePylMainDashboardBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        employeePylMainDashboardBtn.setForeground(new java.awt.Color(255, 255, 255));
        employeePylMainDashboardBtn.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        employeePylMainDashboardBtn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        employeePylMainDashboardBtn.setLabel("Main Dashboard");
        employeePylMainDashboardBtn.addActionListener(this::employeePylMainDashboardBtnActionPerformed);

        employeePylMotorPHIconImgLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/motorph/img/MotorPHIconImg.png"))); // NOI18N

        employeePylPylBtn.setBackground(new java.awt.Color(30, 42, 56));
        employeePylPylBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        employeePylPylBtn.setForeground(new java.awt.Color(255, 255, 255));
        employeePylPylBtn.setText("Payslip");
        employeePylPylBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        employeePylPylBtn.addActionListener(this::employeePylPylBtnActionPerformed);

        employeePylPrlDisputeBtn.setBackground(new java.awt.Color(30, 42, 56));
        employeePylPrlDisputeBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        employeePylPrlDisputeBtn.setForeground(new java.awt.Color(255, 255, 255));
        employeePylPrlDisputeBtn.setText("Payroll Dispute");
        employeePylPrlDisputeBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        employeePylPrlDisputeBtn.addActionListener(this::employeePylPrlDisputeBtnActionPerformed);

        javax.swing.GroupLayout employeePylSidebarPnlLayout = new javax.swing.GroupLayout(employeePylSidebarPnl);
        employeePylSidebarPnl.setLayout(employeePylSidebarPnlLayout);
        employeePylSidebarPnlLayout.setHorizontalGroup(
            employeePylSidebarPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeePylSidebarPnlLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(employeePylMainDashboardBtn))
            .addGroup(employeePylSidebarPnlLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(employeePylSidebarPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(employeePylPrlDisputeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeePylPylRecordBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(employeePylSidebarPnlLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(employeePylMotorPHIconImgLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(employeePylPylBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        employeePylSidebarPnlLayout.setVerticalGroup(
            employeePylSidebarPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeePylSidebarPnlLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(employeePylSidebarPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(employeePylMotorPHIconImgLbl)
                    .addGroup(employeePylSidebarPnlLayout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(employeePylPylBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addComponent(employeePylPylRecordBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(employeePylPrlDisputeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(307, 307, 307)
                .addComponent(employeePylMainDashboardBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        employeePylPylRecordBtn.getAccessibleContext().setAccessibleName("employeePylPylRecordBtn");
        employeePylMainDashboardBtn.getAccessibleContext().setAccessibleName("employeePylMainDashboardBtn");
        employeePylMotorPHIconImgLbl.getAccessibleContext().setAccessibleName("employeePylMotorPHIconImgLbl");
        employeePylPylBtn.getAccessibleContext().setAccessibleName("employeePylPylBtn");
        employeePylPrlDisputeBtn.getAccessibleContext().setAccessibleName("employeePylPrlDisputeBtn");

        employeePylPrlDateFld.setForeground(new java.awt.Color(31, 41, 55));
        employeePylPrlDateFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        employeePylPrlDateFld.setCaretColor(new java.awt.Color(31, 41, 55));
        employeePylPrlDateFld.setDisabledTextColor(new java.awt.Color(31, 41, 55));
        employeePylPrlDateFld.setEnabled(false);
        employeePylPrlDateFld.addActionListener(this::employeePylPrlDateFldActionPerformed);

        employeePylPrlPeriodLbl.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        employeePylPrlPeriodLbl.setForeground(new java.awt.Color(31, 41, 55));
        employeePylPrlPeriodLbl.setText("Payroll Period");

        employeePylENameFld.setForeground(new java.awt.Color(31, 41, 55));
        employeePylENameFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        employeePylENameFld.setCaretColor(new java.awt.Color(31, 41, 55));
        employeePylENameFld.setDisabledTextColor(new java.awt.Color(31, 41, 55));
        employeePylENameFld.setEnabled(false);
        employeePylENameFld.addActionListener(this::employeePylENameFldActionPerformed);

        employeePylENameLbl.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        employeePylENameLbl.setForeground(new java.awt.Color(31, 41, 55));
        employeePylENameLbl.setText("Employee Name");

        employeePylENumberLbl.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        employeePylENumberLbl.setForeground(new java.awt.Color(31, 41, 55));
        employeePylENumberLbl.setText("Employee #");

        employeePylCalculatorBrdrPnl.setBackground(new java.awt.Color(146, 192, 253));
        employeePylCalculatorBrdrPnl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        employeePylCalculatorBrdrPnl.setForeground(new java.awt.Color(146, 192, 253));
        employeePylCalculatorBrdrPnl.setPreferredSize(new java.awt.Dimension(710, 408));

        employeePylCalculatorLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        employeePylCalculatorLbl.setForeground(new java.awt.Color(31, 41, 55));
        employeePylCalculatorLbl.setText("Salary Calculator");

        employeePylTGrossBrdrPnl.setBackground(new java.awt.Color(233, 233, 233));
        employeePylTGrossBrdrPnl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        employeePylTGrossBrdrPnl.setForeground(new java.awt.Color(30, 58, 138));

        employeePylEarningLbl.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        employeePylEarningLbl.setForeground(new java.awt.Color(31, 41, 55));
        employeePylEarningLbl.setText("Earning");

        employeePylBasicSalaryLbl.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        employeePylBasicSalaryLbl.setForeground(new java.awt.Color(31, 41, 55));
        employeePylBasicSalaryLbl.setText("Basic Salary");

        employeePylOvertimeLbl.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        employeePylOvertimeLbl.setForeground(new java.awt.Color(31, 41, 55));
        employeePylOvertimeLbl.setText("Overtime");

        employeePylHolidayLbl.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        employeePylHolidayLbl.setForeground(new java.awt.Color(31, 41, 55));
        employeePylHolidayLbl.setText("Holiday");

        employeePylBenefitLbl.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        employeePylBenefitLbl.setForeground(new java.awt.Color(31, 41, 55));
        employeePylBenefitLbl.setText("Benefit");

        employeePylRiceSubsidyLbl.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        employeePylRiceSubsidyLbl.setForeground(new java.awt.Color(31, 41, 55));
        employeePylRiceSubsidyLbl.setText("Rice Subsidy");

        employeePylPhnAllowanceLbl.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        employeePylPhnAllowanceLbl.setForeground(new java.awt.Color(31, 41, 55));
        employeePylPhnAllowanceLbl.setText("Phone Allowance");

        employeePylCltAllowanceLbl.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        employeePylCltAllowanceLbl.setForeground(new java.awt.Color(31, 41, 55));
        employeePylCltAllowanceLbl.setText("Clothing Allowance");

        employeePylBonusLbl.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        employeePylBonusLbl.setForeground(new java.awt.Color(31, 41, 55));
        employeePylBonusLbl.setText("Bonus");

        employeePylBonusTypeCbx.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        employeePylBonusTypeCbx.setForeground(new java.awt.Color(31, 41, 55));
        employeePylBonusTypeCbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bonus Type", "13th Month", "Christmas", "Performance" }));
        employeePylBonusTypeCbx.addActionListener(this::employeePylBonusTypeCbxActionPerformed);

        employeePylBasicSalaryFld.setForeground(new java.awt.Color(31, 41, 55));
        employeePylBasicSalaryFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        employeePylBasicSalaryFld.setCaretColor(new java.awt.Color(31, 41, 55));
        employeePylBasicSalaryFld.setDisabledTextColor(new java.awt.Color(31, 41, 55));
        employeePylBasicSalaryFld.setEnabled(false);
        employeePylBasicSalaryFld.addActionListener(this::employeePylBasicSalaryFldActionPerformed);

        employeePylOvertimeFld.setForeground(new java.awt.Color(31, 41, 55));
        employeePylOvertimeFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        employeePylOvertimeFld.setCaretColor(new java.awt.Color(31, 41, 55));
        employeePylOvertimeFld.setDisabledTextColor(new java.awt.Color(31, 41, 55));
        employeePylOvertimeFld.setEnabled(false);
        employeePylOvertimeFld.addActionListener(this::employeePylOvertimeFldActionPerformed);

        employeePylHolidayFld.setForeground(new java.awt.Color(31, 41, 55));
        employeePylHolidayFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        employeePylHolidayFld.setCaretColor(new java.awt.Color(31, 41, 55));
        employeePylHolidayFld.setDisabledTextColor(new java.awt.Color(31, 41, 55));
        employeePylHolidayFld.setEnabled(false);
        employeePylHolidayFld.addActionListener(this::employeePylHolidayFldActionPerformed);

        employeePylRiceSubsidyFld.setForeground(new java.awt.Color(31, 41, 55));
        employeePylRiceSubsidyFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        employeePylRiceSubsidyFld.setCaretColor(new java.awt.Color(31, 41, 55));
        employeePylRiceSubsidyFld.setDisabledTextColor(new java.awt.Color(31, 41, 55));
        employeePylRiceSubsidyFld.setEnabled(false);
        employeePylRiceSubsidyFld.addActionListener(this::employeePylRiceSubsidyFldActionPerformed);

        employeePylPhnAllowanceFld.setForeground(new java.awt.Color(31, 41, 55));
        employeePylPhnAllowanceFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        employeePylPhnAllowanceFld.setCaretColor(new java.awt.Color(31, 41, 55));
        employeePylPhnAllowanceFld.setDisabledTextColor(new java.awt.Color(31, 41, 55));
        employeePylPhnAllowanceFld.setEnabled(false);
        employeePylPhnAllowanceFld.addActionListener(this::employeePylPhnAllowanceFldActionPerformed);

        employeePylCltAllowanceFld.setForeground(new java.awt.Color(31, 41, 55));
        employeePylCltAllowanceFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        employeePylCltAllowanceFld.setCaretColor(new java.awt.Color(31, 41, 55));
        employeePylCltAllowanceFld.setDisabledTextColor(new java.awt.Color(31, 41, 55));
        employeePylCltAllowanceFld.setEnabled(false);
        employeePylCltAllowanceFld.addActionListener(this::employeePylCltAllowanceFldActionPerformed);

        employeePylBonusTypeFld.setForeground(new java.awt.Color(31, 41, 55));
        employeePylBonusTypeFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        employeePylBonusTypeFld.setCaretColor(new java.awt.Color(31, 41, 55));
        employeePylBonusTypeFld.setDisabledTextColor(new java.awt.Color(31, 41, 55));
        employeePylBonusTypeFld.setEnabled(false);
        employeePylBonusTypeFld.addActionListener(this::employeePylBonusTypeFldActionPerformed);

        employeePylTGrossFld.setForeground(new java.awt.Color(31, 41, 55));
        employeePylTGrossFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        employeePylTGrossFld.setCaretColor(new java.awt.Color(31, 41, 55));
        employeePylTGrossFld.setDisabledTextColor(new java.awt.Color(31, 41, 55));
        employeePylTGrossFld.setEnabled(false);
        employeePylTGrossFld.addActionListener(this::employeePylTGrossFldActionPerformed);

        employeePylTGrossLbl.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        employeePylTGrossLbl.setForeground(new java.awt.Color(31, 41, 55));
        employeePylTGrossLbl.setText("Total Gross");

        javax.swing.GroupLayout employeePylTGrossBrdrPnlLayout = new javax.swing.GroupLayout(employeePylTGrossBrdrPnl);
        employeePylTGrossBrdrPnl.setLayout(employeePylTGrossBrdrPnlLayout);
        employeePylTGrossBrdrPnlLayout.setHorizontalGroup(
            employeePylTGrossBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, employeePylTGrossBrdrPnlLayout.createSequentialGroup()
                .addGroup(employeePylTGrossBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, employeePylTGrossBrdrPnlLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(employeePylTGrossBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(employeePylTGrossBrdrPnlLayout.createSequentialGroup()
                                .addComponent(employeePylOvertimeLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(employeePylOvertimeFld, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(employeePylTGrossBrdrPnlLayout.createSequentialGroup()
                                .addComponent(employeePylBasicSalaryLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(employeePylBasicSalaryFld, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(employeePylTGrossBrdrPnlLayout.createSequentialGroup()
                                .addComponent(employeePylHolidayLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(employeePylHolidayFld, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(employeePylTGrossBrdrPnlLayout.createSequentialGroup()
                                .addComponent(employeePylRiceSubsidyLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(employeePylRiceSubsidyFld, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(employeePylTGrossBrdrPnlLayout.createSequentialGroup()
                                .addComponent(employeePylPhnAllowanceLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(employeePylPhnAllowanceFld, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(employeePylTGrossBrdrPnlLayout.createSequentialGroup()
                                .addComponent(employeePylCltAllowanceLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                                .addComponent(employeePylCltAllowanceFld, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(employeePylTGrossBrdrPnlLayout.createSequentialGroup()
                                .addGroup(employeePylTGrossBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(employeePylTGrossBrdrPnlLayout.createSequentialGroup()
                                        .addComponent(employeePylBonusTypeCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, employeePylTGrossBrdrPnlLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(employeePylTGrossLbl)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(employeePylTGrossBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(employeePylBonusTypeFld, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(employeePylTGrossFld, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, employeePylTGrossBrdrPnlLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addGroup(employeePylTGrossBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(employeePylBenefitLbl)
                            .addComponent(employeePylEarningLbl)
                            .addGroup(employeePylTGrossBrdrPnlLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(employeePylBonusLbl)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(26, 26, 26))
        );
        employeePylTGrossBrdrPnlLayout.setVerticalGroup(
            employeePylTGrossBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeePylTGrossBrdrPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(employeePylEarningLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(employeePylTGrossBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employeePylBasicSalaryLbl)
                    .addComponent(employeePylBasicSalaryFld, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(employeePylTGrossBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employeePylOvertimeLbl)
                    .addComponent(employeePylOvertimeFld, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(employeePylTGrossBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employeePylHolidayLbl)
                    .addComponent(employeePylHolidayFld, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(employeePylBenefitLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(employeePylTGrossBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employeePylRiceSubsidyLbl)
                    .addComponent(employeePylRiceSubsidyFld, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(employeePylTGrossBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employeePylPhnAllowanceLbl)
                    .addComponent(employeePylPhnAllowanceFld, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(employeePylTGrossBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employeePylCltAllowanceLbl)
                    .addComponent(employeePylCltAllowanceFld, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(employeePylBonusLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(employeePylTGrossBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employeePylBonusTypeCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeePylBonusTypeFld, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(employeePylTGrossBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employeePylTGrossFld, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeePylTGrossLbl))
                .addGap(8, 8, 8))
        );

        employeePylEarningLbl.getAccessibleContext().setAccessibleName("employeePylEarningLbl");
        employeePylBasicSalaryLbl.getAccessibleContext().setAccessibleName("employeePylBasicSalaryLbl");
        employeePylOvertimeLbl.getAccessibleContext().setAccessibleName("employeePylOvertimeLbl");
        employeePylHolidayLbl.getAccessibleContext().setAccessibleName("employeePylHolidayLbl");
        employeePylBenefitLbl.getAccessibleContext().setAccessibleName("employeePylBenefitLbl");
        employeePylRiceSubsidyLbl.getAccessibleContext().setAccessibleName("employeePylRiceSubsidyLbl");
        employeePylPhnAllowanceLbl.getAccessibleContext().setAccessibleName("employeePylPhnAllowanceLbl");
        employeePylCltAllowanceLbl.getAccessibleContext().setAccessibleName("employeePylCltAllowanceLbl");
        employeePylBonusLbl.getAccessibleContext().setAccessibleName("employeePylBonusLbl");
        employeePylBonusTypeCbx.getAccessibleContext().setAccessibleName("employeePylBonusTypeCbx");
        employeePylBasicSalaryFld.getAccessibleContext().setAccessibleName("employeePylBasicSalaryFld");
        employeePylOvertimeFld.getAccessibleContext().setAccessibleName("employeePylOvertimeFld");
        employeePylHolidayFld.getAccessibleContext().setAccessibleName("employeePylHolidayFld");
        employeePylRiceSubsidyFld.getAccessibleContext().setAccessibleName("employeePylRiceSubsidyFld");
        employeePylPhnAllowanceFld.getAccessibleContext().setAccessibleName("employeePylPhnAllowanceFld");
        employeePylCltAllowanceFld.getAccessibleContext().setAccessibleName("employeePylCltAllowanceFld");
        employeePylBonusTypeFld.getAccessibleContext().setAccessibleName("employeePylBonusTypeFld");
        employeePylTGrossFld.getAccessibleContext().setAccessibleName("employeePylTGrossFld");
        employeePylTGrossLbl.getAccessibleContext().setAccessibleName("employeePylTGrossLbl");

        employeePylTDeductionBrdrPnl.setBackground(new java.awt.Color(233, 233, 233));
        employeePylTDeductionBrdrPnl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        employeePylTDeductionBrdrPnl.setForeground(new java.awt.Color(30, 58, 138));

        employeePylDeductionLbl.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        employeePylDeductionLbl.setForeground(new java.awt.Color(31, 41, 55));
        employeePylDeductionLbl.setText("Deduction");

        employeePylSSSLbl.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        employeePylSSSLbl.setForeground(new java.awt.Color(31, 41, 55));
        employeePylSSSLbl.setText("SSS");

        employeePylTINLbl.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        employeePylTINLbl.setForeground(new java.awt.Color(31, 41, 55));
        employeePylTINLbl.setText("Tax");

        employeePylPhilHealthLbl.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        employeePylPhilHealthLbl.setForeground(new java.awt.Color(31, 41, 55));
        employeePylPhilHealthLbl.setText("PhilHealth");

        employeePylPagIbigLbl.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        employeePylPagIbigLbl.setForeground(new java.awt.Color(31, 41, 55));
        employeePylPagIbigLbl.setText("Pag-Ibig");

        employeePylLateLbl.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        employeePylLateLbl.setForeground(new java.awt.Color(31, 41, 55));
        employeePylLateLbl.setText("Late");

        employeePylUndertimeLbl.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        employeePylUndertimeLbl.setForeground(new java.awt.Color(31, 41, 55));
        employeePylUndertimeLbl.setText("Undertime");

        employeePylSSSFld.setForeground(new java.awt.Color(31, 41, 55));
        employeePylSSSFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        employeePylSSSFld.setCaretColor(new java.awt.Color(31, 41, 55));
        employeePylSSSFld.setDisabledTextColor(new java.awt.Color(31, 41, 55));
        employeePylSSSFld.setEnabled(false);
        employeePylSSSFld.addActionListener(this::employeePylSSSFldActionPerformed);

        employeePylTINFld.setForeground(new java.awt.Color(31, 41, 55));
        employeePylTINFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        employeePylTINFld.setCaretColor(new java.awt.Color(31, 41, 55));
        employeePylTINFld.setDisabledTextColor(new java.awt.Color(31, 41, 55));
        employeePylTINFld.setEnabled(false);
        employeePylTINFld.addActionListener(this::employeePylTINFldActionPerformed);

        employeePylPhilHealthFld.setForeground(new java.awt.Color(31, 41, 55));
        employeePylPhilHealthFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        employeePylPhilHealthFld.setCaretColor(new java.awt.Color(31, 41, 55));
        employeePylPhilHealthFld.setDisabledTextColor(new java.awt.Color(31, 41, 55));
        employeePylPhilHealthFld.setEnabled(false);
        employeePylPhilHealthFld.addActionListener(this::employeePylPhilHealthFldActionPerformed);

        employeePylPagIbigFld.setForeground(new java.awt.Color(31, 41, 55));
        employeePylPagIbigFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        employeePylPagIbigFld.setCaretColor(new java.awt.Color(31, 41, 55));
        employeePylPagIbigFld.setDisabledTextColor(new java.awt.Color(31, 41, 55));
        employeePylPagIbigFld.setEnabled(false);
        employeePylPagIbigFld.addActionListener(this::employeePylPagIbigFldActionPerformed);

        employeePylLateFld.setForeground(new java.awt.Color(31, 41, 55));
        employeePylLateFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        employeePylLateFld.setCaretColor(new java.awt.Color(31, 41, 55));
        employeePylLateFld.setDisabledTextColor(new java.awt.Color(31, 41, 55));
        employeePylLateFld.setEnabled(false);
        employeePylLateFld.addActionListener(this::employeePylLateFldActionPerformed);

        employeePylUndertimeFld.setForeground(new java.awt.Color(31, 41, 55));
        employeePylUndertimeFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        employeePylUndertimeFld.setCaretColor(new java.awt.Color(31, 41, 55));
        employeePylUndertimeFld.setDisabledTextColor(new java.awt.Color(31, 41, 55));
        employeePylUndertimeFld.setEnabled(false);
        employeePylUndertimeFld.addActionListener(this::employeePylUndertimeFldActionPerformed);

        employeePylAbsentLbl.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        employeePylAbsentLbl.setForeground(new java.awt.Color(31, 41, 55));
        employeePylAbsentLbl.setText("Absent");

        employeePylAbsentFld.setForeground(new java.awt.Color(31, 41, 55));
        employeePylAbsentFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        employeePylAbsentFld.setCaretColor(new java.awt.Color(31, 41, 55));
        employeePylAbsentFld.setDisabledTextColor(new java.awt.Color(31, 41, 55));
        employeePylAbsentFld.setEnabled(false);
        employeePylAbsentFld.addActionListener(this::employeePylAbsentFldActionPerformed);

        employeePylTDeductionFld.setForeground(new java.awt.Color(31, 41, 55));
        employeePylTDeductionFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        employeePylTDeductionFld.setCaretColor(new java.awt.Color(31, 41, 55));
        employeePylTDeductionFld.setDisabledTextColor(new java.awt.Color(31, 41, 55));
        employeePylTDeductionFld.setEnabled(false);
        employeePylTDeductionFld.addActionListener(this::employeePylTDeductionFldActionPerformed);

        employeePylTDeductionLbl.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        employeePylTDeductionLbl.setForeground(new java.awt.Color(31, 41, 55));
        employeePylTDeductionLbl.setText("Total Deduction");

        javax.swing.GroupLayout employeePylTDeductionBrdrPnlLayout = new javax.swing.GroupLayout(employeePylTDeductionBrdrPnl);
        employeePylTDeductionBrdrPnl.setLayout(employeePylTDeductionBrdrPnlLayout);
        employeePylTDeductionBrdrPnlLayout.setHorizontalGroup(
            employeePylTDeductionBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeePylTDeductionBrdrPnlLayout.createSequentialGroup()
                .addGroup(employeePylTDeductionBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(employeePylTDeductionBrdrPnlLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(employeePylDeductionLbl)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(employeePylTDeductionBrdrPnlLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(employeePylTDeductionBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(employeePylTDeductionBrdrPnlLayout.createSequentialGroup()
                                .addComponent(employeePylTINLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(employeePylTINFld, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(employeePylTDeductionBrdrPnlLayout.createSequentialGroup()
                                .addComponent(employeePylSSSLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(employeePylSSSFld, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(employeePylTDeductionBrdrPnlLayout.createSequentialGroup()
                                .addComponent(employeePylPhilHealthLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(employeePylPhilHealthFld, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(employeePylTDeductionBrdrPnlLayout.createSequentialGroup()
                                .addComponent(employeePylPagIbigLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(employeePylPagIbigFld, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(employeePylTDeductionBrdrPnlLayout.createSequentialGroup()
                                .addComponent(employeePylLateLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(employeePylLateFld, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, employeePylTDeductionBrdrPnlLayout.createSequentialGroup()
                                .addGroup(employeePylTDeductionBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(employeePylUndertimeLbl)
                                    .addComponent(employeePylAbsentLbl))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                                .addGroup(employeePylTDeductionBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(employeePylUndertimeFld, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(employeePylAbsentFld, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, employeePylTDeductionBrdrPnlLayout.createSequentialGroup()
                        .addContainerGap(74, Short.MAX_VALUE)
                        .addComponent(employeePylTDeductionLbl)
                        .addGap(18, 18, 18)
                        .addComponent(employeePylTDeductionFld, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        employeePylTDeductionBrdrPnlLayout.setVerticalGroup(
            employeePylTDeductionBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, employeePylTDeductionBrdrPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(employeePylTDeductionBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(employeePylTDeductionBrdrPnlLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(employeePylTDeductionBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(employeePylTDeductionFld, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(employeePylTDeductionLbl)))
                    .addGroup(employeePylTDeductionBrdrPnlLayout.createSequentialGroup()
                        .addComponent(employeePylDeductionLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(employeePylTDeductionBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(employeePylSSSLbl)
                            .addComponent(employeePylSSSFld, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(employeePylTDeductionBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(employeePylTINLbl)
                            .addComponent(employeePylTINFld, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(employeePylTDeductionBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(employeePylPhilHealthLbl)
                            .addComponent(employeePylPhilHealthFld, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(employeePylTDeductionBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(employeePylPagIbigLbl)
                            .addComponent(employeePylPagIbigFld, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(employeePylTDeductionBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(employeePylLateLbl)
                            .addComponent(employeePylLateFld, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(employeePylTDeductionBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(employeePylUndertimeLbl)
                            .addComponent(employeePylUndertimeFld, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(employeePylTDeductionBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(employeePylAbsentLbl)
                            .addComponent(employeePylAbsentFld, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 59, Short.MAX_VALUE)))
                .addContainerGap())
        );

        employeePylDeductionLbl.getAccessibleContext().setAccessibleName("employeePylDeductionLbl");
        employeePylSSSLbl.getAccessibleContext().setAccessibleName("employeePylSSSLbl");
        employeePylTINLbl.getAccessibleContext().setAccessibleName("employeePylTINLbl");
        employeePylPhilHealthLbl.getAccessibleContext().setAccessibleName("employeePylPhilHealthLbl");
        employeePylPagIbigLbl.getAccessibleContext().setAccessibleName("employeePylPagIbigLbl");
        employeePylLateLbl.getAccessibleContext().setAccessibleName("employeePylLateLbl");
        employeePylUndertimeLbl.getAccessibleContext().setAccessibleName("employeePylUndertimeLbl");
        employeePylSSSFld.getAccessibleContext().setAccessibleName("employeePylSSSFld");
        employeePylTINFld.getAccessibleContext().setAccessibleName("employeePylTINFld");
        employeePylPhilHealthFld.getAccessibleContext().setAccessibleName("employeePylPhilHealthFld");
        employeePylPagIbigFld.getAccessibleContext().setAccessibleName("employeePylPagIbigFld");
        employeePylLateFld.getAccessibleContext().setAccessibleName("employeePylLateFld");
        employeePylUndertimeFld.getAccessibleContext().setAccessibleName("employeePylUndertimeFld");
        employeePylAbsentLbl.getAccessibleContext().setAccessibleName("employeePylAbsentLbl");
        employeePylAbsentFld.getAccessibleContext().setAccessibleName("employeePylAbsentFld");
        employeePylTDeductionFld.getAccessibleContext().setAccessibleName("employeePylTDeductionFld");
        employeePylTDeductionLbl.getAccessibleContext().setAccessibleName("employeePylTDeductionLbl");

        employeePylNetPayLbl.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        employeePylNetPayLbl.setForeground(new java.awt.Color(31, 41, 55));
        employeePylNetPayLbl.setText("Net Pay");

        employeePylNetPayFld.setBackground(new java.awt.Color(34, 197, 94));
        employeePylNetPayFld.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        employeePylNetPayFld.setForeground(new java.awt.Color(255, 255, 255));
        employeePylNetPayFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        employeePylNetPayFld.setCaretColor(new java.awt.Color(255, 255, 255));
        employeePylNetPayFld.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        employeePylNetPayFld.setEnabled(false);
        employeePylNetPayFld.addActionListener(this::employeePylNetPayFldActionPerformed);

        javax.swing.GroupLayout employeePylCalculatorBrdrPnlLayout = new javax.swing.GroupLayout(employeePylCalculatorBrdrPnl);
        employeePylCalculatorBrdrPnl.setLayout(employeePylCalculatorBrdrPnlLayout);
        employeePylCalculatorBrdrPnlLayout.setHorizontalGroup(
            employeePylCalculatorBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeePylCalculatorBrdrPnlLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(employeePylTGrossBrdrPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(employeePylCalculatorBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(employeePylCalculatorBrdrPnlLayout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(employeePylNetPayLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(employeePylNetPayFld, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(employeePylTDeductionBrdrPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, employeePylCalculatorBrdrPnlLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(employeePylCalculatorLbl)
                .addGap(283, 283, 283))
        );
        employeePylCalculatorBrdrPnlLayout.setVerticalGroup(
            employeePylCalculatorBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeePylCalculatorBrdrPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(employeePylCalculatorLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(employeePylCalculatorBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(employeePylTGrossBrdrPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(employeePylCalculatorBrdrPnlLayout.createSequentialGroup()
                        .addComponent(employeePylTDeductionBrdrPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(employeePylCalculatorBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(employeePylNetPayLbl)
                            .addComponent(employeePylNetPayFld, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        employeePylCalculatorLbl.getAccessibleContext().setAccessibleName("employeePylCalculatorLbl");
        employeePylTGrossBrdrPnl.getAccessibleContext().setAccessibleName("employeePylTGrossBrdrPnl");
        employeePylTDeductionBrdrPnl.getAccessibleContext().setAccessibleName("employeePylTDeductionBrdrPnl");
        employeePylNetPayLbl.getAccessibleContext().setAccessibleName("employeePylNetPayLbl");
        employeePylNetPayFld.getAccessibleContext().setAccessibleName("employeePylNetPayFld");

        employeePylPrlDateLbl.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        employeePylPrlDateLbl.setForeground(new java.awt.Color(31, 41, 55));
        employeePylPrlDateLbl.setText("Payroll Date");

        employeePylPDFBtn.setBackground(new java.awt.Color(30, 58, 138));
        employeePylPDFBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        employeePylPDFBtn.setForeground(new java.awt.Color(255, 255, 255));
        employeePylPDFBtn.setText("Export to PDF");
        employeePylPDFBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        employeePylPDFBtn.addActionListener(this::employeePylPDFBtnActionPerformed);

        employeePylENumberFld.setForeground(new java.awt.Color(31, 41, 55));
        employeePylENumberFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        employeePylENumberFld.setCaretColor(new java.awt.Color(31, 41, 55));
        employeePylENumberFld.setDisabledTextColor(new java.awt.Color(31, 41, 55));
        employeePylENumberFld.setEnabled(false);
        employeePylENumberFld.addActionListener(this::employeePylENumberFldActionPerformed);

        employeePylEPylPnl.setBackground(new java.awt.Color(30, 58, 138));
        employeePylEPylPnl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        employeePylEPylPnl.setForeground(new java.awt.Color(30, 58, 138));
        employeePylEPylPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        employeePylEPylLbl.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        employeePylEPylLbl.setForeground(new java.awt.Color(255, 255, 255));
        employeePylEPylLbl.setText(" Employee Payslip ");
        employeePylEPylPnl.add(employeePylEPylLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 1, 230, 46));
        employeePylEPylLbl.getAccessibleContext().setAccessibleName("employeePylEPylLbl");

        employeePylPrlPeriodFld.setForeground(new java.awt.Color(31, 41, 55));
        employeePylPrlPeriodFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        employeePylPrlPeriodFld.setCaretColor(new java.awt.Color(31, 41, 55));
        employeePylPrlPeriodFld.setDisabledTextColor(new java.awt.Color(31, 41, 55));
        employeePylPrlPeriodFld.setEnabled(false);
        employeePylPrlPeriodFld.addActionListener(this::employeePylPrlPeriodFldActionPerformed);

        employeePylSearchPnl.setBackground(new java.awt.Color(146, 192, 253));
        employeePylSearchPnl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        employeePylSearchPnl.setForeground(new java.awt.Color(146, 192, 253));
        employeePylSearchPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        employeePylEntENumberFld.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        employeePylEntENumberFld.setForeground(new java.awt.Color(31, 41, 55));
        employeePylEntENumberFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        employeePylEntENumberFld.setCaretColor(new java.awt.Color(31, 41, 55));
        employeePylEntENumberFld.setDisabledTextColor(new java.awt.Color(31, 41, 55));
        employeePylEntENumberFld.addActionListener(this::employeePylEntENumberFldActionPerformed);
        employeePylSearchPnl.add(employeePylEntENumberFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 7, 170, 31));
        employeePylEntENumberFld.getAccessibleContext().setAccessibleName("employeePylEntENumberFld");

        employeePylSearchIconImgLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/motorph/img/SearchIconImg.png"))); // NOI18N
        employeePylSearchPnl.add(employeePylSearchIconImgLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, -10, 60, 60));
        employeePylSearchIconImgLbl.getAccessibleContext().setAccessibleName("employeePylSearchIconImgLbl");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(employeePylSidebarPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(employeePylEPylPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(employeePylSearchPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(employeePylENameLbl)
                                        .addGap(29, 29, 29)
                                        .addComponent(employeePylENameFld, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(42, 42, 42)
                                        .addComponent(employeePylPrlDateLbl)
                                        .addGap(39, 39, 39)
                                        .addComponent(employeePylPrlDateFld, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(employeePylENumberLbl)
                                        .addGap(60, 60, 60)
                                        .addComponent(employeePylENumberFld, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(42, 42, 42)
                                        .addComponent(employeePylPrlPeriodLbl)
                                        .addGap(28, 28, 28)
                                        .addComponent(employeePylPrlPeriodFld, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(employeePylCalculatorBrdrPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 709, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(17, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(employeePylPDFBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(291, 291, 291))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(employeePylEPylPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeePylSearchPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(employeePylENameFld, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeePylPrlDateFld, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(employeePylENameLbl)
                            .addComponent(employeePylPrlDateLbl))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(employeePylPrlPeriodFld, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(employeePylENumberLbl)
                                    .addComponent(employeePylPrlPeriodLbl)))))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(employeePylENumberFld, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(employeePylCalculatorBrdrPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(employeePylPDFBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(employeePylSidebarPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        employeePylSidebarPnl.getAccessibleContext().setAccessibleName("employeePylSidebarPnl");
        employeePylPrlDateFld.getAccessibleContext().setAccessibleName("employeePylPrlDateFld");
        employeePylPrlPeriodLbl.getAccessibleContext().setAccessibleName("employeePylPrlPeriodLbl");
        employeePylENameFld.getAccessibleContext().setAccessibleName("employeePylENameFld");
        employeePylENameLbl.getAccessibleContext().setAccessibleName("employeePylENameLbl");
        employeePylENumberLbl.getAccessibleContext().setAccessibleName("employeePylENumberLbl");
        employeePylCalculatorBrdrPnl.getAccessibleContext().setAccessibleName("employeePylCalculatorBrdrPnl");
        employeePylPrlDateLbl.getAccessibleContext().setAccessibleName("employeePylPrlDateLbl");
        employeePylPDFBtn.getAccessibleContext().setAccessibleName("employeePylPDFBtn");
        employeePylENumberFld.getAccessibleContext().setAccessibleName("employeePylENumberFld");
        employeePylEPylPnl.getAccessibleContext().setAccessibleName("employeePylEPylPnl");
        employeePylPrlPeriodFld.getAccessibleContext().setAccessibleName("employeePylPrlPeriodFld");
        employeePylSearchPnl.getAccessibleContext().setAccessibleName("employeePylSearchPnl");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void employeePylPylRecordBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeePylPylRecordBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
        new EmployeePayslipRecordUI().setVisible(true);
                
                
    }//GEN-LAST:event_employeePylPylRecordBtnActionPerformed

    private void employeePylMainDashboardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeePylMainDashboardBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new MainDashboardUI().setVisible(true);
    }//GEN-LAST:event_employeePylMainDashboardBtnActionPerformed

    private void employeePylPrlDateFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeePylPrlDateFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeePylPrlDateFldActionPerformed

    private void employeePylENameFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeePylENameFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeePylENameFldActionPerformed

    private void employeePylBonusTypeCbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeePylBonusTypeCbxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeePylBonusTypeCbxActionPerformed

    private void employeePylBasicSalaryFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeePylBasicSalaryFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeePylBasicSalaryFldActionPerformed

    private void employeePylOvertimeFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeePylOvertimeFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeePylOvertimeFldActionPerformed

    private void employeePylHolidayFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeePylHolidayFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeePylHolidayFldActionPerformed

    private void employeePylRiceSubsidyFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeePylRiceSubsidyFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeePylRiceSubsidyFldActionPerformed

    private void employeePylPhnAllowanceFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeePylPhnAllowanceFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeePylPhnAllowanceFldActionPerformed

    private void employeePylCltAllowanceFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeePylCltAllowanceFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeePylCltAllowanceFldActionPerformed

    private void employeePylBonusTypeFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeePylBonusTypeFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeePylBonusTypeFldActionPerformed

    private void employeePylTGrossFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeePylTGrossFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeePylTGrossFldActionPerformed

    private void employeePylSSSFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeePylSSSFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeePylSSSFldActionPerformed

    private void employeePylTINFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeePylTINFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeePylTINFldActionPerformed

    private void employeePylPhilHealthFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeePylPhilHealthFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeePylPhilHealthFldActionPerformed

    private void employeePylPagIbigFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeePylPagIbigFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeePylPagIbigFldActionPerformed

    private void employeePylLateFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeePylLateFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeePylLateFldActionPerformed

    private void employeePylUndertimeFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeePylUndertimeFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeePylUndertimeFldActionPerformed

    private void employeePylAbsentFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeePylAbsentFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeePylAbsentFldActionPerformed

    private void employeePylTDeductionFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeePylTDeductionFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeePylTDeductionFldActionPerformed

    private void employeePylNetPayFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeePylNetPayFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeePylNetPayFldActionPerformed

    private void employeePylPDFBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeePylPDFBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeePylPDFBtnActionPerformed

    private void employeePylENumberFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeePylENumberFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeePylENumberFldActionPerformed

    private void employeePylPrlPeriodFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeePylPrlPeriodFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeePylPrlPeriodFldActionPerformed

    private void employeePylPylBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeePylPylBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeePylPylBtnActionPerformed

    private void employeePylPrlDisputeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeePylPrlDisputeBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
        new EmployeePayrollDisputeUI().setVisible(true);
    }//GEN-LAST:event_employeePylPrlDisputeBtnActionPerformed

    private void employeePylEntENumberFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeePylEntENumberFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeePylEntENumberFldActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField employeePylAbsentFld;
    private javax.swing.JLabel employeePylAbsentLbl;
    private javax.swing.JTextField employeePylBasicSalaryFld;
    private javax.swing.JLabel employeePylBasicSalaryLbl;
    private javax.swing.JLabel employeePylBenefitLbl;
    private javax.swing.JLabel employeePylBonusLbl;
    private javax.swing.JComboBox<String> employeePylBonusTypeCbx;
    private javax.swing.JTextField employeePylBonusTypeFld;
    private javax.swing.JPanel employeePylCalculatorBrdrPnl;
    private javax.swing.JLabel employeePylCalculatorLbl;
    private javax.swing.JTextField employeePylCltAllowanceFld;
    private javax.swing.JLabel employeePylCltAllowanceLbl;
    private javax.swing.JLabel employeePylDeductionLbl;
    private javax.swing.JTextField employeePylENameFld;
    private javax.swing.JLabel employeePylENameLbl;
    private javax.swing.JTextField employeePylENumberFld;
    private javax.swing.JLabel employeePylENumberLbl;
    private javax.swing.JLabel employeePylEPylLbl;
    private javax.swing.JPanel employeePylEPylPnl;
    private javax.swing.JLabel employeePylEarningLbl;
    private javax.swing.JTextField employeePylEntENumberFld;
    private javax.swing.JTextField employeePylHolidayFld;
    private javax.swing.JLabel employeePylHolidayLbl;
    private javax.swing.JTextField employeePylLateFld;
    private javax.swing.JLabel employeePylLateLbl;
    private javax.swing.JButton employeePylMainDashboardBtn;
    private javax.swing.JLabel employeePylMotorPHIconImgLbl;
    private javax.swing.JTextField employeePylNetPayFld;
    private javax.swing.JLabel employeePylNetPayLbl;
    private javax.swing.JTextField employeePylOvertimeFld;
    private javax.swing.JLabel employeePylOvertimeLbl;
    private javax.swing.JButton employeePylPDFBtn;
    private javax.swing.JTextField employeePylPagIbigFld;
    private javax.swing.JLabel employeePylPagIbigLbl;
    private javax.swing.JTextField employeePylPhilHealthFld;
    private javax.swing.JLabel employeePylPhilHealthLbl;
    private javax.swing.JTextField employeePylPhnAllowanceFld;
    private javax.swing.JLabel employeePylPhnAllowanceLbl;
    private javax.swing.JTextField employeePylPrlDateFld;
    private javax.swing.JLabel employeePylPrlDateLbl;
    private javax.swing.JButton employeePylPrlDisputeBtn;
    private javax.swing.JTextField employeePylPrlPeriodFld;
    private javax.swing.JLabel employeePylPrlPeriodLbl;
    private javax.swing.JButton employeePylPylBtn;
    private javax.swing.JButton employeePylPylRecordBtn;
    private javax.swing.JTextField employeePylRiceSubsidyFld;
    private javax.swing.JLabel employeePylRiceSubsidyLbl;
    private javax.swing.JTextField employeePylSSSFld;
    private javax.swing.JLabel employeePylSSSLbl;
    private javax.swing.JLabel employeePylSearchIconImgLbl;
    private javax.swing.JPanel employeePylSearchPnl;
    private javax.swing.JPanel employeePylSidebarPnl;
    private javax.swing.JPanel employeePylTDeductionBrdrPnl;
    private javax.swing.JTextField employeePylTDeductionFld;
    private javax.swing.JLabel employeePylTDeductionLbl;
    private javax.swing.JPanel employeePylTGrossBrdrPnl;
    private javax.swing.JTextField employeePylTGrossFld;
    private javax.swing.JLabel employeePylTGrossLbl;
    private javax.swing.JTextField employeePylTINFld;
    private javax.swing.JLabel employeePylTINLbl;
    private javax.swing.JTextField employeePylUndertimeFld;
    private javax.swing.JLabel employeePylUndertimeLbl;
    // End of variables declaration//GEN-END:variables
}
