/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.motorph.ui;

import com.motorph.model.LeaveRequest;
import com.motorph.model.LeaveType;
import com.motorph.model.Role;
import com.motorph.service.LeaveService;
import com.motorph.util.AppContext;
import com.motorph.util.DateUtils;
import com.motorph.util.GuiUtil;
import com.motorph.util.Session;
import java.time.LocalDate;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lenovo
 */
public class EmployeeLeaveUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EmployeeLeaveUI.class.getName());
    private LeaveService leaveService;
    /**
     * Creates new form EmployeeLeaveFrame
     */
    public EmployeeLeaveUI() {
        
        this.leaveService = AppContext.getLeaveService();
        
        initComponents();
        initComboBox();
        hideLeaveListButton();
        
        if (leaveService != null && Session.getCurrentUser() != null) {
            populateLeaveRecords();
        } else {
            logger.warning("Service or Session is null! Cannot populate table.");
        }
    }
    
    private void hideLeaveListButton() {
        Role role = Session.getCurrentUser().getRole();
        if (role != Role.ADMIN && role != Role.HR) {
            employeeLeaveLListBtn.setVisible(false);
        } else {
            employeeLeaveLListBtn.setVisible(true);
        }
    }
    
    // Initializes leave type dropdown
    private void initComboBox() {
        LeaveType[] types = LeaveType.values();
        DefaultComboBoxModel<Object> model = new DefaultComboBoxModel<>();
        model.addElement("Select Leave Type");
        for (LeaveType type : types) {
            model.addElement(type);
        }
        employeeLeaveTTypeCbx.setModel(model);
    }
    
    
    private void populateLeaveRecords() {
        try {
            
            List<LeaveRequest> list = leaveService.getAllLeave(Session.getCurrentUser().getEmployeeNumber());

            // Ensure the table model exists
            DefaultTableModel model = (DefaultTableModel) employeeLeaveRecordsTbl.getModel();
            model.setRowCount(0);

            // 4. Fill the rows
            for (LeaveRequest q : list) {

                Object[] row = {
                    q.getLeaveType() != null ? q.getLeaveType().toString() : "N/A",
                    q.getStartDate(),
                    q.getEndDate(),
                    q.getDateFiled(),
                    q.getStatus()
                };

                model.addRow(row);
            }
        } catch (Exception e) {
            logger.severe("Failed to populate table: " + e.getMessage());
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        employeeLeaveSidebarPnl = new javax.swing.JPanel();
        employeeLeaveLDetailsBtn = new javax.swing.JButton();
        employeeLeaveLListBtn = new javax.swing.JButton();
        employeeLeaveMainDashboardBtn = new javax.swing.JButton();
        employeeLeaveMotorPHIconImgLbl = new javax.swing.JLabel();
        employeeLeaveLRecordsPnl = new javax.swing.JPanel();
        employeeLeaveLRecordsLbl = new javax.swing.JLabel();
        employeeLeaveLFormBrdrPnl = new javax.swing.JPanel();
        employeeLeaveLFormPnl = new javax.swing.JPanel();
        employeeLeaveLFormLbl = new javax.swing.JLabel();
        employeeLeaveFALeaveBrdrPnl = new javax.swing.JPanel();
        employeeLeaveFALeavePnl = new javax.swing.JPanel();
        employeeLeaveFALeaveLbl = new javax.swing.JLabel();
        employeeLeaveReasonLbl = new javax.swing.JLabel();
        employeeLeaveSubmitBtn = new javax.swing.JButton();
        employeeLeaveFromLbl = new javax.swing.JLabel();
        employeeLeaveReasonFld = new javax.swing.JTextField();
        employeeLeaveENameLbl = new javax.swing.JLabel();
        employeeLeaveFromDtChsr = new com.toedter.calendar.JDateChooser();
        employeeLeaveToDtChsr = new com.toedter.calendar.JDateChooser();
        employeeLeaveTTypeCbx = new javax.swing.JComboBox<>();
        employeeLeaveRecordsBrdrPnl = new javax.swing.JPanel();
        employeeLeaveRecordsLbl = new javax.swing.JLabel();
        employeeLeaveRecordsBrdrScrlPnl = new javax.swing.JScrollPane();
        employeeLeaveRecordsTbl = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        employeeLeaveSidebarPnl.setBackground(new java.awt.Color(30, 58, 138));
        employeeLeaveSidebarPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        employeeLeaveLDetailsBtn.setBackground(new java.awt.Color(30, 42, 56));
        employeeLeaveLDetailsBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        employeeLeaveLDetailsBtn.setForeground(new java.awt.Color(255, 255, 255));
        employeeLeaveLDetailsBtn.setText(" Leave Details");
        employeeLeaveLDetailsBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        employeeLeaveLDetailsBtn.addActionListener(this::employeeLeaveLDetailsBtnActionPerformed);
        employeeLeaveSidebarPnl.add(employeeLeaveLDetailsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 199, 216, 39));
        employeeLeaveLDetailsBtn.getAccessibleContext().setAccessibleName("employeeLeaveLDetailsBtn");

        employeeLeaveLListBtn.setBackground(new java.awt.Color(30, 42, 56));
        employeeLeaveLListBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        employeeLeaveLListBtn.setForeground(new java.awt.Color(255, 255, 255));
        employeeLeaveLListBtn.setText("Leave List");
        employeeLeaveLListBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        employeeLeaveLListBtn.addActionListener(this::employeeLeaveLListBtnActionPerformed);
        employeeLeaveSidebarPnl.add(employeeLeaveLListBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 250, 216, 39));
        employeeLeaveLListBtn.getAccessibleContext().setAccessibleName("employeeLeaveLListBtn");

        employeeLeaveMainDashboardBtn.setBackground(new java.awt.Color(30, 42, 56));
        employeeLeaveMainDashboardBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        employeeLeaveMainDashboardBtn.setForeground(new java.awt.Color(255, 255, 255));
        employeeLeaveMainDashboardBtn.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        employeeLeaveMainDashboardBtn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        employeeLeaveMainDashboardBtn.setLabel("Main Dashboard");
        employeeLeaveMainDashboardBtn.addActionListener(this::employeeLeaveMainDashboardBtnActionPerformed);
        employeeLeaveSidebarPnl.add(employeeLeaveMainDashboardBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 647, -1, 39));
        employeeLeaveMainDashboardBtn.getAccessibleContext().setAccessibleName("employeeLeaveMainDashboardBtn");

        employeeLeaveMotorPHIconImgLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/motorph/img/MotorPHIconImg.png"))); // NOI18N
        employeeLeaveSidebarPnl.add(employeeLeaveMotorPHIconImgLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 180, -1));
        employeeLeaveMotorPHIconImgLbl.getAccessibleContext().setAccessibleName("employeeLeaveMotorPHIconImgLbl");

        employeeLeaveLRecordsPnl.setBackground(new java.awt.Color(30, 58, 138));
        employeeLeaveLRecordsPnl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        employeeLeaveLRecordsPnl.setForeground(new java.awt.Color(30, 58, 138));

        employeeLeaveLRecordsLbl.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        employeeLeaveLRecordsLbl.setForeground(new java.awt.Color(255, 255, 255));
        employeeLeaveLRecordsLbl.setText(" Leave Records");

        javax.swing.GroupLayout employeeLeaveLRecordsPnlLayout = new javax.swing.GroupLayout(employeeLeaveLRecordsPnl);
        employeeLeaveLRecordsPnl.setLayout(employeeLeaveLRecordsPnlLayout);
        employeeLeaveLRecordsPnlLayout.setHorizontalGroup(
            employeeLeaveLRecordsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeeLeaveLRecordsPnlLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(employeeLeaveLRecordsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        employeeLeaveLRecordsPnlLayout.setVerticalGroup(
            employeeLeaveLRecordsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(employeeLeaveLRecordsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        employeeLeaveLRecordsLbl.getAccessibleContext().setAccessibleName("employeeLeaveLDetailsLbl");

        employeeLeaveLFormBrdrPnl.setBackground(new java.awt.Color(255, 255, 255));
        employeeLeaveLFormBrdrPnl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 2, true));

        employeeLeaveLFormPnl.setBackground(new java.awt.Color(30, 58, 138));
        employeeLeaveLFormPnl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        employeeLeaveLFormPnl.setForeground(new java.awt.Color(30, 58, 138));
        employeeLeaveLFormPnl.setPreferredSize(new java.awt.Dimension(126, 40));

        employeeLeaveLFormLbl.setBackground(new java.awt.Color(255, 255, 255));
        employeeLeaveLFormLbl.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        employeeLeaveLFormLbl.setForeground(new java.awt.Color(255, 255, 255));
        employeeLeaveLFormLbl.setText("Leave Form");
        employeeLeaveLFormLbl.setToolTipText("");

        javax.swing.GroupLayout employeeLeaveLFormPnlLayout = new javax.swing.GroupLayout(employeeLeaveLFormPnl);
        employeeLeaveLFormPnl.setLayout(employeeLeaveLFormPnlLayout);
        employeeLeaveLFormPnlLayout.setHorizontalGroup(
            employeeLeaveLFormPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeeLeaveLFormPnlLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(employeeLeaveLFormLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        employeeLeaveLFormPnlLayout.setVerticalGroup(
            employeeLeaveLFormPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeeLeaveLFormPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(employeeLeaveLFormLbl)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        employeeLeaveLFormLbl.getAccessibleContext().setAccessibleName("employeeLeaveLFormLbl");

        employeeLeaveFALeaveBrdrPnl.setBackground(new java.awt.Color(233, 233, 233));
        employeeLeaveFALeaveBrdrPnl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        employeeLeaveFALeaveBrdrPnl.setForeground(new java.awt.Color(178, 178, 178));

        employeeLeaveFALeavePnl.setBackground(new java.awt.Color(146, 192, 253));
        employeeLeaveFALeavePnl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        employeeLeaveFALeavePnl.setForeground(new java.awt.Color(30, 58, 138));
        employeeLeaveFALeavePnl.setPreferredSize(new java.awt.Dimension(126, 40));

        employeeLeaveFALeaveLbl.setBackground(new java.awt.Color(255, 255, 255));
        employeeLeaveFALeaveLbl.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        employeeLeaveFALeaveLbl.setForeground(new java.awt.Color(31, 41, 55));
        employeeLeaveFALeaveLbl.setText(" File A Leave");
        employeeLeaveFALeaveLbl.setToolTipText("");

        javax.swing.GroupLayout employeeLeaveFALeavePnlLayout = new javax.swing.GroupLayout(employeeLeaveFALeavePnl);
        employeeLeaveFALeavePnl.setLayout(employeeLeaveFALeavePnlLayout);
        employeeLeaveFALeavePnlLayout.setHorizontalGroup(
            employeeLeaveFALeavePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeeLeaveFALeavePnlLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(employeeLeaveFALeaveLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        employeeLeaveFALeavePnlLayout.setVerticalGroup(
            employeeLeaveFALeavePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(employeeLeaveFALeaveLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        employeeLeaveFALeaveLbl.getAccessibleContext().setAccessibleName("employeeLeaveFALeaveLbl");

        employeeLeaveReasonLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        employeeLeaveReasonLbl.setForeground(new java.awt.Color(31, 41, 55));
        employeeLeaveReasonLbl.setText("Reason");

        employeeLeaveSubmitBtn.setBackground(new java.awt.Color(59, 130, 246));
        employeeLeaveSubmitBtn.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        employeeLeaveSubmitBtn.setForeground(new java.awt.Color(255, 255, 255));
        employeeLeaveSubmitBtn.setText("Submit");
        employeeLeaveSubmitBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(30, 42, 56)));
        employeeLeaveSubmitBtn.addActionListener(this::employeeLeaveSubmitBtnActionPerformed);

        employeeLeaveFromLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        employeeLeaveFromLbl.setForeground(new java.awt.Color(31, 41, 55));
        employeeLeaveFromLbl.setText("To");

        employeeLeaveReasonFld.setForeground(new java.awt.Color(31, 41, 55));
        employeeLeaveReasonFld.setText(" ");
        employeeLeaveReasonFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        employeeLeaveReasonFld.addActionListener(this::employeeLeaveReasonFldActionPerformed);

        employeeLeaveENameLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        employeeLeaveENameLbl.setForeground(new java.awt.Color(31, 41, 55));
        employeeLeaveENameLbl.setText("From");

        employeeLeaveFromDtChsr.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        employeeLeaveFromDtChsr.setForeground(new java.awt.Color(31, 41, 55));

        employeeLeaveToDtChsr.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(30, 42, 56)));
        employeeLeaveToDtChsr.setForeground(new java.awt.Color(31, 41, 55));

        employeeLeaveTTypeCbx.setForeground(new java.awt.Color(31, 41, 55));
        employeeLeaveTTypeCbx.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));

        javax.swing.GroupLayout employeeLeaveFALeaveBrdrPnlLayout = new javax.swing.GroupLayout(employeeLeaveFALeaveBrdrPnl);
        employeeLeaveFALeaveBrdrPnl.setLayout(employeeLeaveFALeaveBrdrPnlLayout);
        employeeLeaveFALeaveBrdrPnlLayout.setHorizontalGroup(
            employeeLeaveFALeaveBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeeLeaveFALeaveBrdrPnlLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(employeeLeaveFALeaveBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(employeeLeaveFALeaveBrdrPnlLayout.createSequentialGroup()
                        .addGroup(employeeLeaveFALeaveBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(employeeLeaveENameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(employeeLeaveFALeavePnl, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(employeeLeaveReasonLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(employeeLeaveFALeaveBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, employeeLeaveFALeaveBrdrPnlLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(employeeLeaveSubmitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(employeeLeaveFALeaveBrdrPnlLayout.createSequentialGroup()
                                .addGroup(employeeLeaveFALeaveBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(employeeLeaveTTypeCbx, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(employeeLeaveFromDtChsr, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(employeeLeaveFromLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(employeeLeaveToDtChsr, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(employeeLeaveReasonFld, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 21, Short.MAX_VALUE))
        );
        employeeLeaveFALeaveBrdrPnlLayout.setVerticalGroup(
            employeeLeaveFALeaveBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeeLeaveFALeaveBrdrPnlLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(employeeLeaveFALeaveBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(employeeLeaveFALeaveBrdrPnlLayout.createSequentialGroup()
                        .addGroup(employeeLeaveFALeaveBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(employeeLeaveFALeavePnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(employeeLeaveFALeaveBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(employeeLeaveSubmitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(employeeLeaveTTypeCbx, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(employeeLeaveFALeaveBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(employeeLeaveFromLbl, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(employeeLeaveENameLbl)
                            .addComponent(employeeLeaveFromDtChsr, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(employeeLeaveToDtChsr, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(employeeLeaveReasonLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(employeeLeaveReasonFld, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        employeeLeaveFALeavePnl.getAccessibleContext().setAccessibleName("employeeLeaveFALeavePnl");
        employeeLeaveReasonLbl.getAccessibleContext().setAccessibleName("employeeLeaveReasonLbl");
        employeeLeaveSubmitBtn.getAccessibleContext().setAccessibleName("employeeLeaveSubmitBtn");
        employeeLeaveFromLbl.getAccessibleContext().setAccessibleName("employeeLeaveFromLbl");
        employeeLeaveReasonFld.getAccessibleContext().setAccessibleName("employeeLeaveReasonFld");
        employeeLeaveENameLbl.getAccessibleContext().setAccessibleName("employeeLeaveENameLbl");
        employeeLeaveFromDtChsr.getAccessibleContext().setAccessibleName("employeeLeaveFromDtChsr");
        employeeLeaveToDtChsr.getAccessibleContext().setAccessibleName("employeeLeaveToDtChsr");
        employeeLeaveTTypeCbx.getAccessibleContext().setAccessibleName("employeeLeaveTTypeCbx");

        javax.swing.GroupLayout employeeLeaveLFormBrdrPnlLayout = new javax.swing.GroupLayout(employeeLeaveLFormBrdrPnl);
        employeeLeaveLFormBrdrPnl.setLayout(employeeLeaveLFormBrdrPnlLayout);
        employeeLeaveLFormBrdrPnlLayout.setHorizontalGroup(
            employeeLeaveLFormBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, employeeLeaveLFormBrdrPnlLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(employeeLeaveLFormPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(260, 260, 260))
            .addGroup(employeeLeaveLFormBrdrPnlLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(employeeLeaveFALeaveBrdrPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        employeeLeaveLFormBrdrPnlLayout.setVerticalGroup(
            employeeLeaveLFormBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, employeeLeaveLFormBrdrPnlLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(employeeLeaveLFormPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(employeeLeaveFALeaveBrdrPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        employeeLeaveLFormPnl.getAccessibleContext().setAccessibleName("employeeLeaveLFormPnl");
        employeeLeaveFALeaveBrdrPnl.getAccessibleContext().setAccessibleName("employeeLeaveFALeaveBrdrPnl");

        employeeLeaveRecordsBrdrPnl.setBackground(new java.awt.Color(178, 178, 178));
        employeeLeaveRecordsBrdrPnl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 2, true));

        employeeLeaveRecordsLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        employeeLeaveRecordsLbl.setText("Records");

        employeeLeaveRecordsBrdrScrlPnl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));

        employeeLeaveRecordsTbl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        employeeLeaveRecordsTbl.setForeground(new java.awt.Color(30, 42, 56));
        employeeLeaveRecordsTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Leave Type", "From", "To", "Date Filed", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        employeeLeaveRecordsTbl.setGridColor(new java.awt.Color(178, 178, 178));
        employeeLeaveRecordsTbl.setSelectionForeground(new java.awt.Color(30, 42, 56));
        employeeLeaveRecordsBrdrScrlPnl.setViewportView(employeeLeaveRecordsTbl);
        employeeLeaveRecordsTbl.getAccessibleContext().setAccessibleName("employeeLeaveRecordsTbl");

        javax.swing.GroupLayout employeeLeaveRecordsBrdrPnlLayout = new javax.swing.GroupLayout(employeeLeaveRecordsBrdrPnl);
        employeeLeaveRecordsBrdrPnl.setLayout(employeeLeaveRecordsBrdrPnlLayout);
        employeeLeaveRecordsBrdrPnlLayout.setHorizontalGroup(
            employeeLeaveRecordsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeeLeaveRecordsBrdrPnlLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(employeeLeaveRecordsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, employeeLeaveRecordsBrdrPnlLayout.createSequentialGroup()
                        .addComponent(employeeLeaveRecordsLbl)
                        .addGap(319, 319, 319))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, employeeLeaveRecordsBrdrPnlLayout.createSequentialGroup()
                        .addComponent(employeeLeaveRecordsBrdrScrlPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 667, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))))
        );
        employeeLeaveRecordsBrdrPnlLayout.setVerticalGroup(
            employeeLeaveRecordsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeeLeaveRecordsBrdrPnlLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(employeeLeaveRecordsLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(employeeLeaveRecordsBrdrScrlPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        employeeLeaveRecordsLbl.getAccessibleContext().setAccessibleName("employeeLeaveRecordsLbl");
        employeeLeaveRecordsBrdrScrlPnl.getAccessibleContext().setAccessibleName("employeeLeaveRecordsBrdrScrlPnl");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(employeeLeaveSidebarPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(employeeLeaveLRecordsPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeeLeaveLFormBrdrPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeeLeaveRecordsBrdrPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(employeeLeaveSidebarPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(employeeLeaveLRecordsPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(employeeLeaveRecordsBrdrPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(employeeLeaveLFormBrdrPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        employeeLeaveSidebarPnl.getAccessibleContext().setAccessibleName("employeeLeaveSidebarPnl");
        employeeLeaveLRecordsPnl.getAccessibleContext().setAccessibleName("employeeLeaveLDetailsPnl");
        employeeLeaveLFormBrdrPnl.getAccessibleContext().setAccessibleName("employeeLeaveLFormBrdrPnl");
        employeeLeaveRecordsBrdrPnl.getAccessibleContext().setAccessibleName("employeeLeaveRecordsBrdrPnl");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void employeeLeaveMainDashboardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeLeaveMainDashboardBtnActionPerformed
        // TODO add your handling code here:
        GuiUtil.openFrame(this);
    }//GEN-LAST:event_employeeLeaveMainDashboardBtnActionPerformed

    private void employeeLeaveSubmitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeLeaveSubmitBtnActionPerformed
        // TODO add your handling code here:
        
        String employeeNumber = Session.getCurrentUser().getEmployeeNumber();
        
        try {
            
            String requestId = leaveService.generateNextLeaveId(employeeNumber);
            LocalDate dateFiled = LocalDate.now();
        
            // Leave Type
            LeaveType selectedLeaveType = null;
            Object selectedItem = employeeLeaveTTypeCbx.getSelectedItem();

            if (selectedItem instanceof LeaveType) {
                selectedLeaveType = (LeaveType) selectedItem;
            } else {
                throw new IllegalArgumentException("Please select a valid leave type.");
            }
           
            Date fromDate = employeeLeaveFromDtChsr.getDate();
            Date toDate = employeeLeaveToDtChsr.getDate();

            if (fromDate == null || toDate == null) {
                throw new IllegalArgumentException("Please select both Start and End dates.");
            }

            LocalDate startDate = DateUtils.convertDateToLocalDate(fromDate);
            LocalDate endDate = DateUtils.convertDateToLocalDate(toDate);
            
            String reason = employeeLeaveReasonFld.getText();
            if (reason == null || reason.isEmpty() || reason.isBlank()) {
                throw new IllegalArgumentException("Please provide a reason for the leave.");
            }
            
            LeaveRequest leaveRequest = new LeaveRequest(requestId, employeeNumber, dateFiled, startDate, endDate, selectedLeaveType,  reason);
            
            
            // Submit Leave
            leaveService.submitLeaveRequest(leaveRequest);
         
            JOptionPane.showMessageDialog(this, "Leave request submitted successfully!");
            
            populateLeaveRecords();

        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Input Error", JOptionPane.WARNING_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "An error occurred: " + e.getMessage(), "System Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace(); 
        }

        
        
    }//GEN-LAST:event_employeeLeaveSubmitBtnActionPerformed

    private void employeeLeaveReasonFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeLeaveReasonFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeLeaveReasonFldActionPerformed

    private void employeeLeaveLListBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeLeaveLListBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();

        new HRLeaveListUI().setVisible(true);
    }//GEN-LAST:event_employeeLeaveLListBtnActionPerformed

    private void employeeLeaveLDetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeLeaveLDetailsBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeLeaveLDetailsBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EmployeeLeaveUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel employeeLeaveENameLbl;
    private javax.swing.JPanel employeeLeaveFALeaveBrdrPnl;
    private javax.swing.JLabel employeeLeaveFALeaveLbl;
    private javax.swing.JPanel employeeLeaveFALeavePnl;
    private com.toedter.calendar.JDateChooser employeeLeaveFromDtChsr;
    private javax.swing.JLabel employeeLeaveFromLbl;
    private javax.swing.JButton employeeLeaveLDetailsBtn;
    private javax.swing.JPanel employeeLeaveLFormBrdrPnl;
    private javax.swing.JLabel employeeLeaveLFormLbl;
    private javax.swing.JPanel employeeLeaveLFormPnl;
    private javax.swing.JButton employeeLeaveLListBtn;
    private javax.swing.JLabel employeeLeaveLRecordsLbl;
    private javax.swing.JPanel employeeLeaveLRecordsPnl;
    private javax.swing.JButton employeeLeaveMainDashboardBtn;
    private javax.swing.JLabel employeeLeaveMotorPHIconImgLbl;
    private javax.swing.JTextField employeeLeaveReasonFld;
    private javax.swing.JLabel employeeLeaveReasonLbl;
    private javax.swing.JPanel employeeLeaveRecordsBrdrPnl;
    private javax.swing.JScrollPane employeeLeaveRecordsBrdrScrlPnl;
    private javax.swing.JLabel employeeLeaveRecordsLbl;
    private javax.swing.JTable employeeLeaveRecordsTbl;
    private javax.swing.JPanel employeeLeaveSidebarPnl;
    private javax.swing.JButton employeeLeaveSubmitBtn;
    private javax.swing.JComboBox<Object> employeeLeaveTTypeCbx;
    private com.toedter.calendar.JDateChooser employeeLeaveToDtChsr;
    // End of variables declaration//GEN-END:variables
}
