/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.motorph.ui;

import com.motorph.dao.CsvEmployeeDAO;
import com.motorph.model.AttendanceRecord;
import com.motorph.model.Employee;
import com.motorph.service.AttendanceService;
import com.motorph.service.EmployeeService;
import com.motorph.util.AppContext;
import com.motorph.util.DateUtils;
import com.motorph.util.Session;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lenovo
 */
public class EmployeeDashboardUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EmployeeDashboardUI.class.getName());
    private EmployeeService empService;
    private AttendanceService attendanceService;
    

    /**
     * Creates new form EMPLOYEEDASH
     */
    public EmployeeDashboardUI() {
        initComponents();
        
        this.empService = AppContext.getEmployeeService();
        this.attendanceService = AppContext.getAttendanceService();
                
        populateFields();
        populateAttendanceLogs();
    }
    
        private void populateFields() {
            Employee emp = empService.findEmployee(Session.getCurrentUser().getEmployeeNumber());
                    
            employeeDashboardENumberFld.setText(emp.getEmployeeNumber());
            employeeDashboardFNameFld.setText(emp.getFirstName());
            employeeDashboardLNameFld.setText(emp.getLastName());
            employeeDashboardBirthdayDtChsr.setDate(DateUtils.localDateToUtilDate(emp.getBirthday()));
            employeeDashboardAddressFld.setText(emp.getAddress());
            employeeDashboardPhnNumberFld.setText(emp.getPhoneNumber());
            employeeDashboardSSSFld.setText(emp.getSSSNumber());
            employeeDashboardPhilHealthFld.setText(emp.getPhilhealthNumber());
            employeeDashboardTINFld.setText(emp.getTIN());
            employeeDashboardPagIbigFld.setText(emp.getPagIbigNumber());
            employeeDashboardStatusCbx.setSelectedItem(emp.getStatus());
            employeeDashboardPositionFld.setText(emp.getPosition());
            employeeDashboardISupervisorFld.setText(emp.getImmediateSupervisor());
            employeeDashboardBasicSalaryFld.setText(String.valueOf(emp.getBasicSalary()));
            employeeDashboardRiceSubsidyFld.setText(String.valueOf(emp.getRiceSubsidy()));
            employeeDashboardPhnAllowanceFld.setText(String.valueOf(emp.getPhoneAllowance()));
            employeeDashboardCltAllowanceFld.setText(String.valueOf(emp.getClothingAllowance()));
        }
        
        
        private void populateAttendanceLogs() {
            
            String empNumber = Session.getCurrentUser().getEmployeeNumber();
            
            List<AttendanceRecord> logs = attendanceService.getAttendanceByEmployee(empNumber);
            Employee emp = empService.findEmployee(empNumber);
            
            DefaultTableModel model = (DefaultTableModel) employeeDashboardAttLogsTbl.getModel();
            
            model.setRowCount(0);
            
            for (AttendanceRecord log : logs) {
                
                Object[] row = {
                    String.valueOf(log.getDate()),
                    String.valueOf(log.getLogIn()),
                    String.valueOf(log.getLogOut()),
                    "GOODS :)"
                };
                
                model.addRow(row);
            }
            
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        employeeDashboardSidebarPnl = new javax.swing.JPanel();
        employeeDashboardDashboardBtn = new javax.swing.JButton();
        employeeDashboardMainDashboardBtn = new javax.swing.JButton();
        hrEDetailsMotorPHIconImgLbl = new javax.swing.JLabel();
        employeeDashboardEDetailsBrdrPnl = new javax.swing.JPanel();
        employeeDashboardENumberLbl = new javax.swing.JLabel();
        employeeDashboardLNameLbl = new javax.swing.JLabel();
        employeeDashboardAddressLbl = new javax.swing.JLabel();
        employeeDashboardBirthdayLbl = new javax.swing.JLabel();
        employeeDashboardENumberFld = new javax.swing.JTextField();
        employeeDashboardAddressFld = new javax.swing.JTextField();
        employeeDashboardLNameFld = new javax.swing.JTextField();
        employeeDashboardPositionFld = new javax.swing.JTextField();
        employeeDashboardBasicSalaryFld = new javax.swing.JTextField();
        employeeDashboardPhnAllowanceFld = new javax.swing.JTextField();
        employeeDashboardPositionLbl = new javax.swing.JLabel();
        employeeDashboardBasicSalaryLbl = new javax.swing.JLabel();
        employeeDashboardPhnAllowanceLbl = new javax.swing.JLabel();
        employeeDashboardSSSFld = new javax.swing.JTextField();
        employeeDashboardPhilHealthFld = new javax.swing.JTextField();
        employeeDashboardSSSLbl = new javax.swing.JLabel();
        employeeDashboardPhilHealthLbl = new javax.swing.JLabel();
        employeeDashboardFNameFld = new javax.swing.JTextField();
        employeeDashboardISupervisorLbl = new javax.swing.JLabel();
        employeeDashboardPhnNumberFld = new javax.swing.JTextField();
        employeeDashboardISupervisorFld = new javax.swing.JTextField();
        employeeDashboardRiceSubsidyFld = new javax.swing.JTextField();
        employeeDashboardCltAllowanceFld = new javax.swing.JTextField();
        employeeDashboardTINFld = new javax.swing.JTextField();
        employeeDashboardPagIbigFld = new javax.swing.JTextField();
        employeeDashboardFNameLbl = new javax.swing.JLabel();
        employeeDashboardPhnNumberLbl = new javax.swing.JLabel();
        employeeDashboardRiceSubsidyLbl = new javax.swing.JLabel();
        employeeDashboardCltAllowanceLbl = new javax.swing.JLabel();
        employeeDashboardTINLbl = new javax.swing.JLabel();
        employeeDashboardPagIbigLbl = new javax.swing.JLabel();
        employeeDashboardStatusLbl = new javax.swing.JLabel();
        employeeDashboardStatusCbx = new javax.swing.JComboBox<>();
        employeeDashboardBirthdayDtChsr = new com.toedter.calendar.JDateChooser();
        hrEDetailsEDetailsPnl = new javax.swing.JPanel();
        employeeDashboardProfileLbl = new javax.swing.JLabel();
        employeeDashboardResetPassBrdrPnl = new javax.swing.JPanel();
        employeeDashboardResetPassPnl = new javax.swing.JPanel();
        employeeDashboardResetPassLbl = new javax.swing.JLabel();
        employeeDashboardPassBrdrPnl = new javax.swing.JPanel();
        employeeDashboardCurrPassLbl = new javax.swing.JLabel();
        employeeDashboardCurrPassFld = new javax.swing.JTextField();
        employeeDashboardNewPassLbl = new javax.swing.JLabel();
        employeeDashboardNewPassFld = new javax.swing.JTextField();
        employeeDashboardConfirmBtn = new javax.swing.JButton();
        employeeDashboardTimeOutBtn = new javax.swing.JButton();
        employeeDashboardTimeInBtn = new javax.swing.JButton();
        employeeDashboardAttLogsBrdrPnl = new javax.swing.JPanel();
        employeeDashboardAttLogsBrdrScrlPnl = new javax.swing.JScrollPane();
        employeeDashboardAttLogsTbl = new javax.swing.JTable();
        employeeDashboardAttLogsPnl = new javax.swing.JPanel();
        employeeDashboardAttLogsLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        employeeDashboardSidebarPnl.setBackground(new java.awt.Color(30, 58, 138));
        employeeDashboardSidebarPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        employeeDashboardDashboardBtn.setBackground(new java.awt.Color(30, 42, 56));
        employeeDashboardDashboardBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        employeeDashboardDashboardBtn.setForeground(new java.awt.Color(255, 255, 255));
        employeeDashboardDashboardBtn.setText("Dashboard");
        employeeDashboardDashboardBtn.setToolTipText("");
        employeeDashboardDashboardBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        employeeDashboardDashboardBtn.addActionListener(this::employeeDashboardDashboardBtnActionPerformed);
        employeeDashboardSidebarPnl.add(employeeDashboardDashboardBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 199, 216, 39));
        employeeDashboardDashboardBtn.getAccessibleContext().setAccessibleName("employeeDashboardDashboardBtn");

        employeeDashboardMainDashboardBtn.setBackground(new java.awt.Color(30, 42, 56));
        employeeDashboardMainDashboardBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        employeeDashboardMainDashboardBtn.setForeground(new java.awt.Color(255, 255, 255));
        employeeDashboardMainDashboardBtn.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        employeeDashboardMainDashboardBtn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        employeeDashboardMainDashboardBtn.setLabel("Main Dashboard");
        employeeDashboardMainDashboardBtn.addActionListener(this::employeeDashboardMainDashboardBtnActionPerformed);
        employeeDashboardSidebarPnl.add(employeeDashboardMainDashboardBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 647, -1, 39));

        hrEDetailsMotorPHIconImgLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/motorph/img/MotorPHIconImg.png"))); // NOI18N
        employeeDashboardSidebarPnl.add(hrEDetailsMotorPHIconImgLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 180, -1));
        hrEDetailsMotorPHIconImgLbl.getAccessibleContext().setAccessibleName("employeeDashboardMainDashboardBtn");

        employeeDashboardEDetailsBrdrPnl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 2, true));
        employeeDashboardEDetailsBrdrPnl.setForeground(new java.awt.Color(30, 42, 56));
        employeeDashboardEDetailsBrdrPnl.setFocusable(false);
        employeeDashboardEDetailsBrdrPnl.setPreferredSize(new java.awt.Dimension(700, 469));
        employeeDashboardEDetailsBrdrPnl.setRequestFocusEnabled(false);

        employeeDashboardENumberLbl.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        employeeDashboardENumberLbl.setForeground(new java.awt.Color(31, 41, 55));
        employeeDashboardENumberLbl.setText("Employee #");

        employeeDashboardLNameLbl.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        employeeDashboardLNameLbl.setForeground(new java.awt.Color(31, 41, 55));
        employeeDashboardLNameLbl.setText("Last Name");

        employeeDashboardAddressLbl.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        employeeDashboardAddressLbl.setForeground(new java.awt.Color(31, 41, 55));
        employeeDashboardAddressLbl.setText("Address");

        employeeDashboardBirthdayLbl.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        employeeDashboardBirthdayLbl.setForeground(new java.awt.Color(31, 41, 55));
        employeeDashboardBirthdayLbl.setText("Birthday");

        employeeDashboardENumberFld.setForeground(new java.awt.Color(30, 42, 56));
        employeeDashboardENumberFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        employeeDashboardENumberFld.setCaretColor(new java.awt.Color(31, 41, 55));
        employeeDashboardENumberFld.setDisabledTextColor(new java.awt.Color(31, 41, 55));
        employeeDashboardENumberFld.setEnabled(false);
        employeeDashboardENumberFld.addActionListener(this::employeeDashboardENumberFldActionPerformed);

        employeeDashboardAddressFld.setForeground(new java.awt.Color(30, 42, 56));
        employeeDashboardAddressFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        employeeDashboardAddressFld.setCaretColor(new java.awt.Color(31, 41, 55));
        employeeDashboardAddressFld.setDisabledTextColor(new java.awt.Color(31, 41, 55));
        employeeDashboardAddressFld.setEnabled(false);
        employeeDashboardAddressFld.addActionListener(this::employeeDashboardAddressFldActionPerformed);

        employeeDashboardLNameFld.setForeground(new java.awt.Color(30, 42, 56));
        employeeDashboardLNameFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        employeeDashboardLNameFld.setCaretColor(new java.awt.Color(31, 41, 55));
        employeeDashboardLNameFld.setDisabledTextColor(new java.awt.Color(31, 41, 55));
        employeeDashboardLNameFld.setEnabled(false);
        employeeDashboardLNameFld.addActionListener(this::employeeDashboardLNameFldActionPerformed);

        employeeDashboardPositionFld.setForeground(new java.awt.Color(30, 42, 56));
        employeeDashboardPositionFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        employeeDashboardPositionFld.setCaretColor(new java.awt.Color(31, 41, 55));
        employeeDashboardPositionFld.setDisabledTextColor(new java.awt.Color(31, 41, 55));
        employeeDashboardPositionFld.setEnabled(false);
        employeeDashboardPositionFld.addActionListener(this::employeeDashboardPositionFldActionPerformed);

        employeeDashboardBasicSalaryFld.setForeground(new java.awt.Color(30, 42, 56));
        employeeDashboardBasicSalaryFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        employeeDashboardBasicSalaryFld.setCaretColor(new java.awt.Color(31, 41, 55));
        employeeDashboardBasicSalaryFld.setDisabledTextColor(new java.awt.Color(31, 41, 55));
        employeeDashboardBasicSalaryFld.setEnabled(false);
        employeeDashboardBasicSalaryFld.addActionListener(this::employeeDashboardBasicSalaryFldActionPerformed);

        employeeDashboardPhnAllowanceFld.setForeground(new java.awt.Color(30, 42, 56));
        employeeDashboardPhnAllowanceFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        employeeDashboardPhnAllowanceFld.setCaretColor(new java.awt.Color(31, 41, 55));
        employeeDashboardPhnAllowanceFld.setDisabledTextColor(new java.awt.Color(31, 41, 55));
        employeeDashboardPhnAllowanceFld.setEnabled(false);
        employeeDashboardPhnAllowanceFld.addActionListener(this::employeeDashboardPhnAllowanceFldActionPerformed);

        employeeDashboardPositionLbl.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        employeeDashboardPositionLbl.setForeground(new java.awt.Color(31, 41, 55));
        employeeDashboardPositionLbl.setText("Position");

        employeeDashboardBasicSalaryLbl.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        employeeDashboardBasicSalaryLbl.setForeground(new java.awt.Color(31, 41, 55));
        employeeDashboardBasicSalaryLbl.setText("Basic Salary");

        employeeDashboardPhnAllowanceLbl.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        employeeDashboardPhnAllowanceLbl.setForeground(new java.awt.Color(31, 41, 55));
        employeeDashboardPhnAllowanceLbl.setText("Phone Allowance");

        employeeDashboardSSSFld.setForeground(new java.awt.Color(30, 42, 56));
        employeeDashboardSSSFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        employeeDashboardSSSFld.setCaretColor(new java.awt.Color(31, 41, 55));
        employeeDashboardSSSFld.setDisabledTextColor(new java.awt.Color(31, 41, 55));
        employeeDashboardSSSFld.setEnabled(false);
        employeeDashboardSSSFld.addActionListener(this::employeeDashboardSSSFldActionPerformed);

        employeeDashboardPhilHealthFld.setForeground(new java.awt.Color(30, 42, 56));
        employeeDashboardPhilHealthFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        employeeDashboardPhilHealthFld.setDisabledTextColor(new java.awt.Color(31, 41, 55));
        employeeDashboardPhilHealthFld.setEnabled(false);
        employeeDashboardPhilHealthFld.addActionListener(this::employeeDashboardPhilHealthFldActionPerformed);

        employeeDashboardSSSLbl.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        employeeDashboardSSSLbl.setForeground(new java.awt.Color(31, 41, 55));
        employeeDashboardSSSLbl.setText("SSS");

        employeeDashboardPhilHealthLbl.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        employeeDashboardPhilHealthLbl.setForeground(new java.awt.Color(31, 41, 55));
        employeeDashboardPhilHealthLbl.setText("PhilHealth");

        employeeDashboardFNameFld.setForeground(new java.awt.Color(30, 42, 56));
        employeeDashboardFNameFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        employeeDashboardFNameFld.setCaretColor(new java.awt.Color(31, 41, 55));
        employeeDashboardFNameFld.setDisabledTextColor(new java.awt.Color(31, 41, 55));
        employeeDashboardFNameFld.setEnabled(false);
        employeeDashboardFNameFld.addActionListener(this::employeeDashboardFNameFldActionPerformed);

        employeeDashboardISupervisorLbl.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        employeeDashboardISupervisorLbl.setForeground(new java.awt.Color(31, 41, 55));
        employeeDashboardISupervisorLbl.setText("Immediate Supervisor");

        employeeDashboardPhnNumberFld.setForeground(new java.awt.Color(30, 42, 56));
        employeeDashboardPhnNumberFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        employeeDashboardPhnNumberFld.setCaretColor(new java.awt.Color(31, 41, 55));
        employeeDashboardPhnNumberFld.setDisabledTextColor(new java.awt.Color(31, 41, 55));
        employeeDashboardPhnNumberFld.setEnabled(false);
        employeeDashboardPhnNumberFld.addActionListener(this::employeeDashboardPhnNumberFldActionPerformed);

        employeeDashboardISupervisorFld.setForeground(new java.awt.Color(30, 42, 56));
        employeeDashboardISupervisorFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        employeeDashboardISupervisorFld.setCaretColor(new java.awt.Color(31, 41, 55));
        employeeDashboardISupervisorFld.setDisabledTextColor(new java.awt.Color(31, 41, 55));
        employeeDashboardISupervisorFld.setEnabled(false);
        employeeDashboardISupervisorFld.addActionListener(this::employeeDashboardISupervisorFldActionPerformed);

        employeeDashboardRiceSubsidyFld.setForeground(new java.awt.Color(30, 42, 56));
        employeeDashboardRiceSubsidyFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        employeeDashboardRiceSubsidyFld.setCaretColor(new java.awt.Color(31, 41, 55));
        employeeDashboardRiceSubsidyFld.setDisabledTextColor(new java.awt.Color(31, 41, 55));
        employeeDashboardRiceSubsidyFld.setEnabled(false);
        employeeDashboardRiceSubsidyFld.addActionListener(this::employeeDashboardRiceSubsidyFldActionPerformed);

        employeeDashboardCltAllowanceFld.setForeground(new java.awt.Color(30, 42, 56));
        employeeDashboardCltAllowanceFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        employeeDashboardCltAllowanceFld.setCaretColor(new java.awt.Color(31, 41, 55));
        employeeDashboardCltAllowanceFld.setDisabledTextColor(new java.awt.Color(31, 41, 55));
        employeeDashboardCltAllowanceFld.setEnabled(false);
        employeeDashboardCltAllowanceFld.addActionListener(this::employeeDashboardCltAllowanceFldActionPerformed);

        employeeDashboardTINFld.setForeground(new java.awt.Color(30, 42, 56));
        employeeDashboardTINFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        employeeDashboardTINFld.setCaretColor(new java.awt.Color(31, 41, 55));
        employeeDashboardTINFld.setDisabledTextColor(new java.awt.Color(31, 41, 55));
        employeeDashboardTINFld.setEnabled(false);
        employeeDashboardTINFld.addActionListener(this::employeeDashboardTINFldActionPerformed);

        employeeDashboardPagIbigFld.setForeground(new java.awt.Color(30, 42, 56));
        employeeDashboardPagIbigFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        employeeDashboardPagIbigFld.setCaretColor(new java.awt.Color(31, 41, 55));
        employeeDashboardPagIbigFld.setDisabledTextColor(new java.awt.Color(31, 41, 55));
        employeeDashboardPagIbigFld.setEnabled(false);
        employeeDashboardPagIbigFld.addActionListener(this::employeeDashboardPagIbigFldActionPerformed);

        employeeDashboardFNameLbl.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        employeeDashboardFNameLbl.setForeground(new java.awt.Color(31, 41, 55));
        employeeDashboardFNameLbl.setText("First Name");

        employeeDashboardPhnNumberLbl.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        employeeDashboardPhnNumberLbl.setForeground(new java.awt.Color(31, 41, 55));
        employeeDashboardPhnNumberLbl.setText("Phone Number");

        employeeDashboardRiceSubsidyLbl.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        employeeDashboardRiceSubsidyLbl.setForeground(new java.awt.Color(31, 41, 55));
        employeeDashboardRiceSubsidyLbl.setText("Rice Subsidy");

        employeeDashboardCltAllowanceLbl.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        employeeDashboardCltAllowanceLbl.setForeground(new java.awt.Color(31, 41, 55));
        employeeDashboardCltAllowanceLbl.setText("Clothing Allowance");

        employeeDashboardTINLbl.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        employeeDashboardTINLbl.setForeground(new java.awt.Color(31, 41, 55));
        employeeDashboardTINLbl.setText("TIN");

        employeeDashboardPagIbigLbl.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        employeeDashboardPagIbigLbl.setForeground(new java.awt.Color(31, 41, 55));
        employeeDashboardPagIbigLbl.setText("Pag-Ibig");

        employeeDashboardStatusLbl.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        employeeDashboardStatusLbl.setForeground(new java.awt.Color(31, 41, 55));
        employeeDashboardStatusLbl.setText("Status");

        employeeDashboardStatusCbx.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        employeeDashboardStatusCbx.setForeground(new java.awt.Color(31, 41, 55));
        employeeDashboardStatusCbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose", "Regular", "Probationary" }));
        employeeDashboardStatusCbx.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        employeeDashboardStatusCbx.setEnabled(false);

        employeeDashboardBirthdayDtChsr.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        employeeDashboardBirthdayDtChsr.setForeground(new java.awt.Color(31, 41, 55));
        employeeDashboardBirthdayDtChsr.setEnabled(false);

        javax.swing.GroupLayout employeeDashboardEDetailsBrdrPnlLayout = new javax.swing.GroupLayout(employeeDashboardEDetailsBrdrPnl);
        employeeDashboardEDetailsBrdrPnl.setLayout(employeeDashboardEDetailsBrdrPnlLayout);
        employeeDashboardEDetailsBrdrPnlLayout.setHorizontalGroup(
            employeeDashboardEDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeeDashboardEDetailsBrdrPnlLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(employeeDashboardEDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(employeeDashboardENumberLbl)
                    .addComponent(employeeDashboardLNameLbl)
                    .addComponent(employeeDashboardAddressLbl)
                    .addComponent(employeeDashboardBirthdayLbl)
                    .addComponent(employeeDashboardPositionLbl)
                    .addComponent(employeeDashboardBasicSalaryLbl)
                    .addComponent(employeeDashboardPhnAllowanceLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeeDashboardSSSLbl)
                    .addComponent(employeeDashboardPhilHealthLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(employeeDashboardEDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(employeeDashboardEDetailsBrdrPnlLayout.createSequentialGroup()
                        .addGroup(employeeDashboardEDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(employeeDashboardBirthdayDtChsr, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                            .addComponent(employeeDashboardPhilHealthFld)
                            .addComponent(employeeDashboardSSSFld)
                            .addComponent(employeeDashboardPhnAllowanceFld)
                            .addComponent(employeeDashboardBasicSalaryFld)
                            .addComponent(employeeDashboardPositionFld)
                            .addComponent(employeeDashboardENumberFld))
                        .addGap(18, 18, 18)
                        .addGroup(employeeDashboardEDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(employeeDashboardRiceSubsidyLbl)
                            .addComponent(employeeDashboardCltAllowanceLbl)
                            .addComponent(employeeDashboardTINLbl)
                            .addComponent(employeeDashboardPagIbigLbl)
                            .addComponent(employeeDashboardStatusLbl)
                            .addComponent(employeeDashboardISupervisorLbl)
                            .addComponent(employeeDashboardPhnNumberLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addGroup(employeeDashboardEDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(employeeDashboardPagIbigFld, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(employeeDashboardTINFld, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(employeeDashboardCltAllowanceFld, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(employeeDashboardRiceSubsidyFld, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(employeeDashboardISupervisorFld, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(employeeDashboardPhnNumberFld, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(employeeDashboardStatusCbx, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(employeeDashboardEDetailsBrdrPnlLayout.createSequentialGroup()
                        .addComponent(employeeDashboardLNameFld, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(employeeDashboardFNameLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(employeeDashboardFNameFld, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(employeeDashboardAddressFld))
                .addGap(16, 16, 16))
        );
        employeeDashboardEDetailsBrdrPnlLayout.setVerticalGroup(
            employeeDashboardEDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeeDashboardEDetailsBrdrPnlLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(employeeDashboardEDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employeeDashboardENumberLbl)
                    .addComponent(employeeDashboardENumberFld, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeeDashboardStatusLbl)
                    .addComponent(employeeDashboardStatusCbx, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(employeeDashboardEDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employeeDashboardLNameFld, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeeDashboardLNameLbl)
                    .addComponent(employeeDashboardFNameLbl)
                    .addComponent(employeeDashboardFNameFld, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(employeeDashboardEDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employeeDashboardAddressFld, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeeDashboardAddressLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(employeeDashboardEDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(employeeDashboardEDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(employeeDashboardBirthdayLbl)
                        .addComponent(employeeDashboardPhnNumberFld, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(employeeDashboardPhnNumberLbl))
                    .addComponent(employeeDashboardBirthdayDtChsr, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(employeeDashboardEDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(employeeDashboardEDetailsBrdrPnlLayout.createSequentialGroup()
                        .addGroup(employeeDashboardEDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(employeeDashboardPositionFld, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(employeeDashboardPositionLbl)
                            .addComponent(employeeDashboardISupervisorFld, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(employeeDashboardISupervisorLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(employeeDashboardEDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(employeeDashboardBasicSalaryFld, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(employeeDashboardBasicSalaryLbl)
                            .addComponent(employeeDashboardRiceSubsidyFld, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(employeeDashboardRiceSubsidyLbl, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(employeeDashboardEDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employeeDashboardPhnAllowanceFld, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeeDashboardPhnAllowanceLbl)
                    .addComponent(employeeDashboardCltAllowanceFld, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeeDashboardCltAllowanceLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(employeeDashboardEDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employeeDashboardSSSFld, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeeDashboardSSSLbl)
                    .addComponent(employeeDashboardTINFld, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeeDashboardTINLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(employeeDashboardEDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employeeDashboardPhilHealthFld, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeeDashboardPhilHealthLbl)
                    .addComponent(employeeDashboardPagIbigFld, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeeDashboardPagIbigLbl))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        employeeDashboardENumberLbl.getAccessibleContext().setAccessibleName("employeeDashboardENumberLbl");
        employeeDashboardLNameLbl.getAccessibleContext().setAccessibleName("employeeDashboardLNameLbl");
        employeeDashboardAddressLbl.getAccessibleContext().setAccessibleName("employeeDashboardAddressLbl");
        employeeDashboardBirthdayLbl.getAccessibleContext().setAccessibleName("employeeDashboardBirthdayLbl");
        employeeDashboardENumberFld.getAccessibleContext().setAccessibleName("employeeDashboardENumberFld");
        employeeDashboardAddressFld.getAccessibleContext().setAccessibleName("employeeDashboardAddressFld");
        employeeDashboardLNameFld.getAccessibleContext().setAccessibleName("employeeDashboardLNameFld");
        employeeDashboardPositionFld.getAccessibleContext().setAccessibleName("employeeDashboardPositionFld");
        employeeDashboardBasicSalaryFld.getAccessibleContext().setAccessibleName("employeeDashboardBasicSalaryFld");
        employeeDashboardPhnAllowanceFld.getAccessibleContext().setAccessibleName("employeeDashboardPhnAllowanceFld");
        employeeDashboardPositionLbl.getAccessibleContext().setAccessibleName("employeeDashboardPositionLbl");
        employeeDashboardBasicSalaryLbl.getAccessibleContext().setAccessibleName("employeeDashboardBasicSalaryLbl");
        employeeDashboardPhnAllowanceLbl.getAccessibleContext().setAccessibleName("employeeDashboardPhnAllowanceLbl");
        employeeDashboardSSSFld.getAccessibleContext().setAccessibleName("employeeDashboardSSSFld");
        employeeDashboardPhilHealthFld.getAccessibleContext().setAccessibleName("employeeDashboardPhilHealthFld");
        employeeDashboardSSSLbl.getAccessibleContext().setAccessibleName("employeeDashboardSSSLbl");
        employeeDashboardPhilHealthLbl.getAccessibleContext().setAccessibleName("employeeDashboardPhilHealthLbl");
        employeeDashboardFNameFld.getAccessibleContext().setAccessibleName("employeeDashboardFNameFld");
        employeeDashboardISupervisorLbl.getAccessibleContext().setAccessibleName("employeeDashboardISupervisorLbl");
        employeeDashboardPhnNumberFld.getAccessibleContext().setAccessibleName("employeeDashboardPhnNumberFld");
        employeeDashboardISupervisorFld.getAccessibleContext().setAccessibleName("employeeDashboardISupervisorFld");
        employeeDashboardRiceSubsidyFld.getAccessibleContext().setAccessibleName("employeeDashboardRiceSubsidyFld");
        employeeDashboardCltAllowanceFld.getAccessibleContext().setAccessibleName("employeeDashboardCltAllowanceFld");
        employeeDashboardTINFld.getAccessibleContext().setAccessibleName("employeeDashboardTINFld");
        employeeDashboardPagIbigFld.getAccessibleContext().setAccessibleName("employeeDashboardPagIbigFld");
        employeeDashboardFNameLbl.getAccessibleContext().setAccessibleName("employeeDashboardFNameLbl");
        employeeDashboardPhnNumberLbl.getAccessibleContext().setAccessibleName("employeeDashboardPhnNumberLbl");
        employeeDashboardRiceSubsidyLbl.getAccessibleContext().setAccessibleName("employeeDashboardRiceSubsidyLbl");
        employeeDashboardCltAllowanceLbl.getAccessibleContext().setAccessibleName("employeeDashboardCltAllowanceLbl");
        employeeDashboardTINLbl.getAccessibleContext().setAccessibleName("employeeDashboardTINLbl");
        employeeDashboardPagIbigLbl.getAccessibleContext().setAccessibleName("employeeDashboardPagIbigLbl");
        employeeDashboardStatusLbl.getAccessibleContext().setAccessibleName("employeeDashboardStatusLbl");
        employeeDashboardStatusCbx.getAccessibleContext().setAccessibleName("employeeDashboardStatusCbx");
        employeeDashboardBirthdayDtChsr.getAccessibleContext().setAccessibleName("employeeDashboardBirthdayDtChsr");

        hrEDetailsEDetailsPnl.setBackground(new java.awt.Color(30, 58, 138));
        hrEDetailsEDetailsPnl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        hrEDetailsEDetailsPnl.setForeground(new java.awt.Color(30, 58, 138));
        hrEDetailsEDetailsPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        employeeDashboardProfileLbl.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        employeeDashboardProfileLbl.setForeground(new java.awt.Color(255, 255, 255));
        employeeDashboardProfileLbl.setText("Profile");
        hrEDetailsEDetailsPnl.add(employeeDashboardProfileLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 1, 90, 46));
        employeeDashboardProfileLbl.getAccessibleContext().setAccessibleName("employeeDashboardProfileLbl");

        employeeDashboardResetPassBrdrPnl.setBackground(new java.awt.Color(255, 255, 255));
        employeeDashboardResetPassBrdrPnl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 2, true));

        employeeDashboardResetPassPnl.setBackground(new java.awt.Color(146, 192, 253));
        employeeDashboardResetPassPnl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        employeeDashboardResetPassPnl.setForeground(new java.awt.Color(30, 58, 138));
        employeeDashboardResetPassPnl.setPreferredSize(new java.awt.Dimension(126, 40));

        employeeDashboardResetPassLbl.setBackground(new java.awt.Color(255, 255, 255));
        employeeDashboardResetPassLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        employeeDashboardResetPassLbl.setForeground(new java.awt.Color(31, 41, 55));
        employeeDashboardResetPassLbl.setText("Reset Password");
        employeeDashboardResetPassLbl.setToolTipText("");

        javax.swing.GroupLayout employeeDashboardResetPassPnlLayout = new javax.swing.GroupLayout(employeeDashboardResetPassPnl);
        employeeDashboardResetPassPnl.setLayout(employeeDashboardResetPassPnlLayout);
        employeeDashboardResetPassPnlLayout.setHorizontalGroup(
            employeeDashboardResetPassPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, employeeDashboardResetPassPnlLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(employeeDashboardResetPassLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        employeeDashboardResetPassPnlLayout.setVerticalGroup(
            employeeDashboardResetPassPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeeDashboardResetPassPnlLayout.createSequentialGroup()
                .addComponent(employeeDashboardResetPassLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        employeeDashboardResetPassLbl.getAccessibleContext().setAccessibleName("employeeDashboardResetPassLbl");

        employeeDashboardPassBrdrPnl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));

        employeeDashboardCurrPassLbl.setForeground(new java.awt.Color(31, 41, 55));
        employeeDashboardCurrPassLbl.setText("Current Password");

        employeeDashboardCurrPassFld.setForeground(new java.awt.Color(30, 42, 56));
        employeeDashboardCurrPassFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        employeeDashboardCurrPassFld.setCaretColor(new java.awt.Color(31, 41, 55));
        employeeDashboardCurrPassFld.setDisabledTextColor(new java.awt.Color(31, 41, 55));
        employeeDashboardCurrPassFld.addActionListener(this::employeeDashboardCurrPassFldActionPerformed);

        employeeDashboardNewPassLbl.setForeground(new java.awt.Color(31, 41, 55));
        employeeDashboardNewPassLbl.setText("New Password");

        employeeDashboardNewPassFld.setForeground(new java.awt.Color(30, 42, 56));
        employeeDashboardNewPassFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        employeeDashboardNewPassFld.setCaretColor(new java.awt.Color(31, 41, 55));
        employeeDashboardNewPassFld.setDisabledTextColor(new java.awt.Color(31, 41, 55));
        employeeDashboardNewPassFld.addActionListener(this::employeeDashboardNewPassFldActionPerformed);

        employeeDashboardConfirmBtn.setBackground(new java.awt.Color(34, 197, 94));
        employeeDashboardConfirmBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        employeeDashboardConfirmBtn.setForeground(new java.awt.Color(255, 255, 255));
        employeeDashboardConfirmBtn.setText("Confirm");
        employeeDashboardConfirmBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));

        javax.swing.GroupLayout employeeDashboardPassBrdrPnlLayout = new javax.swing.GroupLayout(employeeDashboardPassBrdrPnl);
        employeeDashboardPassBrdrPnl.setLayout(employeeDashboardPassBrdrPnlLayout);
        employeeDashboardPassBrdrPnlLayout.setHorizontalGroup(
            employeeDashboardPassBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeeDashboardPassBrdrPnlLayout.createSequentialGroup()
                .addGroup(employeeDashboardPassBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(employeeDashboardPassBrdrPnlLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(employeeDashboardPassBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(employeeDashboardNewPassLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(employeeDashboardCurrPassLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(employeeDashboardPassBrdrPnlLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(employeeDashboardPassBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(employeeDashboardCurrPassFld, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(employeeDashboardNewPassFld, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(employeeDashboardPassBrdrPnlLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(employeeDashboardConfirmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        employeeDashboardPassBrdrPnlLayout.setVerticalGroup(
            employeeDashboardPassBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeeDashboardPassBrdrPnlLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(employeeDashboardCurrPassLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(employeeDashboardCurrPassFld, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(employeeDashboardNewPassLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(employeeDashboardNewPassFld, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(employeeDashboardConfirmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        employeeDashboardCurrPassLbl.getAccessibleContext().setAccessibleName("employeeDashboardCurrPassLbl");
        employeeDashboardCurrPassFld.getAccessibleContext().setAccessibleName("employeeDashboardCurrPassFld");
        employeeDashboardNewPassLbl.getAccessibleContext().setAccessibleName("employeeDashboardNewPassLbl");
        employeeDashboardNewPassFld.getAccessibleContext().setAccessibleName("employeeDashboardNewPassFld");
        employeeDashboardConfirmBtn.getAccessibleContext().setAccessibleName("employeeDashboardConfirmBtn");

        javax.swing.GroupLayout employeeDashboardResetPassBrdrPnlLayout = new javax.swing.GroupLayout(employeeDashboardResetPassBrdrPnl);
        employeeDashboardResetPassBrdrPnl.setLayout(employeeDashboardResetPassBrdrPnlLayout);
        employeeDashboardResetPassBrdrPnlLayout.setHorizontalGroup(
            employeeDashboardResetPassBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeeDashboardResetPassBrdrPnlLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(employeeDashboardPassBrdrPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, employeeDashboardResetPassBrdrPnlLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(employeeDashboardResetPassPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        employeeDashboardResetPassBrdrPnlLayout.setVerticalGroup(
            employeeDashboardResetPassBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeeDashboardResetPassBrdrPnlLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(employeeDashboardResetPassPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(employeeDashboardPassBrdrPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        employeeDashboardResetPassPnl.getAccessibleContext().setAccessibleName("employeeDashboardResetPassPnl");
        employeeDashboardPassBrdrPnl.getAccessibleContext().setAccessibleName("employeeDashboardPassBrdrPnl");

        employeeDashboardTimeOutBtn.setBackground(new java.awt.Color(239, 68, 68));
        employeeDashboardTimeOutBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        employeeDashboardTimeOutBtn.setForeground(new java.awt.Color(255, 255, 255));
        employeeDashboardTimeOutBtn.setText("Time Out");
        employeeDashboardTimeOutBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        employeeDashboardTimeOutBtn.addActionListener(this::employeeDashboardTimeOutBtnActionPerformed);

        employeeDashboardTimeInBtn.setBackground(new java.awt.Color(34, 197, 94));
        employeeDashboardTimeInBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        employeeDashboardTimeInBtn.setForeground(new java.awt.Color(255, 255, 255));
        employeeDashboardTimeInBtn.setText("Time In");
        employeeDashboardTimeInBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        employeeDashboardTimeInBtn.addActionListener(this::employeeDashboardTimeInBtnActionPerformed);

        employeeDashboardAttLogsBrdrPnl.setBackground(new java.awt.Color(146, 192, 253));
        employeeDashboardAttLogsBrdrPnl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 2, true));

        employeeDashboardAttLogsTbl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        employeeDashboardAttLogsTbl.setForeground(new java.awt.Color(30, 42, 56));
        employeeDashboardAttLogsTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Date", "Log In", "Log Out", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        employeeDashboardAttLogsTbl.setGridColor(new java.awt.Color(178, 178, 178));
        employeeDashboardAttLogsTbl.setSelectionForeground(new java.awt.Color(30, 42, 56));
        employeeDashboardAttLogsBrdrScrlPnl.setViewportView(employeeDashboardAttLogsTbl);
        employeeDashboardAttLogsTbl.getAccessibleContext().setAccessibleName("employeeDashboardAttLogsTbl");

        employeeDashboardAttLogsPnl.setBackground(new java.awt.Color(30, 58, 138));
        employeeDashboardAttLogsPnl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        employeeDashboardAttLogsPnl.setForeground(new java.awt.Color(30, 58, 138));
        employeeDashboardAttLogsPnl.setPreferredSize(new java.awt.Dimension(126, 40));

        employeeDashboardAttLogsLbl.setBackground(new java.awt.Color(255, 255, 255));
        employeeDashboardAttLogsLbl.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        employeeDashboardAttLogsLbl.setForeground(new java.awt.Color(255, 255, 255));
        employeeDashboardAttLogsLbl.setText("Attendance Logs");
        employeeDashboardAttLogsLbl.setToolTipText("");

        javax.swing.GroupLayout employeeDashboardAttLogsPnlLayout = new javax.swing.GroupLayout(employeeDashboardAttLogsPnl);
        employeeDashboardAttLogsPnl.setLayout(employeeDashboardAttLogsPnlLayout);
        employeeDashboardAttLogsPnlLayout.setHorizontalGroup(
            employeeDashboardAttLogsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeeDashboardAttLogsPnlLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(employeeDashboardAttLogsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        employeeDashboardAttLogsPnlLayout.setVerticalGroup(
            employeeDashboardAttLogsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(employeeDashboardAttLogsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        employeeDashboardAttLogsLbl.getAccessibleContext().setAccessibleName("employeeDashboardAttLogsLbl");

        javax.swing.GroupLayout employeeDashboardAttLogsBrdrPnlLayout = new javax.swing.GroupLayout(employeeDashboardAttLogsBrdrPnl);
        employeeDashboardAttLogsBrdrPnl.setLayout(employeeDashboardAttLogsBrdrPnlLayout);
        employeeDashboardAttLogsBrdrPnlLayout.setHorizontalGroup(
            employeeDashboardAttLogsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeeDashboardAttLogsBrdrPnlLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(employeeDashboardAttLogsBrdrScrlPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, employeeDashboardAttLogsBrdrPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(employeeDashboardAttLogsPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118))
        );
        employeeDashboardAttLogsBrdrPnlLayout.setVerticalGroup(
            employeeDashboardAttLogsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeeDashboardAttLogsBrdrPnlLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(employeeDashboardAttLogsPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(employeeDashboardAttLogsBrdrScrlPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );

        employeeDashboardAttLogsBrdrScrlPnl.getAccessibleContext().setAccessibleName("employeeDashboardAttLogsBrdrScrlPnl");
        employeeDashboardAttLogsPnl.getAccessibleContext().setAccessibleName("employeeDashboardAttLogsPnl");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(employeeDashboardSidebarPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(employeeDashboardResetPassBrdrPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(employeeDashboardAttLogsBrdrPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(employeeDashboardEDetailsBrdrPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(hrEDetailsEDetailsPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(359, 359, 359)
                        .addComponent(employeeDashboardTimeInBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(employeeDashboardTimeOutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(employeeDashboardSidebarPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(hrEDetailsEDetailsPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(employeeDashboardTimeOutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(employeeDashboardTimeInBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12)
                        .addComponent(employeeDashboardEDetailsBrdrPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(employeeDashboardResetPassBrdrPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(employeeDashboardAttLogsBrdrPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        employeeDashboardSidebarPnl.getAccessibleContext().setAccessibleName("employeeDashboardSidebarPnl");
        employeeDashboardEDetailsBrdrPnl.getAccessibleContext().setAccessibleName("employeeDashboardEDetailsBrdrPnl");
        employeeDashboardResetPassBrdrPnl.getAccessibleContext().setAccessibleName("employeeDashboardResetPassBrdrPnl");
        employeeDashboardAttLogsBrdrPnl.getAccessibleContext().setAccessibleName("employeeDashboardAttLogsBrdrPnl");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void employeeDashboardDashboardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeDashboardDashboardBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeDashboardDashboardBtnActionPerformed

    private void employeeDashboardMainDashboardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeDashboardMainDashboardBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new MainDashboardUI().setVisible(true);
    }//GEN-LAST:event_employeeDashboardMainDashboardBtnActionPerformed

    private void employeeDashboardENumberFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeDashboardENumberFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeDashboardENumberFldActionPerformed

    private void employeeDashboardAddressFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeDashboardAddressFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeDashboardAddressFldActionPerformed

    private void employeeDashboardLNameFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeDashboardLNameFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeDashboardLNameFldActionPerformed

    private void employeeDashboardPositionFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeDashboardPositionFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeDashboardPositionFldActionPerformed

    private void employeeDashboardBasicSalaryFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeDashboardBasicSalaryFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeDashboardBasicSalaryFldActionPerformed

    private void employeeDashboardPhnAllowanceFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeDashboardPhnAllowanceFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeDashboardPhnAllowanceFldActionPerformed

    private void employeeDashboardSSSFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeDashboardSSSFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeDashboardSSSFldActionPerformed

    private void employeeDashboardPhilHealthFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeDashboardPhilHealthFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeDashboardPhilHealthFldActionPerformed

    private void employeeDashboardFNameFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeDashboardFNameFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeDashboardFNameFldActionPerformed

    private void employeeDashboardPhnNumberFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeDashboardPhnNumberFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeDashboardPhnNumberFldActionPerformed

    private void employeeDashboardISupervisorFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeDashboardISupervisorFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeDashboardISupervisorFldActionPerformed

    private void employeeDashboardRiceSubsidyFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeDashboardRiceSubsidyFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeDashboardRiceSubsidyFldActionPerformed

    private void employeeDashboardCltAllowanceFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeDashboardCltAllowanceFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeDashboardCltAllowanceFldActionPerformed

    private void employeeDashboardTINFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeDashboardTINFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeDashboardTINFldActionPerformed

    private void employeeDashboardPagIbigFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeDashboardPagIbigFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeDashboardPagIbigFldActionPerformed

    private void employeeDashboardTimeOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeDashboardTimeOutBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeDashboardTimeOutBtnActionPerformed

    private void employeeDashboardTimeInBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeDashboardTimeInBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeDashboardTimeInBtnActionPerformed

    private void employeeDashboardCurrPassFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeDashboardCurrPassFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeDashboardCurrPassFldActionPerformed

    private void employeeDashboardNewPassFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeDashboardNewPassFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeDashboardNewPassFldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EmployeeDashboardUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField employeeDashboardAddressFld;
    private javax.swing.JLabel employeeDashboardAddressLbl;
    private javax.swing.JPanel employeeDashboardAttLogsBrdrPnl;
    private javax.swing.JScrollPane employeeDashboardAttLogsBrdrScrlPnl;
    private javax.swing.JLabel employeeDashboardAttLogsLbl;
    private javax.swing.JPanel employeeDashboardAttLogsPnl;
    private javax.swing.JTable employeeDashboardAttLogsTbl;
    private javax.swing.JTextField employeeDashboardBasicSalaryFld;
    private javax.swing.JLabel employeeDashboardBasicSalaryLbl;
    private com.toedter.calendar.JDateChooser employeeDashboardBirthdayDtChsr;
    private javax.swing.JLabel employeeDashboardBirthdayLbl;
    private javax.swing.JTextField employeeDashboardCltAllowanceFld;
    private javax.swing.JLabel employeeDashboardCltAllowanceLbl;
    private javax.swing.JButton employeeDashboardConfirmBtn;
    private javax.swing.JTextField employeeDashboardCurrPassFld;
    private javax.swing.JLabel employeeDashboardCurrPassLbl;
    private javax.swing.JButton employeeDashboardDashboardBtn;
    private javax.swing.JPanel employeeDashboardEDetailsBrdrPnl;
    private javax.swing.JTextField employeeDashboardENumberFld;
    private javax.swing.JLabel employeeDashboardENumberLbl;
    private javax.swing.JTextField employeeDashboardFNameFld;
    private javax.swing.JLabel employeeDashboardFNameLbl;
    private javax.swing.JTextField employeeDashboardISupervisorFld;
    private javax.swing.JLabel employeeDashboardISupervisorLbl;
    private javax.swing.JTextField employeeDashboardLNameFld;
    private javax.swing.JLabel employeeDashboardLNameLbl;
    private javax.swing.JButton employeeDashboardMainDashboardBtn;
    private javax.swing.JTextField employeeDashboardNewPassFld;
    private javax.swing.JLabel employeeDashboardNewPassLbl;
    private javax.swing.JTextField employeeDashboardPagIbigFld;
    private javax.swing.JLabel employeeDashboardPagIbigLbl;
    private javax.swing.JPanel employeeDashboardPassBrdrPnl;
    private javax.swing.JTextField employeeDashboardPhilHealthFld;
    private javax.swing.JLabel employeeDashboardPhilHealthLbl;
    private javax.swing.JTextField employeeDashboardPhnAllowanceFld;
    private javax.swing.JLabel employeeDashboardPhnAllowanceLbl;
    private javax.swing.JTextField employeeDashboardPhnNumberFld;
    private javax.swing.JLabel employeeDashboardPhnNumberLbl;
    private javax.swing.JTextField employeeDashboardPositionFld;
    private javax.swing.JLabel employeeDashboardPositionLbl;
    private javax.swing.JLabel employeeDashboardProfileLbl;
    private javax.swing.JPanel employeeDashboardResetPassBrdrPnl;
    private javax.swing.JLabel employeeDashboardResetPassLbl;
    private javax.swing.JPanel employeeDashboardResetPassPnl;
    private javax.swing.JTextField employeeDashboardRiceSubsidyFld;
    private javax.swing.JLabel employeeDashboardRiceSubsidyLbl;
    private javax.swing.JTextField employeeDashboardSSSFld;
    private javax.swing.JLabel employeeDashboardSSSLbl;
    private javax.swing.JPanel employeeDashboardSidebarPnl;
    private javax.swing.JComboBox<String> employeeDashboardStatusCbx;
    private javax.swing.JLabel employeeDashboardStatusLbl;
    private javax.swing.JTextField employeeDashboardTINFld;
    private javax.swing.JLabel employeeDashboardTINLbl;
    private javax.swing.JButton employeeDashboardTimeInBtn;
    private javax.swing.JButton employeeDashboardTimeOutBtn;
    private javax.swing.JPanel hrEDetailsEDetailsPnl;
    private javax.swing.JLabel hrEDetailsMotorPHIconImgLbl;
    // End of variables declaration//GEN-END:variables
}
