/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.motorph.ui;

import com.motorph.model.AttendanceRecord;
import com.motorph.model.Employee;
import com.motorph.service.AttendanceService;
import com.motorph.service.EmployeeService;
import com.motorph.util.AppContext;
import com.motorph.util.Session;
import java.util.List;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Lenovo
 */
public class FinanceAttendanceLogsUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FinanceAttendanceLogsUI.class.getName());
    private AttendanceService attendanceService;
    private EmployeeService empService;
    private TableRowSorter<DefaultTableModel> sorter;
    /**
     * Creates new form FinanceDashboardFrame
     */
    public FinanceAttendanceLogsUI() {
        this.attendanceService = AppContext.getAttendanceService();
        this.empService = AppContext.getEmployeeService();
        initComponents();
        
        // Filter for table
        DefaultTableModel model = (DefaultTableModel) financeAttLogsAttLogsTbl.getModel();
        sorter = new TableRowSorter<>(model);
        financeAttLogsAttLogsTbl.setRowSorter(sorter);
        
        
        refreshAttendanceLogs();
    }
    
    private void refreshAttendanceLogs() {
                      
        List<AttendanceRecord> logs = attendanceService.getAllAttendance();

        // Most recent attendance should be shown first
        java.util.Collections.reverse(logs);

        DefaultTableModel model = (DefaultTableModel) financeAttLogsAttLogsTbl.getModel();
        model.setRowCount(0);

        for (AttendanceRecord log : logs) {

            Object[] row = {
                log.getEmployeeNumber(),
                log.getLastName() + ", " + log.getFirstName(),
                String.valueOf(log.getDate()),
                String.valueOf(log.getLogIn()),
                String.valueOf(log.getLogOut()),
                "GOODS :)"
            };

            model.addRow(row);
        }
    }
    
    
    
    private void performSearch() {
        System.out.println("EVENT TRIGGERD");
        String id = financeAttLogsEntENumberFld.getText().trim();
        
        if (id.isEmpty()) {
            
            System.out.println("1");
            sorter.setRowFilter(null);
        } else {
            sorter.setRowFilter(RowFilter.regexFilter("(?i)" + id, 0));
            
            System.out.println("2");
        }
    }

/**

/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        financeAttLogsSidebarPnl = new javax.swing.JPanel();
        financeAttLogsMainDashboardBtn = new javax.swing.JButton();
        financeAttLogsAttLogsBtn = new javax.swing.JButton();
        financeAttLogsMotorPHIconImgLbl = new javax.swing.JLabel();
        financeAttLogsSearchPnl = new javax.swing.JPanel();
        financeAttLogsEntENumberFld = new javax.swing.JTextField();
        financeAttLogsSearchIconImgLbl = new javax.swing.JLabel();
        financeAttLogsEDetailsPnl = new javax.swing.JPanel();
        financeAttLogsAttLogsBrdrPnl = new javax.swing.JPanel();
        financeAttLogsAttLogsScrlPnl = new javax.swing.JScrollPane();
        financeAttLogsAttLogsTbl = new javax.swing.JTable();
        financeAttLogsAttRecordsPnl = new javax.swing.JPanel();
        financeAttLogsAttRecordsLbl = new javax.swing.JLabel();
        financeAttLogsEditBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        financeAttLogsSidebarPnl.setBackground(new java.awt.Color(30, 58, 138));

        financeAttLogsMainDashboardBtn.setBackground(new java.awt.Color(30, 42, 56));
        financeAttLogsMainDashboardBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        financeAttLogsMainDashboardBtn.setForeground(new java.awt.Color(255, 255, 255));
        financeAttLogsMainDashboardBtn.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        financeAttLogsMainDashboardBtn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        financeAttLogsMainDashboardBtn.setLabel("Main Dashboard");
        financeAttLogsMainDashboardBtn.addActionListener(this::financeAttLogsMainDashboardBtnActionPerformed);

        financeAttLogsAttLogsBtn.setBackground(new java.awt.Color(30, 42, 56));
        financeAttLogsAttLogsBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        financeAttLogsAttLogsBtn.setForeground(new java.awt.Color(255, 255, 255));
        financeAttLogsAttLogsBtn.setText("Attendance Logs");
        financeAttLogsAttLogsBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        financeAttLogsAttLogsBtn.addActionListener(this::financeAttLogsAttLogsBtnActionPerformed);

        financeAttLogsMotorPHIconImgLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/motorph/img/MotorPHIconImg.png"))); // NOI18N

        javax.swing.GroupLayout financeAttLogsSidebarPnlLayout = new javax.swing.GroupLayout(financeAttLogsSidebarPnl);
        financeAttLogsSidebarPnl.setLayout(financeAttLogsSidebarPnlLayout);
        financeAttLogsSidebarPnlLayout.setHorizontalGroup(
            financeAttLogsSidebarPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(financeAttLogsSidebarPnlLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(financeAttLogsMainDashboardBtn))
            .addGroup(financeAttLogsSidebarPnlLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(financeAttLogsSidebarPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(financeAttLogsSidebarPnlLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(financeAttLogsMotorPHIconImgLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(financeAttLogsAttLogsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        financeAttLogsSidebarPnlLayout.setVerticalGroup(
            financeAttLogsSidebarPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(financeAttLogsSidebarPnlLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(financeAttLogsSidebarPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(financeAttLogsMotorPHIconImgLbl)
                    .addGroup(financeAttLogsSidebarPnlLayout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(financeAttLogsAttLogsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 420, Short.MAX_VALUE)
                .addComponent(financeAttLogsMainDashboardBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        financeAttLogsMainDashboardBtn.getAccessibleContext().setAccessibleName("financeAttLogsMainDashboardBtn");
        financeAttLogsAttLogsBtn.getAccessibleContext().setAccessibleName("financeAttLogsAttLogsBtn");
        financeAttLogsMotorPHIconImgLbl.getAccessibleContext().setAccessibleName("financeAttLogsMotorPHIconImgLbl");

        financeAttLogsSearchPnl.setBackground(new java.awt.Color(146, 192, 253));
        financeAttLogsSearchPnl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        financeAttLogsSearchPnl.setForeground(new java.awt.Color(146, 192, 253));
        financeAttLogsSearchPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        financeAttLogsEntENumberFld.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        financeAttLogsEntENumberFld.setForeground(new java.awt.Color(31, 41, 55));
        financeAttLogsEntENumberFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        financeAttLogsEntENumberFld.setCaretColor(new java.awt.Color(31, 41, 55));
        financeAttLogsEntENumberFld.setDisabledTextColor(new java.awt.Color(31, 41, 55));
        financeAttLogsEntENumberFld.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                financeAttLogsEntENumberFldMouseClicked(evt);
            }
        });
        financeAttLogsEntENumberFld.addActionListener(this::financeAttLogsEntENumberFldActionPerformed);
        financeAttLogsSearchPnl.add(financeAttLogsEntENumberFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 7, 170, 31));
        financeAttLogsEntENumberFld.getAccessibleContext().setAccessibleName("financeAttLogsEntENumberFld");

        financeAttLogsSearchIconImgLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/motorph/img/SearchIconImg.png"))); // NOI18N
        financeAttLogsSearchPnl.add(financeAttLogsSearchIconImgLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, -10, 60, 60));
        financeAttLogsSearchIconImgLbl.getAccessibleContext().setAccessibleName("financeAttLogsSearchIconImgLbl");

        financeAttLogsEDetailsPnl.setBackground(new java.awt.Color(30, 58, 138));
        financeAttLogsEDetailsPnl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        financeAttLogsEDetailsPnl.setForeground(new java.awt.Color(30, 58, 138));
        financeAttLogsEDetailsPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        financeAttLogsAttLogsBrdrPnl.setBackground(new java.awt.Color(146, 192, 253));
        financeAttLogsAttLogsBrdrPnl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 2, true));

        financeAttLogsAttLogsScrlPnl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));

        financeAttLogsAttLogsTbl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        financeAttLogsAttLogsTbl.setForeground(new java.awt.Color(30, 42, 56));
        financeAttLogsAttLogsTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Employee #", "Employee Name", "Date", "Log In", "Log Out", "Remarks"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        financeAttLogsAttLogsTbl.setGridColor(new java.awt.Color(178, 178, 178));
        financeAttLogsAttLogsTbl.setSelectionForeground(new java.awt.Color(30, 42, 56));
        financeAttLogsAttLogsScrlPnl.setViewportView(financeAttLogsAttLogsTbl);
        financeAttLogsAttLogsTbl.getAccessibleContext().setAccessibleName("financeAttLogsAttLogsTbl");

        javax.swing.GroupLayout financeAttLogsAttLogsBrdrPnlLayout = new javax.swing.GroupLayout(financeAttLogsAttLogsBrdrPnl);
        financeAttLogsAttLogsBrdrPnl.setLayout(financeAttLogsAttLogsBrdrPnlLayout);
        financeAttLogsAttLogsBrdrPnlLayout.setHorizontalGroup(
            financeAttLogsAttLogsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(financeAttLogsAttLogsBrdrPnlLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(financeAttLogsAttLogsScrlPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        financeAttLogsAttLogsBrdrPnlLayout.setVerticalGroup(
            financeAttLogsAttLogsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(financeAttLogsAttLogsBrdrPnlLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(financeAttLogsAttLogsScrlPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        financeAttLogsAttLogsScrlPnl.getAccessibleContext().setAccessibleName("financeAttLogsAttLogsScrlPnl");

        financeAttLogsAttRecordsPnl.setBackground(new java.awt.Color(30, 58, 138));
        financeAttLogsAttRecordsPnl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        financeAttLogsAttRecordsPnl.setForeground(new java.awt.Color(30, 58, 138));
        financeAttLogsAttRecordsPnl.setPreferredSize(new java.awt.Dimension(126, 40));

        financeAttLogsAttRecordsLbl.setBackground(new java.awt.Color(255, 255, 255));
        financeAttLogsAttRecordsLbl.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        financeAttLogsAttRecordsLbl.setForeground(new java.awt.Color(255, 255, 255));
        financeAttLogsAttRecordsLbl.setText(" Attendance Records");
        financeAttLogsAttRecordsLbl.setToolTipText("");

        javax.swing.GroupLayout financeAttLogsAttRecordsPnlLayout = new javax.swing.GroupLayout(financeAttLogsAttRecordsPnl);
        financeAttLogsAttRecordsPnl.setLayout(financeAttLogsAttRecordsPnlLayout);
        financeAttLogsAttRecordsPnlLayout.setHorizontalGroup(
            financeAttLogsAttRecordsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, financeAttLogsAttRecordsPnlLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(financeAttLogsAttRecordsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        financeAttLogsAttRecordsPnlLayout.setVerticalGroup(
            financeAttLogsAttRecordsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(financeAttLogsAttRecordsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        financeAttLogsAttRecordsLbl.getAccessibleContext().setAccessibleName("financeAttLogsAttLogsLbl");

        financeAttLogsEditBtn.setBackground(new java.awt.Color(59, 130, 246));
        financeAttLogsEditBtn.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        financeAttLogsEditBtn.setForeground(new java.awt.Color(255, 255, 255));
        financeAttLogsEditBtn.setText("Edit");
        financeAttLogsEditBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        financeAttLogsEditBtn.addActionListener(this::financeAttLogsEditBtnActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(financeAttLogsSidebarPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(financeAttLogsAttLogsBrdrPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(financeAttLogsAttRecordsPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(financeAttLogsEDetailsPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(financeAttLogsSearchPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(financeAttLogsEditBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(financeAttLogsEDetailsPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(financeAttLogsSearchPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(financeAttLogsAttRecordsPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(financeAttLogsAttLogsBrdrPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(financeAttLogsEditBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
            .addComponent(financeAttLogsSidebarPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        financeAttLogsSidebarPnl.getAccessibleContext().setAccessibleName("financeAttLogsSidebarPnl");
        financeAttLogsSearchPnl.getAccessibleContext().setAccessibleName("financeAttLogsSearchPnl");
        financeAttLogsEDetailsPnl.getAccessibleContext().setAccessibleName("financeAttLogsEDetailsPnl");
        financeAttLogsAttLogsBrdrPnl.getAccessibleContext().setAccessibleName("financeAttLogsAttLogsBrdrPnl");
        financeAttLogsAttRecordsPnl.getAccessibleContext().setAccessibleName("financeAttLogsAttLogsPnl");
        financeAttLogsEditBtn.getAccessibleContext().setAccessibleName("financeAttLogsEditBtn");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void financeAttLogsEditBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_financeAttLogsEditBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_financeAttLogsEditBtnActionPerformed

    private void financeAttLogsMainDashboardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_financeAttLogsMainDashboardBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new MainAdminDashboardUI().setVisible(true);
    }//GEN-LAST:event_financeAttLogsMainDashboardBtnActionPerformed

    private void financeAttLogsEntENumberFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_financeAttLogsEntENumberFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_financeAttLogsEntENumberFldActionPerformed

    private void financeAttLogsAttLogsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_financeAttLogsAttLogsBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_financeAttLogsAttLogsBtnActionPerformed

    private void financeAttLogsEntENumberFldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_financeAttLogsEntENumberFldMouseClicked
        // TODO add your handling code here:
        
        performSearch();
        
        
    }//GEN-LAST:event_financeAttLogsEntENumberFldMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FinanceAttendanceLogsUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel financeAttLogsAttLogsBrdrPnl;
    private javax.swing.JButton financeAttLogsAttLogsBtn;
    private javax.swing.JScrollPane financeAttLogsAttLogsScrlPnl;
    private javax.swing.JTable financeAttLogsAttLogsTbl;
    private javax.swing.JLabel financeAttLogsAttRecordsLbl;
    private javax.swing.JPanel financeAttLogsAttRecordsPnl;
    private javax.swing.JPanel financeAttLogsEDetailsPnl;
    private javax.swing.JButton financeAttLogsEditBtn;
    private javax.swing.JTextField financeAttLogsEntENumberFld;
    private javax.swing.JButton financeAttLogsMainDashboardBtn;
    private javax.swing.JLabel financeAttLogsMotorPHIconImgLbl;
    private javax.swing.JLabel financeAttLogsSearchIconImgLbl;
    private javax.swing.JPanel financeAttLogsSearchPnl;
    private javax.swing.JPanel financeAttLogsSidebarPnl;
    // End of variables declaration//GEN-END:variables
}
