/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.motorph.ui;

import com.motorph.model.Employee;
import com.motorph.util.DateUtils;

/**
 *
 * @author Lenovo
 */
public class HREditEmployeeUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HREditEmployeeUI.class.getName());

    /**
     * Creates new form HREditEmployeeFrame
     */
    public HREditEmployeeUI(Employee emp) {
        initComponents();
        
        populateFields(emp);
    }
    
    private void populateFields(Employee emp) {
        hrEditEmployeeENumberFld.setText(emp.getEmployeeNumber());
        hrEditEmployeeFNameFld.setText(emp.getFirstName());
        hrEditEmployeeLNameFld.setText(emp.getLastName());
        hrEditEmployeeBirthdayFld.setText(DateUtils.dateToString(emp.getBirthday()));
        hrEditEmployeeAddressFld.setText(emp.getAddress());
        hrEditEmployeePhnNumberFld.setText(emp.getPhoneNumber());
        hrEditEmployeeSSSFld.setText(emp.getSSSNumber());
        hrEditEmployeePhilHealthFld.setText(emp.getPhilhealthNumber());
        hrEditEmployeeTINFld.setText(emp.getTIN());
        hrEditEmployeePagIbigFld.setText(emp.getPagIbigNumber());
        //statusField.setText(emp.getStatus());
        hrEditEmployeePositionFld.setText(emp.getPosition());
        hrEditEmployeeISupervisorFld.setText(emp.getImmediateSupervisor());
        hrEditEmployeeBasicSalaryFld.setText(String.valueOf(emp.getBasicSalary()));
        hrEditEmployeeRiceSubsidyFld.setText(String.valueOf(emp.getRiceSubsidy()));
        hrEditEmployeePhnAllowanceFld.setText(String.valueOf(emp.getPhoneAllowance()));
        hrEditEmployeeCltAllowanceFld.setText(String.valueOf(emp.getClothingAllowance()));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hrEditEmployeeSidebarPnl = new javax.swing.JPanel();
        hrEditEmployeeEDetailsBtn = new javax.swing.JButton();
        hrEditEmployeeEditEDetailsBtn = new javax.swing.JButton();
        hrEditEmployeeAEDetailsBtn = new javax.swing.JButton();
        hrEditEmployeeMainDashboardBtn = new javax.swing.JButton();
        hrEditEmployeeMotorPHIconImgLbl = new javax.swing.JLabel();
        hrEditEmployeeUpdateBtn = new javax.swing.JButton();
        hrEditEmployeeEditEDetailsPnl = new javax.swing.JPanel();
        hrEditEmployeeEditEDetailsLbl = new javax.swing.JLabel();
        hrEditEmployeeEDetailsBrdrPnl = new javax.swing.JPanel();
        hrEditEmployeeENumberLbl = new javax.swing.JLabel();
        hrEditEmployeeLNameLbl = new javax.swing.JLabel();
        hrEditEmployeeAddressLbl = new javax.swing.JLabel();
        hrEditEmployeeBirthdayLbl = new javax.swing.JLabel();
        hrEditEmployeePositionLbl = new javax.swing.JLabel();
        hrEditEmployeeBasicSalaryLbl = new javax.swing.JLabel();
        hrEditEmployeeSSSLbl = new javax.swing.JLabel();
        hrEditEmployeePhilHealthLbl = new javax.swing.JLabel();
        hrEditEmployeeCltAllowanceLbl = new javax.swing.JLabel();
        hrEditEmployeeFNameLbl = new javax.swing.JLabel();
        hrEditEmployeePhnNumberLbl = new javax.swing.JLabel();
        hrEditEmployeeISupervisorLbl = new javax.swing.JLabel();
        hrEditEmployeeRiceSubsidyLbl = new javax.swing.JLabel();
        hrEditEmployeeTINLbl = new javax.swing.JLabel();
        hrEditEmployeePagIbigLbl = new javax.swing.JLabel();
        hrEditEmployeePhnAllowanceLbl = new javax.swing.JLabel();
        hrEditEmployeeLNameFld = new javax.swing.JTextField();
        hrEditEmployeeAddressFld = new javax.swing.JTextField();
        hrEditEmployeeBirthdayFld = new javax.swing.JTextField();
        hrEditEmployeePositionFld = new javax.swing.JTextField();
        hrEditEmployeeBasicSalaryFld = new javax.swing.JTextField();
        hrEditEmployeePhnAllowanceFld = new javax.swing.JTextField();
        hrEditEmployeeSSSFld = new javax.swing.JTextField();
        hrEditEmployeePhilHealthFld = new javax.swing.JTextField();
        hrEditEmployeeENumberFld = new javax.swing.JTextField();
        hrEditEmployeeISupervisorFld = new javax.swing.JTextField();
        hrEditEmployeeRiceSubsidyFld = new javax.swing.JTextField();
        hrEditEmployeeTINFld = new javax.swing.JTextField();
        hrEditEmployeePagIbigFld = new javax.swing.JTextField();
        hrEditEmployeePhnNumberFld = new javax.swing.JTextField();
        hrEditEmployeeFNameFld = new javax.swing.JTextField();
        hrEditEmployeeStatusCbx = new javax.swing.JComboBox<>();
        hrEditEmployeeStatusLbl = new javax.swing.JLabel();
        hrEditEmployeeCltAllowanceFld = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        hrEditEmployeeSidebarPnl.setBackground(new java.awt.Color(30, 58, 138));
        hrEditEmployeeSidebarPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hrEditEmployeeEDetailsBtn.setBackground(new java.awt.Color(30, 42, 56));
        hrEditEmployeeEDetailsBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        hrEditEmployeeEDetailsBtn.setForeground(new java.awt.Color(255, 255, 255));
        hrEditEmployeeEDetailsBtn.setText("Employee Details");
        hrEditEmployeeEDetailsBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        hrEditEmployeeEDetailsBtn.addActionListener(this::hrEditEmployeeEDetailsBtnActionPerformed);
        hrEditEmployeeSidebarPnl.add(hrEditEmployeeEDetailsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 199, 216, 39));
        hrEditEmployeeEDetailsBtn.getAccessibleContext().setAccessibleName("hrEditEmployeeEDetailsBtn");

        hrEditEmployeeEditEDetailsBtn.setBackground(new java.awt.Color(30, 42, 56));
        hrEditEmployeeEditEDetailsBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        hrEditEmployeeEditEDetailsBtn.setForeground(new java.awt.Color(255, 255, 255));
        hrEditEmployeeEditEDetailsBtn.setText("Edit Employee Details");
        hrEditEmployeeEditEDetailsBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        hrEditEmployeeEditEDetailsBtn.addActionListener(this::hrEditEmployeeEditEDetailsBtnActionPerformed);
        hrEditEmployeeSidebarPnl.add(hrEditEmployeeEditEDetailsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 250, 216, 39));
        hrEditEmployeeEditEDetailsBtn.getAccessibleContext().setAccessibleName("hrEditEmployeeEditEDetailsBtn");

        hrEditEmployeeAEDetailsBtn.setBackground(new java.awt.Color(30, 42, 56));
        hrEditEmployeeAEDetailsBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        hrEditEmployeeAEDetailsBtn.setForeground(new java.awt.Color(255, 255, 255));
        hrEditEmployeeAEDetailsBtn.setText("Add Employee Details");
        hrEditEmployeeAEDetailsBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        hrEditEmployeeAEDetailsBtn.addActionListener(this::hrEditEmployeeAEDetailsBtnActionPerformed);
        hrEditEmployeeSidebarPnl.add(hrEditEmployeeAEDetailsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 301, -1, 39));
        hrEditEmployeeAEDetailsBtn.getAccessibleContext().setAccessibleName("hrEditEmployeeAEDetailsBtn");

        hrEditEmployeeMainDashboardBtn.setBackground(new java.awt.Color(30, 42, 56));
        hrEditEmployeeMainDashboardBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        hrEditEmployeeMainDashboardBtn.setForeground(new java.awt.Color(255, 255, 255));
        hrEditEmployeeMainDashboardBtn.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        hrEditEmployeeMainDashboardBtn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        hrEditEmployeeMainDashboardBtn.setLabel("Main Dashboard");
        hrEditEmployeeMainDashboardBtn.addActionListener(this::hrEditEmployeeMainDashboardBtnActionPerformed);
        hrEditEmployeeSidebarPnl.add(hrEditEmployeeMainDashboardBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 647, -1, 39));
        hrEditEmployeeMainDashboardBtn.getAccessibleContext().setAccessibleName("hrEditEmployeeMainDashboardBtn");
        hrEditEmployeeMainDashboardBtn.getAccessibleContext().setAccessibleDescription("");

        hrEditEmployeeMotorPHIconImgLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/motorph/img/MotorPHIconImg.png"))); // NOI18N
        hrEditEmployeeSidebarPnl.add(hrEditEmployeeMotorPHIconImgLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 180, -1));
        hrEditEmployeeMotorPHIconImgLbl.getAccessibleContext().setAccessibleName("hrEditEmployeeMotorPHIconImgLbl");

        hrEditEmployeeUpdateBtn.setBackground(new java.awt.Color(34, 197, 94));
        hrEditEmployeeUpdateBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        hrEditEmployeeUpdateBtn.setForeground(new java.awt.Color(255, 255, 255));
        hrEditEmployeeUpdateBtn.setText("Update");
        hrEditEmployeeUpdateBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        hrEditEmployeeUpdateBtn.addActionListener(this::hrEditEmployeeUpdateBtnActionPerformed);

        hrEditEmployeeEditEDetailsPnl.setBackground(new java.awt.Color(30, 58, 138));
        hrEditEmployeeEditEDetailsPnl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        hrEditEmployeeEditEDetailsPnl.setForeground(new java.awt.Color(30, 58, 138));
        hrEditEmployeeEditEDetailsPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hrEditEmployeeEditEDetailsLbl.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        hrEditEmployeeEditEDetailsLbl.setForeground(new java.awt.Color(255, 255, 255));
        hrEditEmployeeEditEDetailsLbl.setText("Edit Employee Details");
        hrEditEmployeeEditEDetailsPnl.add(hrEditEmployeeEditEDetailsLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 1, 266, 46));
        hrEditEmployeeEditEDetailsLbl.getAccessibleContext().setAccessibleName("hrEditEmployeeEditEDetailsLbl");

        hrEditEmployeeEDetailsBrdrPnl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(31, 41, 55), 2, true));
        hrEditEmployeeEDetailsBrdrPnl.setForeground(new java.awt.Color(31, 41, 55));
        hrEditEmployeeEDetailsBrdrPnl.setFocusable(false);
        hrEditEmployeeEDetailsBrdrPnl.setPreferredSize(new java.awt.Dimension(700, 469));
        hrEditEmployeeEDetailsBrdrPnl.setRequestFocusEnabled(false);

        hrEditEmployeeENumberLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        hrEditEmployeeENumberLbl.setForeground(new java.awt.Color(31, 41, 55));
        hrEditEmployeeENumberLbl.setText("Employee #");

        hrEditEmployeeLNameLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        hrEditEmployeeLNameLbl.setForeground(new java.awt.Color(31, 41, 55));
        hrEditEmployeeLNameLbl.setText("Last Name");

        hrEditEmployeeAddressLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        hrEditEmployeeAddressLbl.setForeground(new java.awt.Color(31, 41, 55));
        hrEditEmployeeAddressLbl.setText("Address");

        hrEditEmployeeBirthdayLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        hrEditEmployeeBirthdayLbl.setForeground(new java.awt.Color(31, 41, 55));
        hrEditEmployeeBirthdayLbl.setText("Birthday");

        hrEditEmployeePositionLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        hrEditEmployeePositionLbl.setForeground(new java.awt.Color(31, 41, 55));
        hrEditEmployeePositionLbl.setText("Position");

        hrEditEmployeeBasicSalaryLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        hrEditEmployeeBasicSalaryLbl.setForeground(new java.awt.Color(31, 41, 55));
        hrEditEmployeeBasicSalaryLbl.setText("Basic Salary");

        hrEditEmployeeSSSLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        hrEditEmployeeSSSLbl.setForeground(new java.awt.Color(31, 41, 55));
        hrEditEmployeeSSSLbl.setText("SSS");

        hrEditEmployeePhilHealthLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        hrEditEmployeePhilHealthLbl.setForeground(new java.awt.Color(31, 41, 55));
        hrEditEmployeePhilHealthLbl.setText("PhilHealth");

        hrEditEmployeeCltAllowanceLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        hrEditEmployeeCltAllowanceLbl.setForeground(new java.awt.Color(31, 41, 55));
        hrEditEmployeeCltAllowanceLbl.setText("Clothing Allowance");

        hrEditEmployeeFNameLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        hrEditEmployeeFNameLbl.setForeground(new java.awt.Color(31, 41, 55));
        hrEditEmployeeFNameLbl.setText("First Name");

        hrEditEmployeePhnNumberLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        hrEditEmployeePhnNumberLbl.setForeground(new java.awt.Color(31, 41, 55));
        hrEditEmployeePhnNumberLbl.setText("Phone Number");

        hrEditEmployeeISupervisorLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        hrEditEmployeeISupervisorLbl.setForeground(new java.awt.Color(31, 41, 55));
        hrEditEmployeeISupervisorLbl.setText("Immediate Supervisor");

        hrEditEmployeeRiceSubsidyLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        hrEditEmployeeRiceSubsidyLbl.setForeground(new java.awt.Color(31, 41, 55));
        hrEditEmployeeRiceSubsidyLbl.setText("Rice Subsidy");

        hrEditEmployeeTINLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        hrEditEmployeeTINLbl.setForeground(new java.awt.Color(31, 41, 55));
        hrEditEmployeeTINLbl.setText("TIN");

        hrEditEmployeePagIbigLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        hrEditEmployeePagIbigLbl.setForeground(new java.awt.Color(31, 41, 55));
        hrEditEmployeePagIbigLbl.setText("Pag-Ibig");

        hrEditEmployeePhnAllowanceLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        hrEditEmployeePhnAllowanceLbl.setForeground(new java.awt.Color(31, 41, 55));
        hrEditEmployeePhnAllowanceLbl.setText("Phone Allowance");

        hrEditEmployeeLNameFld.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        hrEditEmployeeLNameFld.setForeground(new java.awt.Color(31, 41, 55));
        hrEditEmployeeLNameFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        hrEditEmployeeLNameFld.addActionListener(this::hrEditEmployeeLNameFldActionPerformed);

        hrEditEmployeeAddressFld.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        hrEditEmployeeAddressFld.setForeground(new java.awt.Color(31, 41, 55));
        hrEditEmployeeAddressFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        hrEditEmployeeAddressFld.addActionListener(this::hrEditEmployeeAddressFldActionPerformed);

        hrEditEmployeeBirthdayFld.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        hrEditEmployeeBirthdayFld.setForeground(new java.awt.Color(31, 41, 55));
        hrEditEmployeeBirthdayFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        hrEditEmployeeBirthdayFld.addActionListener(this::hrEditEmployeeBirthdayFldActionPerformed);

        hrEditEmployeePositionFld.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        hrEditEmployeePositionFld.setForeground(new java.awt.Color(31, 41, 55));
        hrEditEmployeePositionFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        hrEditEmployeePositionFld.addActionListener(this::hrEditEmployeePositionFldActionPerformed);

        hrEditEmployeeBasicSalaryFld.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        hrEditEmployeeBasicSalaryFld.setForeground(new java.awt.Color(31, 41, 55));
        hrEditEmployeeBasicSalaryFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        hrEditEmployeeBasicSalaryFld.addActionListener(this::hrEditEmployeeBasicSalaryFldActionPerformed);

        hrEditEmployeePhnAllowanceFld.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        hrEditEmployeePhnAllowanceFld.setForeground(new java.awt.Color(31, 41, 55));
        hrEditEmployeePhnAllowanceFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        hrEditEmployeePhnAllowanceFld.addActionListener(this::hrEditEmployeePhnAllowanceFldActionPerformed);

        hrEditEmployeeSSSFld.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        hrEditEmployeeSSSFld.setForeground(new java.awt.Color(31, 41, 55));
        hrEditEmployeeSSSFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        hrEditEmployeeSSSFld.addActionListener(this::hrEditEmployeeSSSFldActionPerformed);

        hrEditEmployeePhilHealthFld.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        hrEditEmployeePhilHealthFld.setForeground(new java.awt.Color(31, 41, 55));
        hrEditEmployeePhilHealthFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        hrEditEmployeePhilHealthFld.addActionListener(this::hrEditEmployeePhilHealthFldActionPerformed);

        hrEditEmployeeENumberFld.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        hrEditEmployeeENumberFld.setForeground(new java.awt.Color(31, 41, 55));
        hrEditEmployeeENumberFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        hrEditEmployeeENumberFld.addActionListener(this::hrEditEmployeeENumberFldActionPerformed);

        hrEditEmployeeISupervisorFld.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        hrEditEmployeeISupervisorFld.setForeground(new java.awt.Color(31, 41, 55));
        hrEditEmployeeISupervisorFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        hrEditEmployeeISupervisorFld.addActionListener(this::hrEditEmployeeISupervisorFldActionPerformed);

        hrEditEmployeeRiceSubsidyFld.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        hrEditEmployeeRiceSubsidyFld.setForeground(new java.awt.Color(31, 41, 55));
        hrEditEmployeeRiceSubsidyFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        hrEditEmployeeRiceSubsidyFld.addActionListener(this::hrEditEmployeeRiceSubsidyFldActionPerformed);

        hrEditEmployeeTINFld.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        hrEditEmployeeTINFld.setForeground(new java.awt.Color(31, 41, 55));
        hrEditEmployeeTINFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        hrEditEmployeeTINFld.addActionListener(this::hrEditEmployeeTINFldActionPerformed);

        hrEditEmployeePagIbigFld.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        hrEditEmployeePagIbigFld.setForeground(new java.awt.Color(31, 41, 55));
        hrEditEmployeePagIbigFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        hrEditEmployeePagIbigFld.addActionListener(this::hrEditEmployeePagIbigFldActionPerformed);

        hrEditEmployeePhnNumberFld.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        hrEditEmployeePhnNumberFld.setForeground(new java.awt.Color(31, 41, 55));
        hrEditEmployeePhnNumberFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        hrEditEmployeePhnNumberFld.addActionListener(this::hrEditEmployeePhnNumberFldActionPerformed);

        hrEditEmployeeFNameFld.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        hrEditEmployeeFNameFld.setForeground(new java.awt.Color(31, 41, 55));
        hrEditEmployeeFNameFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        hrEditEmployeeFNameFld.addActionListener(this::hrEditEmployeeFNameFldActionPerformed);

        hrEditEmployeeStatusCbx.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        hrEditEmployeeStatusCbx.setForeground(new java.awt.Color(31, 41, 55));
        hrEditEmployeeStatusCbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose", "Regular", "Probationary" }));
        hrEditEmployeeStatusCbx.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));

        hrEditEmployeeStatusLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        hrEditEmployeeStatusLbl.setForeground(new java.awt.Color(31, 41, 55));
        hrEditEmployeeStatusLbl.setText("Status");

        hrEditEmployeeCltAllowanceFld.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        hrEditEmployeeCltAllowanceFld.setForeground(new java.awt.Color(31, 41, 55));
        hrEditEmployeeCltAllowanceFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        hrEditEmployeeCltAllowanceFld.addActionListener(this::hrEditEmployeeCltAllowanceFldActionPerformed);

        javax.swing.GroupLayout hrEditEmployeeEDetailsBrdrPnlLayout = new javax.swing.GroupLayout(hrEditEmployeeEDetailsBrdrPnl);
        hrEditEmployeeEDetailsBrdrPnl.setLayout(hrEditEmployeeEDetailsBrdrPnlLayout);
        hrEditEmployeeEDetailsBrdrPnlLayout.setHorizontalGroup(
            hrEditEmployeeEDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hrEditEmployeeEDetailsBrdrPnlLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(hrEditEmployeeEDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(hrEditEmployeeEDetailsBrdrPnlLayout.createSequentialGroup()
                        .addGroup(hrEditEmployeeEDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hrEditEmployeePhnAllowanceLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hrEditEmployeeBasicSalaryLbl)
                            .addComponent(hrEditEmployeeSSSLbl)
                            .addComponent(hrEditEmployeePhilHealthLbl))
                        .addContainerGap())
                    .addGroup(hrEditEmployeeEDetailsBrdrPnlLayout.createSequentialGroup()
                        .addGroup(hrEditEmployeeEDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hrEditEmployeeENumberLbl)
                            .addComponent(hrEditEmployeeLNameLbl))
                        .addGap(54, 54, 54)
                        .addGroup(hrEditEmployeeEDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hrEditEmployeeLNameFld, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hrEditEmployeeENumberFld, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(hrEditEmployeeEDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hrEditEmployeeStatusLbl)
                            .addComponent(hrEditEmployeeFNameLbl))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(hrEditEmployeeEDetailsBrdrPnlLayout.createSequentialGroup()
                        .addGroup(hrEditEmployeeEDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hrEditEmployeeBirthdayLbl)
                            .addComponent(hrEditEmployeePositionLbl)
                            .addComponent(hrEditEmployeeAddressLbl))
                        .addGap(81, 81, 81)
                        .addGroup(hrEditEmployeeEDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(hrEditEmployeeEDetailsBrdrPnlLayout.createSequentialGroup()
                                .addGroup(hrEditEmployeeEDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(hrEditEmployeePhilHealthFld, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(hrEditEmployeeSSSFld, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hrEditEmployeeEDetailsBrdrPnlLayout.createSequentialGroup()
                                .addGroup(hrEditEmployeeEDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(hrEditEmployeeAddressFld, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(hrEditEmployeeEDetailsBrdrPnlLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(hrEditEmployeeEDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(hrEditEmployeeFNameFld, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(hrEditEmployeeEDetailsBrdrPnlLayout.createSequentialGroup()
                                                .addGroup(hrEditEmployeeEDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(hrEditEmployeeEDetailsBrdrPnlLayout.createSequentialGroup()
                                                        .addGroup(hrEditEmployeeEDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(hrEditEmployeePositionFld, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(hrEditEmployeeBirthdayFld, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(hrEditEmployeeBasicSalaryFld, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(hrEditEmployeeEDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(hrEditEmployeeEDetailsBrdrPnlLayout.createSequentialGroup()
                                                                .addGap(18, 18, 18)
                                                                .addComponent(hrEditEmployeeRiceSubsidyLbl))
                                                            .addGroup(hrEditEmployeeEDetailsBrdrPnlLayout.createSequentialGroup()
                                                                .addGap(18, 18, 18)
                                                                .addGroup(hrEditEmployeeEDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                    .addComponent(hrEditEmployeePhnNumberLbl)
                                                                    .addComponent(hrEditEmployeeISupervisorLbl)))))
                                                    .addGroup(hrEditEmployeeEDetailsBrdrPnlLayout.createSequentialGroup()
                                                        .addComponent(hrEditEmployeePhnAllowanceFld, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addGroup(hrEditEmployeeEDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(hrEditEmployeeTINLbl)
                                                            .addComponent(hrEditEmployeeCltAllowanceLbl)
                                                            .addComponent(hrEditEmployeePagIbigLbl))))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(hrEditEmployeeEDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(hrEditEmployeePagIbigFld, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(hrEditEmployeeTINFld, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(hrEditEmployeeCltAllowanceFld, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(hrEditEmployeeRiceSubsidyFld, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(hrEditEmployeeISupervisorFld, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(hrEditEmployeePhnNumberFld, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(hrEditEmployeeStatusCbx, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(55, 55, 55))))))
        );
        hrEditEmployeeEDetailsBrdrPnlLayout.setVerticalGroup(
            hrEditEmployeeEDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hrEditEmployeeEDetailsBrdrPnlLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(hrEditEmployeeEDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hrEditEmployeeENumberLbl)
                    .addGroup(hrEditEmployeeEDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(hrEditEmployeeENumberFld, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(hrEditEmployeeStatusCbx, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(hrEditEmployeeStatusLbl)))
                .addGap(16, 16, 16)
                .addGroup(hrEditEmployeeEDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hrEditEmployeeLNameLbl)
                    .addGroup(hrEditEmployeeEDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(hrEditEmployeeFNameLbl)
                        .addComponent(hrEditEmployeeLNameFld, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(hrEditEmployeeFNameFld, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(hrEditEmployeeEDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hrEditEmployeeAddressLbl)
                    .addComponent(hrEditEmployeeAddressFld, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(hrEditEmployeeEDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(hrEditEmployeeEDetailsBrdrPnlLayout.createSequentialGroup()
                        .addGroup(hrEditEmployeeEDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hrEditEmployeeBirthdayLbl)
                            .addGroup(hrEditEmployeeEDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(hrEditEmployeePhnNumberLbl)
                                .addComponent(hrEditEmployeeBirthdayFld, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(hrEditEmployeePositionLbl))
                    .addGroup(hrEditEmployeeEDetailsBrdrPnlLayout.createSequentialGroup()
                        .addComponent(hrEditEmployeePhnNumberFld, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addGroup(hrEditEmployeeEDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hrEditEmployeePositionFld, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hrEditEmployeeISupervisorLbl)
                            .addComponent(hrEditEmployeeISupervisorFld, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(hrEditEmployeeEDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hrEditEmployeeBasicSalaryFld, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hrEditEmployeeBasicSalaryLbl)
                    .addComponent(hrEditEmployeeRiceSubsidyLbl)
                    .addComponent(hrEditEmployeeRiceSubsidyFld, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(hrEditEmployeeEDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hrEditEmployeePhnAllowanceFld, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hrEditEmployeePhnAllowanceLbl)
                    .addComponent(hrEditEmployeeCltAllowanceLbl)
                    .addComponent(hrEditEmployeeCltAllowanceFld, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(hrEditEmployeeEDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hrEditEmployeeSSSLbl)
                    .addGroup(hrEditEmployeeEDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(hrEditEmployeeTINLbl)
                        .addComponent(hrEditEmployeeSSSFld, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(hrEditEmployeeTINFld, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(hrEditEmployeeEDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(hrEditEmployeeEDetailsBrdrPnlLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(hrEditEmployeeEDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hrEditEmployeePhilHealthLbl)
                            .addGroup(hrEditEmployeeEDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(hrEditEmployeePagIbigLbl)
                                .addComponent(hrEditEmployeePhilHealthFld, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(hrEditEmployeeEDetailsBrdrPnlLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(hrEditEmployeePagIbigFld, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        hrEditEmployeeENumberLbl.getAccessibleContext().setAccessibleName("hrEditEmployeeENumberLbl");
        hrEditEmployeeLNameLbl.getAccessibleContext().setAccessibleName("hrEditEmployeeLNameLbl");
        hrEditEmployeeAddressLbl.getAccessibleContext().setAccessibleName("hrEditEmployeeAddressLbl");
        hrEditEmployeeBirthdayLbl.getAccessibleContext().setAccessibleName("hrEditEmployeeBirthdayLbl");
        hrEditEmployeePositionLbl.getAccessibleContext().setAccessibleName("hrEditEmployeePositionLbl");
        hrEditEmployeeBasicSalaryLbl.getAccessibleContext().setAccessibleName("hrEditEmployeeBasicSalaryLbl");
        hrEditEmployeeSSSLbl.getAccessibleContext().setAccessibleName("hrEditEmployeeSSSLbl");
        hrEditEmployeePhilHealthLbl.getAccessibleContext().setAccessibleName("hrEditEmployeePhilHealthLbl");
        hrEditEmployeeCltAllowanceLbl.getAccessibleContext().setAccessibleName("hrEditEmployeeCltAllowanceLbl");
        hrEditEmployeeFNameLbl.getAccessibleContext().setAccessibleName("hrEditEmployeeFNameLbl");
        hrEditEmployeePhnNumberLbl.getAccessibleContext().setAccessibleName("hrEditEmployeePhnNumberLbl");
        hrEditEmployeeISupervisorLbl.getAccessibleContext().setAccessibleName("hrEditEmployeeISupervisorLbl");
        hrEditEmployeeRiceSubsidyLbl.getAccessibleContext().setAccessibleName("hrEditEmployeeRiceSubsidyLbl");
        hrEditEmployeeTINLbl.getAccessibleContext().setAccessibleName("hrEditEmployeeTINLbl");
        hrEditEmployeePagIbigLbl.getAccessibleContext().setAccessibleName("hrEditEmployeePagIbigLbl");
        hrEditEmployeePhnAllowanceLbl.getAccessibleContext().setAccessibleName("hrEditEmployeePhnAllowanceLbl");
        hrEditEmployeeLNameFld.getAccessibleContext().setAccessibleName("hrEditEmployeeLNameFld");
        hrEditEmployeeAddressFld.getAccessibleContext().setAccessibleName("hrEditEmployeeAddressFld");
        hrEditEmployeeBirthdayFld.getAccessibleContext().setAccessibleName("hrEditEmployeeBirthdayFld");
        hrEditEmployeePositionFld.getAccessibleContext().setAccessibleName("hrEditEmployeePositionFld");
        hrEditEmployeeBasicSalaryFld.getAccessibleContext().setAccessibleName("hrEditEmployeeBasicSalaryFld");
        hrEditEmployeePhnAllowanceFld.getAccessibleContext().setAccessibleName("hrEditEmployeePhnAllowanceFld");
        hrEditEmployeeSSSFld.getAccessibleContext().setAccessibleName("hrEditEmployeeSSSFld");
        hrEditEmployeePhilHealthFld.getAccessibleContext().setAccessibleName("hrEditEmployeePhilHealthFld");
        hrEditEmployeeENumberFld.getAccessibleContext().setAccessibleName("hrEditEmployeeENumberFld");
        hrEditEmployeeISupervisorFld.getAccessibleContext().setAccessibleName("hrEditEmployeeISupervisorFld");
        hrEditEmployeeRiceSubsidyFld.getAccessibleContext().setAccessibleName("hrEditEmployeeRiceSubsidyFld");
        hrEditEmployeeTINFld.getAccessibleContext().setAccessibleName("hrEditEmployeeTINFld");
        hrEditEmployeePagIbigFld.getAccessibleContext().setAccessibleName("hrEditEmployeePagIbigFld");
        hrEditEmployeePhnNumberFld.getAccessibleContext().setAccessibleName("hrEditEmployeePhnNumberFld");
        hrEditEmployeeFNameFld.getAccessibleContext().setAccessibleName("hrEditEmployeeFNameFld");
        hrEditEmployeeStatusCbx.getAccessibleContext().setAccessibleName("hrEditEmployeeStatusCbx");
        hrEditEmployeeStatusLbl.getAccessibleContext().setAccessibleName("hrEditEmployeeStatusLbl");
        hrEditEmployeeCltAllowanceFld.getAccessibleContext().setAccessibleName("hrEditEmployeeCltAllowanceFld");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(hrEditEmployeeUpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(hrEditEmployeeSidebarPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hrEditEmployeeEditEDetailsPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hrEditEmployeeEDetailsBrdrPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(hrEditEmployeeSidebarPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(hrEditEmployeeEditEDetailsPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hrEditEmployeeEDetailsBrdrPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(hrEditEmployeeUpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        hrEditEmployeeSidebarPnl.getAccessibleContext().setAccessibleName("hrEditEmployeeSidebarPnl");
        hrEditEmployeeUpdateBtn.getAccessibleContext().setAccessibleName("hrEditEmployeeUpdateBtn");
        hrEditEmployeeEditEDetailsPnl.getAccessibleContext().setAccessibleName("hrEditEmployeeEditEDetailsPnl");
        hrEditEmployeeEDetailsBrdrPnl.getAccessibleContext().setAccessibleName("hrEditEmployeeEDetailsBrdrPnl");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hrEditEmployeeEDetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrEditEmployeeEDetailsBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hrEditEmployeeEDetailsBtnActionPerformed

    private void hrEditEmployeeEditEDetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrEditEmployeeEditEDetailsBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hrEditEmployeeEditEDetailsBtnActionPerformed

    private void hrEditEmployeeAEDetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrEditEmployeeAEDetailsBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hrEditEmployeeAEDetailsBtnActionPerformed

    private void hrEditEmployeeMainDashboardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrEditEmployeeMainDashboardBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new MainDashboardUI().setVisible(true);
    }//GEN-LAST:event_hrEditEmployeeMainDashboardBtnActionPerformed

    private void hrEditEmployeeUpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrEditEmployeeUpdateBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hrEditEmployeeUpdateBtnActionPerformed

    private void hrEditEmployeeLNameFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrEditEmployeeLNameFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hrEditEmployeeLNameFldActionPerformed

    private void hrEditEmployeeAddressFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrEditEmployeeAddressFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hrEditEmployeeAddressFldActionPerformed

    private void hrEditEmployeeBirthdayFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrEditEmployeeBirthdayFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hrEditEmployeeBirthdayFldActionPerformed

    private void hrEditEmployeePositionFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrEditEmployeePositionFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hrEditEmployeePositionFldActionPerformed

    private void hrEditEmployeeBasicSalaryFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrEditEmployeeBasicSalaryFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hrEditEmployeeBasicSalaryFldActionPerformed

    private void hrEditEmployeePhnAllowanceFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrEditEmployeePhnAllowanceFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hrEditEmployeePhnAllowanceFldActionPerformed

    private void hrEditEmployeeSSSFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrEditEmployeeSSSFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hrEditEmployeeSSSFldActionPerformed

    private void hrEditEmployeePhilHealthFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrEditEmployeePhilHealthFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hrEditEmployeePhilHealthFldActionPerformed

    private void hrEditEmployeeENumberFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrEditEmployeeENumberFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hrEditEmployeeENumberFldActionPerformed

    private void hrEditEmployeeISupervisorFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrEditEmployeeISupervisorFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hrEditEmployeeISupervisorFldActionPerformed

    private void hrEditEmployeeRiceSubsidyFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrEditEmployeeRiceSubsidyFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hrEditEmployeeRiceSubsidyFldActionPerformed

    private void hrEditEmployeeTINFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrEditEmployeeTINFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hrEditEmployeeTINFldActionPerformed

    private void hrEditEmployeePagIbigFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrEditEmployeePagIbigFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hrEditEmployeePagIbigFldActionPerformed

    private void hrEditEmployeePhnNumberFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrEditEmployeePhnNumberFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hrEditEmployeePhnNumberFldActionPerformed

    private void hrEditEmployeeFNameFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrEditEmployeeFNameFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hrEditEmployeeFNameFldActionPerformed

    private void hrEditEmployeeCltAllowanceFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrEditEmployeeCltAllowanceFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hrEditEmployeeCltAllowanceFldActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton hrEditEmployeeAEDetailsBtn;
    private javax.swing.JTextField hrEditEmployeeAddressFld;
    private javax.swing.JLabel hrEditEmployeeAddressLbl;
    private javax.swing.JTextField hrEditEmployeeBasicSalaryFld;
    private javax.swing.JLabel hrEditEmployeeBasicSalaryLbl;
    private javax.swing.JTextField hrEditEmployeeBirthdayFld;
    private javax.swing.JLabel hrEditEmployeeBirthdayLbl;
    private javax.swing.JTextField hrEditEmployeeCltAllowanceFld;
    private javax.swing.JLabel hrEditEmployeeCltAllowanceLbl;
    private javax.swing.JPanel hrEditEmployeeEDetailsBrdrPnl;
    private javax.swing.JButton hrEditEmployeeEDetailsBtn;
    private javax.swing.JTextField hrEditEmployeeENumberFld;
    private javax.swing.JLabel hrEditEmployeeENumberLbl;
    private javax.swing.JButton hrEditEmployeeEditEDetailsBtn;
    private javax.swing.JLabel hrEditEmployeeEditEDetailsLbl;
    private javax.swing.JPanel hrEditEmployeeEditEDetailsPnl;
    private javax.swing.JTextField hrEditEmployeeFNameFld;
    private javax.swing.JLabel hrEditEmployeeFNameLbl;
    private javax.swing.JTextField hrEditEmployeeISupervisorFld;
    private javax.swing.JLabel hrEditEmployeeISupervisorLbl;
    private javax.swing.JTextField hrEditEmployeeLNameFld;
    private javax.swing.JLabel hrEditEmployeeLNameLbl;
    private javax.swing.JButton hrEditEmployeeMainDashboardBtn;
    private javax.swing.JLabel hrEditEmployeeMotorPHIconImgLbl;
    private javax.swing.JTextField hrEditEmployeePagIbigFld;
    private javax.swing.JLabel hrEditEmployeePagIbigLbl;
    private javax.swing.JTextField hrEditEmployeePhilHealthFld;
    private javax.swing.JLabel hrEditEmployeePhilHealthLbl;
    private javax.swing.JTextField hrEditEmployeePhnAllowanceFld;
    private javax.swing.JLabel hrEditEmployeePhnAllowanceLbl;
    private javax.swing.JTextField hrEditEmployeePhnNumberFld;
    private javax.swing.JLabel hrEditEmployeePhnNumberLbl;
    private javax.swing.JTextField hrEditEmployeePositionFld;
    private javax.swing.JLabel hrEditEmployeePositionLbl;
    private javax.swing.JTextField hrEditEmployeeRiceSubsidyFld;
    private javax.swing.JLabel hrEditEmployeeRiceSubsidyLbl;
    private javax.swing.JTextField hrEditEmployeeSSSFld;
    private javax.swing.JLabel hrEditEmployeeSSSLbl;
    private javax.swing.JPanel hrEditEmployeeSidebarPnl;
    private javax.swing.JComboBox<String> hrEditEmployeeStatusCbx;
    private javax.swing.JLabel hrEditEmployeeStatusLbl;
    private javax.swing.JTextField hrEditEmployeeTINFld;
    private javax.swing.JLabel hrEditEmployeeTINLbl;
    private javax.swing.JButton hrEditEmployeeUpdateBtn;
    // End of variables declaration//GEN-END:variables
}
