
package com.motorph.ui;

import com.motorph.dao.CsvEmployeeDAO;
import com.motorph.model.Employee;
import com.motorph.service.EmployeeService;
import com.motorph.util.DateUtils;
import javax.swing.JOptionPane;


public class HREmployeeDetailsUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HREmployeeDetailsUI.class.getName());
    private final EmployeeService empService;
    /**
     * Creates new form HRDashboardFrame
     */
    public HREmployeeDetailsUI() {
        initComponents();
        
        this.empService = new EmployeeService(new CsvEmployeeDAO());
        
      
    }
    
    private void performSearch() {
        String id = hrEDetailsEntENumberFld.getText().trim();
        System.out.println(id);
        Employee found = empService.findEmployee(id);
        if (found != null) {
            populateFields(found);
        } else {
            clearFields();
        }
    }
    
    private void populateFields(Employee emp) {
        hrEDetailsENumberFld.setText(emp.getEmployeeNumber());
        hrEDetailsIFNameFld.setText(emp.getFirstName());
        hrEDetailsLNameFld.setText(emp.getLastName());
        //hrEDetailsBirthdayFld.setText(DateUtils.dateToString(emp.getBirthday()));
        hrEDetailsAddressFld.setText(emp.getAddress());
        hrEDetailsIPhnNumberFld.setText(emp.getPhoneNumber());
        hrEDetailsSSSFld.setText(emp.getSSSNumber());
        hrEDetailsPhilHealthFld.setText(emp.getPhilhealthNumber());
        hrEDetailsTINFld.setText(emp.getTIN());
        hrEDetailsPagIbigFld.setText(emp.getPagIbigNumber());
        //hrEDetailsIStatusFld.setText(emp.getStatus());
        hrEDetailsPositionFld.setText(emp.getPosition());
        hrEDetailsISupervisorFld.setText(emp.getImmediateSupervisor());
        hrEDetailsBasicSalaryFld.setText(String.valueOf(emp.getBasicSalary()));
        hrEDetailsRiceSubsidyFld.setText(String.valueOf(emp.getRiceSubsidy()));
        hrEDetailsPhnAllowanceFld.setText(String.valueOf(emp.getPhoneAllowance()));
        hrEDetailsCltAllowanceFld.setText(String.valueOf(emp.getClothingAllowance()));
    }

    private void clearFields() {
        hrEDetailsENumberFld.setText("");
        hrEDetailsIFNameFld.setText("");
        hrEDetailsLNameFld.setText("");
        //hrEDetailsBirthdayFld.setText("");
        hrEDetailsAddressFld.setText("");
        hrEDetailsIPhnNumberFld.setText("");
        hrEDetailsSSSFld.setText("");
        hrEDetailsPhilHealthFld.setText("");
        hrEDetailsTINFld.setText("");
        hrEDetailsPagIbigFld.setText("");
        //hrEDetailsIStatusFld.setText("");
        hrEDetailsPositionFld.setText("");
        hrEDetailsISupervisorFld.setText("");
        hrEDetailsBasicSalaryFld.setText("");
        hrEDetailsRiceSubsidyFld.setText("");
        hrEDetailsPhnAllowanceFld.setText("");
        hrEDetailsCltAllowanceFld.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        hrEDetailsSidebarPnl = new javax.swing.JPanel();
        hrEDetailsEDetailsBtn = new javax.swing.JButton();
        hrEDetailsMainDashboardBtn = new javax.swing.JButton();
        hrEDetailsMotorPHIconImgLbl = new javax.swing.JLabel();
        hrEDetailsEDetailsPnl = new javax.swing.JPanel();
        hrEDetailsEDetailsLbl = new javax.swing.JLabel();
        hrEDetailsAddBtn = new javax.swing.JButton();
        hrEDetailsEditBtn = new javax.swing.JButton();
        hrEDetailsDeleteBtn = new javax.swing.JButton();
        hrEDetailsSearchPnl = new javax.swing.JPanel();
        hrEDetailsEntENumberFld = new javax.swing.JTextField();
        hrEDetailsSearchIconImgLbl = new javax.swing.JLabel();
        hrEDetailsEDetailsBrdrPnl = new javax.swing.JPanel();
        hrEDetailsENumberLbl = new javax.swing.JLabel();
        hrEDetailsLNameLbl = new javax.swing.JLabel();
        hrEDetailsAddressLbl = new javax.swing.JLabel();
        hrEDetailsBirthdayLbl = new javax.swing.JLabel();
        hrEDetailsENumberFld = new javax.swing.JTextField();
        hrEDetailsAddressFld = new javax.swing.JTextField();
        hrEDetailsLNameFld = new javax.swing.JTextField();
        hrEDetailsPositionFld = new javax.swing.JTextField();
        hrEDetailsBasicSalaryFld = new javax.swing.JTextField();
        hrEDetailsPhnAllowanceFld = new javax.swing.JTextField();
        hrEDetailsPositionLbl = new javax.swing.JLabel();
        hrEDetailsBasicSalaryLbl = new javax.swing.JLabel();
        hrEDetailsPhnAllowanceLbl = new javax.swing.JLabel();
        hrEDetailsSSSFld = new javax.swing.JTextField();
        hrEDetailsPhilHealthFld = new javax.swing.JTextField();
        hrEDetailsSSSLbl = new javax.swing.JLabel();
        hrEDetailsPhilHealthLbl = new javax.swing.JLabel();
        hrEDetailsIFNameFld = new javax.swing.JTextField();
        hrEDetailsISupervisorLbl = new javax.swing.JLabel();
        hrEDetailsIPhnNumberFld = new javax.swing.JTextField();
        hrEDetailsISupervisorFld = new javax.swing.JTextField();
        hrEDetailsRiceSubsidyFld = new javax.swing.JTextField();
        hrEDetailsCltAllowanceFld = new javax.swing.JTextField();
        hrEDetailsTINFld = new javax.swing.JTextField();
        hrEDetailsPagIbigFld = new javax.swing.JTextField();
        hrEDetailsIFNameLbl = new javax.swing.JLabel();
        hrEDetailsIPhnNumberLbl = new javax.swing.JLabel();
        hrEDetailsRiceSubsidyLbl = new javax.swing.JLabel();
        hrEDetailsCltAllowanceLbl = new javax.swing.JLabel();
        hrEDetailsTINLbl = new javax.swing.JLabel();
        hrEDetailsPagIbigLbl = new javax.swing.JLabel();
        hrEDetailsIStatusLbl = new javax.swing.JLabel();
        hrAEmployeeBirthdayDtChsr = new com.toedter.calendar.JDateChooser();
        hrEDetailsIStatusCbx = new javax.swing.JComboBox<>();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        hrEDetailsSidebarPnl.setBackground(new java.awt.Color(30, 58, 138));

        hrEDetailsEDetailsBtn.setBackground(new java.awt.Color(30, 42, 56));
        hrEDetailsEDetailsBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        hrEDetailsEDetailsBtn.setForeground(new java.awt.Color(255, 255, 255));
        hrEDetailsEDetailsBtn.setText("Employee Details");
        hrEDetailsEDetailsBtn.setToolTipText("");
        hrEDetailsEDetailsBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        hrEDetailsEDetailsBtn.addActionListener(this::hrEDetailsEDetailsBtnActionPerformed);

        hrEDetailsMainDashboardBtn.setBackground(new java.awt.Color(30, 42, 56));
        hrEDetailsMainDashboardBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        hrEDetailsMainDashboardBtn.setForeground(new java.awt.Color(255, 255, 255));
        hrEDetailsMainDashboardBtn.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        hrEDetailsMainDashboardBtn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        hrEDetailsMainDashboardBtn.setLabel("Main Dashboard");
        hrEDetailsMainDashboardBtn.addActionListener(this::hrEDetailsMainDashboardBtnActionPerformed);

        hrEDetailsMotorPHIconImgLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/motorph/img/MotorPHIconImg.png"))); // NOI18N

        javax.swing.GroupLayout hrEDetailsSidebarPnlLayout = new javax.swing.GroupLayout(hrEDetailsSidebarPnl);
        hrEDetailsSidebarPnl.setLayout(hrEDetailsSidebarPnlLayout);
        hrEDetailsSidebarPnlLayout.setHorizontalGroup(
            hrEDetailsSidebarPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hrEDetailsSidebarPnlLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(hrEDetailsMainDashboardBtn))
            .addGroup(hrEDetailsSidebarPnlLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(hrEDetailsSidebarPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hrEDetailsEDetailsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(hrEDetailsSidebarPnlLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(hrEDetailsMotorPHIconImgLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        hrEDetailsSidebarPnlLayout.setVerticalGroup(
            hrEDetailsSidebarPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hrEDetailsSidebarPnlLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(hrEDetailsSidebarPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(hrEDetailsSidebarPnlLayout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(hrEDetailsEDetailsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(hrEDetailsMotorPHIconImgLbl))
                .addGap(409, 409, 409)
                .addComponent(hrEDetailsMainDashboardBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        hrEDetailsEDetailsBtn.getAccessibleContext().setAccessibleName("hrEDetailsEDetailsBtn");
        hrEDetailsMainDashboardBtn.getAccessibleContext().setAccessibleName("hrEDetailsMainDashboardBtn");
        hrEDetailsMotorPHIconImgLbl.getAccessibleContext().setAccessibleName("hrEDetailsMotorPHIconImgLbl");

        hrEDetailsEDetailsPnl.setBackground(new java.awt.Color(30, 58, 138));
        hrEDetailsEDetailsPnl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        hrEDetailsEDetailsPnl.setForeground(new java.awt.Color(30, 58, 138));
        hrEDetailsEDetailsPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hrEDetailsEDetailsLbl.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        hrEDetailsEDetailsLbl.setForeground(new java.awt.Color(255, 255, 255));
        hrEDetailsEDetailsLbl.setText("Employee Details");
        hrEDetailsEDetailsPnl.add(hrEDetailsEDetailsLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 1, 211, 46));
        hrEDetailsEDetailsLbl.getAccessibleContext().setAccessibleName("hrEDetailsEDetailsLbl");

        hrEDetailsAddBtn.setBackground(new java.awt.Color(30, 58, 138));
        hrEDetailsAddBtn.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        hrEDetailsAddBtn.setForeground(new java.awt.Color(255, 255, 255));
        hrEDetailsAddBtn.setText("Add");
        hrEDetailsAddBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        hrEDetailsAddBtn.addActionListener(this::hrEDetailsAddBtnActionPerformed);

        hrEDetailsEditBtn.setBackground(new java.awt.Color(59, 130, 246));
        hrEDetailsEditBtn.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        hrEDetailsEditBtn.setForeground(new java.awt.Color(255, 255, 255));
        hrEDetailsEditBtn.setText("Edit");
        hrEDetailsEditBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        hrEDetailsEditBtn.addActionListener(this::hrEDetailsEditBtnActionPerformed);

        hrEDetailsDeleteBtn.setBackground(new java.awt.Color(239, 68, 68));
        hrEDetailsDeleteBtn.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        hrEDetailsDeleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        hrEDetailsDeleteBtn.setText("Delete");
        hrEDetailsDeleteBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        hrEDetailsDeleteBtn.addActionListener(this::hrEDetailsDeleteBtnActionPerformed);

        hrEDetailsSearchPnl.setBackground(new java.awt.Color(146, 192, 253));
        hrEDetailsSearchPnl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        hrEDetailsSearchPnl.setForeground(new java.awt.Color(146, 192, 253));
        hrEDetailsSearchPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hrEDetailsEntENumberFld.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        hrEDetailsEntENumberFld.setForeground(new java.awt.Color(31, 41, 55));
        hrEDetailsEntENumberFld.setText("   Enter Employee #");
        hrEDetailsEntENumberFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        hrEDetailsEntENumberFld.addActionListener(this::hrEDetailsEntENumberFldActionPerformed);
        hrEDetailsSearchPnl.add(hrEDetailsEntENumberFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 7, 170, 31));
        hrEDetailsEntENumberFld.getAccessibleContext().setAccessibleName("hrEDetailsEntENumberFld");

        hrEDetailsSearchIconImgLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/motorph/img/SearchIconImg.png"))); // NOI18N
        hrEDetailsSearchIconImgLbl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                hrEDetailsSearchIconImgLblKeyPressed(evt);
            }
        });
        hrEDetailsSearchPnl.add(hrEDetailsSearchIconImgLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, -10, 60, 60));
        hrEDetailsSearchIconImgLbl.getAccessibleContext().setAccessibleName("hrEDetailsSearchIconImgLbl");

        hrEDetailsEDetailsBrdrPnl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 2, true));
        hrEDetailsEDetailsBrdrPnl.setForeground(new java.awt.Color(30, 42, 56));
        hrEDetailsEDetailsBrdrPnl.setFocusable(false);
        hrEDetailsEDetailsBrdrPnl.setPreferredSize(new java.awt.Dimension(700, 469));
        hrEDetailsEDetailsBrdrPnl.setRequestFocusEnabled(false);

        hrEDetailsENumberLbl.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        hrEDetailsENumberLbl.setForeground(new java.awt.Color(31, 41, 55));
        hrEDetailsENumberLbl.setText("Employee #");

        hrEDetailsLNameLbl.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        hrEDetailsLNameLbl.setForeground(new java.awt.Color(31, 41, 55));
        hrEDetailsLNameLbl.setText("Last Name");

        hrEDetailsAddressLbl.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        hrEDetailsAddressLbl.setForeground(new java.awt.Color(31, 41, 55));
        hrEDetailsAddressLbl.setText("Address");

        hrEDetailsBirthdayLbl.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        hrEDetailsBirthdayLbl.setForeground(new java.awt.Color(31, 41, 55));
        hrEDetailsBirthdayLbl.setText("Birthday");

        hrEDetailsENumberFld.setForeground(new java.awt.Color(30, 42, 56));
        hrEDetailsENumberFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        hrEDetailsENumberFld.setCaretColor(new java.awt.Color(31, 41, 55));
        hrEDetailsENumberFld.setDisabledTextColor(new java.awt.Color(31, 41, 55));
        hrEDetailsENumberFld.setEnabled(false);
        hrEDetailsENumberFld.addActionListener(this::hrEDetailsENumberFldActionPerformed);

        hrEDetailsAddressFld.setForeground(new java.awt.Color(30, 42, 56));
        hrEDetailsAddressFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        hrEDetailsAddressFld.setCaretColor(new java.awt.Color(31, 41, 55));
        hrEDetailsAddressFld.setDisabledTextColor(new java.awt.Color(31, 41, 55));
        hrEDetailsAddressFld.setEnabled(false);
        hrEDetailsAddressFld.addActionListener(this::hrEDetailsAddressFldActionPerformed);

        hrEDetailsLNameFld.setForeground(new java.awt.Color(30, 42, 56));
        hrEDetailsLNameFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        hrEDetailsLNameFld.setCaretColor(new java.awt.Color(31, 41, 55));
        hrEDetailsLNameFld.setDisabledTextColor(new java.awt.Color(31, 41, 55));
        hrEDetailsLNameFld.setEnabled(false);
        hrEDetailsLNameFld.addActionListener(this::hrEDetailsLNameFldActionPerformed);

        hrEDetailsPositionFld.setForeground(new java.awt.Color(30, 42, 56));
        hrEDetailsPositionFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        hrEDetailsPositionFld.setCaretColor(new java.awt.Color(31, 41, 55));
        hrEDetailsPositionFld.setDisabledTextColor(new java.awt.Color(31, 41, 55));
        hrEDetailsPositionFld.setEnabled(false);
        hrEDetailsPositionFld.addActionListener(this::hrEDetailsPositionFldActionPerformed);

        hrEDetailsBasicSalaryFld.setForeground(new java.awt.Color(30, 42, 56));
        hrEDetailsBasicSalaryFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        hrEDetailsBasicSalaryFld.setCaretColor(new java.awt.Color(31, 41, 55));
        hrEDetailsBasicSalaryFld.setDisabledTextColor(new java.awt.Color(31, 41, 55));
        hrEDetailsBasicSalaryFld.setEnabled(false);
        hrEDetailsBasicSalaryFld.addActionListener(this::hrEDetailsBasicSalaryFldActionPerformed);

        hrEDetailsPhnAllowanceFld.setForeground(new java.awt.Color(30, 42, 56));
        hrEDetailsPhnAllowanceFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        hrEDetailsPhnAllowanceFld.setCaretColor(new java.awt.Color(31, 41, 55));
        hrEDetailsPhnAllowanceFld.setDisabledTextColor(new java.awt.Color(31, 41, 55));
        hrEDetailsPhnAllowanceFld.setEnabled(false);
        hrEDetailsPhnAllowanceFld.addActionListener(this::hrEDetailsPhnAllowanceFldActionPerformed);

        hrEDetailsPositionLbl.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        hrEDetailsPositionLbl.setForeground(new java.awt.Color(31, 41, 55));
        hrEDetailsPositionLbl.setText("Position");

        hrEDetailsBasicSalaryLbl.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        hrEDetailsBasicSalaryLbl.setForeground(new java.awt.Color(31, 41, 55));
        hrEDetailsBasicSalaryLbl.setText("Basic Salary");

        hrEDetailsPhnAllowanceLbl.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        hrEDetailsPhnAllowanceLbl.setForeground(new java.awt.Color(31, 41, 55));
        hrEDetailsPhnAllowanceLbl.setText("Phone Allowance");

        hrEDetailsSSSFld.setForeground(new java.awt.Color(30, 42, 56));
        hrEDetailsSSSFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        hrEDetailsSSSFld.setCaretColor(new java.awt.Color(31, 41, 55));
        hrEDetailsSSSFld.setDisabledTextColor(new java.awt.Color(31, 41, 55));
        hrEDetailsSSSFld.setEnabled(false);
        hrEDetailsSSSFld.addActionListener(this::hrEDetailsSSSFldActionPerformed);

        hrEDetailsPhilHealthFld.setForeground(new java.awt.Color(30, 42, 56));
        hrEDetailsPhilHealthFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        hrEDetailsPhilHealthFld.setDisabledTextColor(new java.awt.Color(31, 41, 55));
        hrEDetailsPhilHealthFld.setEnabled(false);
        hrEDetailsPhilHealthFld.addActionListener(this::hrEDetailsPhilHealthFldActionPerformed);

        hrEDetailsSSSLbl.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        hrEDetailsSSSLbl.setForeground(new java.awt.Color(31, 41, 55));
        hrEDetailsSSSLbl.setText("SSS");

        hrEDetailsPhilHealthLbl.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        hrEDetailsPhilHealthLbl.setForeground(new java.awt.Color(31, 41, 55));
        hrEDetailsPhilHealthLbl.setText("PhilHealth");

        hrEDetailsIFNameFld.setForeground(new java.awt.Color(30, 42, 56));
        hrEDetailsIFNameFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        hrEDetailsIFNameFld.setCaretColor(new java.awt.Color(31, 41, 55));
        hrEDetailsIFNameFld.setDisabledTextColor(new java.awt.Color(31, 41, 55));
        hrEDetailsIFNameFld.setEnabled(false);
        hrEDetailsIFNameFld.addActionListener(this::hrEDetailsIFNameFldActionPerformed);

        hrEDetailsISupervisorLbl.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        hrEDetailsISupervisorLbl.setForeground(new java.awt.Color(31, 41, 55));
        hrEDetailsISupervisorLbl.setText("Immediate Supervisor");

        hrEDetailsIPhnNumberFld.setForeground(new java.awt.Color(30, 42, 56));
        hrEDetailsIPhnNumberFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        hrEDetailsIPhnNumberFld.setCaretColor(new java.awt.Color(31, 41, 55));
        hrEDetailsIPhnNumberFld.setDisabledTextColor(new java.awt.Color(31, 41, 55));
        hrEDetailsIPhnNumberFld.setEnabled(false);
        hrEDetailsIPhnNumberFld.addActionListener(this::hrEDetailsIPhnNumberFldActionPerformed);

        hrEDetailsISupervisorFld.setForeground(new java.awt.Color(30, 42, 56));
        hrEDetailsISupervisorFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        hrEDetailsISupervisorFld.setCaretColor(new java.awt.Color(31, 41, 55));
        hrEDetailsISupervisorFld.setDisabledTextColor(new java.awt.Color(31, 41, 55));
        hrEDetailsISupervisorFld.setEnabled(false);
        hrEDetailsISupervisorFld.addActionListener(this::hrEDetailsISupervisorFldActionPerformed);

        hrEDetailsRiceSubsidyFld.setForeground(new java.awt.Color(30, 42, 56));
        hrEDetailsRiceSubsidyFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        hrEDetailsRiceSubsidyFld.setCaretColor(new java.awt.Color(31, 41, 55));
        hrEDetailsRiceSubsidyFld.setDisabledTextColor(new java.awt.Color(31, 41, 55));
        hrEDetailsRiceSubsidyFld.setEnabled(false);
        hrEDetailsRiceSubsidyFld.addActionListener(this::hrEDetailsRiceSubsidyFldActionPerformed);

        hrEDetailsCltAllowanceFld.setForeground(new java.awt.Color(30, 42, 56));
        hrEDetailsCltAllowanceFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        hrEDetailsCltAllowanceFld.setCaretColor(new java.awt.Color(31, 41, 55));
        hrEDetailsCltAllowanceFld.setDisabledTextColor(new java.awt.Color(31, 41, 55));
        hrEDetailsCltAllowanceFld.setEnabled(false);
        hrEDetailsCltAllowanceFld.addActionListener(this::hrEDetailsCltAllowanceFldActionPerformed);

        hrEDetailsTINFld.setForeground(new java.awt.Color(30, 42, 56));
        hrEDetailsTINFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        hrEDetailsTINFld.setCaretColor(new java.awt.Color(31, 41, 55));
        hrEDetailsTINFld.setDisabledTextColor(new java.awt.Color(31, 41, 55));
        hrEDetailsTINFld.setEnabled(false);
        hrEDetailsTINFld.addActionListener(this::hrEDetailsTINFldActionPerformed);

        hrEDetailsPagIbigFld.setForeground(new java.awt.Color(30, 42, 56));
        hrEDetailsPagIbigFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        hrEDetailsPagIbigFld.setCaretColor(new java.awt.Color(31, 41, 55));
        hrEDetailsPagIbigFld.setDisabledTextColor(new java.awt.Color(31, 41, 55));
        hrEDetailsPagIbigFld.setEnabled(false);
        hrEDetailsPagIbigFld.addActionListener(this::hrEDetailsPagIbigFldActionPerformed);

        hrEDetailsIFNameLbl.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        hrEDetailsIFNameLbl.setForeground(new java.awt.Color(31, 41, 55));
        hrEDetailsIFNameLbl.setText("First Name");

        hrEDetailsIPhnNumberLbl.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        hrEDetailsIPhnNumberLbl.setForeground(new java.awt.Color(31, 41, 55));
        hrEDetailsIPhnNumberLbl.setText("Phone Number");

        hrEDetailsRiceSubsidyLbl.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        hrEDetailsRiceSubsidyLbl.setForeground(new java.awt.Color(31, 41, 55));
        hrEDetailsRiceSubsidyLbl.setText("Rice Subsidy");

        hrEDetailsCltAllowanceLbl.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        hrEDetailsCltAllowanceLbl.setForeground(new java.awt.Color(31, 41, 55));
        hrEDetailsCltAllowanceLbl.setText("Clothing Allowance");

        hrEDetailsTINLbl.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        hrEDetailsTINLbl.setForeground(new java.awt.Color(31, 41, 55));
        hrEDetailsTINLbl.setText("TIN");

        hrEDetailsPagIbigLbl.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        hrEDetailsPagIbigLbl.setForeground(new java.awt.Color(31, 41, 55));
        hrEDetailsPagIbigLbl.setText("Pag-Ibig");

        hrEDetailsIStatusLbl.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        hrEDetailsIStatusLbl.setForeground(new java.awt.Color(31, 41, 55));
        hrEDetailsIStatusLbl.setText("Status");

        hrAEmployeeBirthdayDtChsr.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        hrAEmployeeBirthdayDtChsr.setForeground(new java.awt.Color(31, 41, 55));
        hrAEmployeeBirthdayDtChsr.setEnabled(false);

        hrEDetailsIStatusCbx.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        hrEDetailsIStatusCbx.setForeground(new java.awt.Color(31, 41, 55));
        hrEDetailsIStatusCbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose", "Regular", "Probationary" }));
        hrEDetailsIStatusCbx.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        hrEDetailsIStatusCbx.setEnabled(false);

        javax.swing.GroupLayout hrEDetailsEDetailsBrdrPnlLayout = new javax.swing.GroupLayout(hrEDetailsEDetailsBrdrPnl);
        hrEDetailsEDetailsBrdrPnl.setLayout(hrEDetailsEDetailsBrdrPnlLayout);
        hrEDetailsEDetailsBrdrPnlLayout.setHorizontalGroup(
            hrEDetailsEDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hrEDetailsEDetailsBrdrPnlLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(hrEDetailsEDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hrEDetailsENumberLbl)
                    .addComponent(hrEDetailsLNameLbl)
                    .addComponent(hrEDetailsAddressLbl)
                    .addComponent(hrEDetailsBirthdayLbl)
                    .addComponent(hrEDetailsPositionLbl)
                    .addComponent(hrEDetailsBasicSalaryLbl)
                    .addComponent(hrEDetailsPhnAllowanceLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hrEDetailsSSSLbl)
                    .addComponent(hrEDetailsPhilHealthLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(hrEDetailsEDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(hrEDetailsEDetailsBrdrPnlLayout.createSequentialGroup()
                        .addGroup(hrEDetailsEDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(hrAEmployeeBirthdayDtChsr, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                            .addComponent(hrEDetailsPhilHealthFld)
                            .addComponent(hrEDetailsSSSFld)
                            .addComponent(hrEDetailsPhnAllowanceFld)
                            .addComponent(hrEDetailsBasicSalaryFld)
                            .addComponent(hrEDetailsPositionFld)
                            .addComponent(hrEDetailsENumberFld))
                        .addGap(18, 18, 18)
                        .addGroup(hrEDetailsEDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hrEDetailsRiceSubsidyLbl)
                            .addComponent(hrEDetailsCltAllowanceLbl)
                            .addComponent(hrEDetailsTINLbl)
                            .addComponent(hrEDetailsPagIbigLbl)
                            .addComponent(hrEDetailsIStatusLbl)
                            .addComponent(hrEDetailsISupervisorLbl)
                            .addComponent(hrEDetailsIPhnNumberLbl))
                        .addGroup(hrEDetailsEDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(hrEDetailsEDetailsBrdrPnlLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(hrEDetailsEDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(hrEDetailsPagIbigFld, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                                    .addComponent(hrEDetailsTINFld, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(hrEDetailsCltAllowanceFld, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(hrEDetailsRiceSubsidyFld, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(hrEDetailsISupervisorFld, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(hrEDetailsIPhnNumberFld, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(hrEDetailsEDetailsBrdrPnlLayout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(hrEDetailsIStatusCbx, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(hrEDetailsEDetailsBrdrPnlLayout.createSequentialGroup()
                        .addComponent(hrEDetailsLNameFld, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(hrEDetailsIFNameLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(hrEDetailsIFNameFld, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(hrEDetailsAddressFld))
                .addGap(16, 16, 16))
        );
        hrEDetailsEDetailsBrdrPnlLayout.setVerticalGroup(
            hrEDetailsEDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hrEDetailsEDetailsBrdrPnlLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(hrEDetailsEDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hrEDetailsENumberLbl)
                    .addComponent(hrEDetailsENumberFld, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hrEDetailsIStatusLbl)
                    .addComponent(hrEDetailsIStatusCbx, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(hrEDetailsEDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hrEDetailsLNameFld, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hrEDetailsLNameLbl)
                    .addComponent(hrEDetailsIFNameLbl)
                    .addComponent(hrEDetailsIFNameFld, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(hrEDetailsEDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hrEDetailsAddressFld, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hrEDetailsAddressLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(hrEDetailsEDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(hrEDetailsEDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(hrEDetailsBirthdayLbl)
                        .addComponent(hrEDetailsIPhnNumberFld, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(hrEDetailsIPhnNumberLbl))
                    .addComponent(hrAEmployeeBirthdayDtChsr, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(hrEDetailsEDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(hrEDetailsEDetailsBrdrPnlLayout.createSequentialGroup()
                        .addGroup(hrEDetailsEDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hrEDetailsPositionFld, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hrEDetailsPositionLbl)
                            .addComponent(hrEDetailsISupervisorFld, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hrEDetailsISupervisorLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(hrEDetailsEDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hrEDetailsBasicSalaryFld, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hrEDetailsBasicSalaryLbl)
                            .addComponent(hrEDetailsRiceSubsidyFld, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(hrEDetailsRiceSubsidyLbl, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(hrEDetailsEDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hrEDetailsPhnAllowanceFld, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hrEDetailsPhnAllowanceLbl)
                    .addComponent(hrEDetailsCltAllowanceFld, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hrEDetailsCltAllowanceLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(hrEDetailsEDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hrEDetailsSSSFld, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hrEDetailsSSSLbl)
                    .addComponent(hrEDetailsTINFld, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hrEDetailsTINLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(hrEDetailsEDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hrEDetailsPhilHealthFld, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hrEDetailsPhilHealthLbl)
                    .addComponent(hrEDetailsPagIbigFld, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hrEDetailsPagIbigLbl))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        hrEDetailsENumberLbl.getAccessibleContext().setAccessibleName("hrEDetailsENumberLbl");
        hrEDetailsLNameLbl.getAccessibleContext().setAccessibleName("hrEDetailsLNameLbl");
        hrEDetailsAddressLbl.getAccessibleContext().setAccessibleName("hrEDetailsAddressLbl");
        hrEDetailsBirthdayLbl.getAccessibleContext().setAccessibleName("hrEDetailsBirthdayLbl");
        hrEDetailsENumberFld.getAccessibleContext().setAccessibleName("hrEDetailsENumberFld");
        hrEDetailsAddressFld.getAccessibleContext().setAccessibleName("hrEDetailsAddressFld");
        hrEDetailsLNameFld.getAccessibleContext().setAccessibleName("hrEDetailsLNameFld");
        hrEDetailsPositionFld.getAccessibleContext().setAccessibleName("hrEDetailsPositionFld");
        hrEDetailsBasicSalaryFld.getAccessibleContext().setAccessibleName("hrEDetailsBasicSalaryFld");
        hrEDetailsPhnAllowanceFld.getAccessibleContext().setAccessibleName("hrEDetailsPhnAllowanceFld");
        hrEDetailsPositionLbl.getAccessibleContext().setAccessibleName("hrEDetailsPositionLbl");
        hrEDetailsBasicSalaryLbl.getAccessibleContext().setAccessibleName("hrEDetailsBasicSalaryLbl");
        hrEDetailsPhnAllowanceLbl.getAccessibleContext().setAccessibleName("hrEDetailsPhnAllowanceLbl");
        hrEDetailsSSSFld.getAccessibleContext().setAccessibleName("hrEDetailsSSSFld");
        hrEDetailsPhilHealthFld.getAccessibleContext().setAccessibleName("hrEDetailsPhilHealthFld");
        hrEDetailsSSSLbl.getAccessibleContext().setAccessibleName("hrEDetailsSSSLbl");
        hrEDetailsPhilHealthLbl.getAccessibleContext().setAccessibleName("hrEDetailsPhilHealthLbl");
        hrEDetailsIFNameFld.getAccessibleContext().setAccessibleName("hrEDetailsIFNameFld");
        hrEDetailsISupervisorLbl.getAccessibleContext().setAccessibleName("hrEDetailsISupervisorLbl");
        hrEDetailsIPhnNumberFld.getAccessibleContext().setAccessibleName("hrEDetailsIPhnNumberFld");
        hrEDetailsISupervisorFld.getAccessibleContext().setAccessibleName("hrEDetailsISupervisorFld");
        hrEDetailsRiceSubsidyFld.getAccessibleContext().setAccessibleName("hrEDetailsRiceSubsidyFld");
        hrEDetailsCltAllowanceFld.getAccessibleContext().setAccessibleName("hrEDetailsCltAllowanceFld");
        hrEDetailsTINFld.getAccessibleContext().setAccessibleName("hrEDetailsTINFld");
        hrEDetailsPagIbigFld.getAccessibleContext().setAccessibleName("hrEDetailsPagIbigFld");
        hrEDetailsIFNameLbl.getAccessibleContext().setAccessibleName("hrEDetailsIFNameLbl");
        hrEDetailsIPhnNumberLbl.getAccessibleContext().setAccessibleName("hrEDetailsIPhnNumberLbl");
        hrEDetailsRiceSubsidyLbl.getAccessibleContext().setAccessibleName("hrEDetailsRiceSubsidyLbl");
        hrEDetailsCltAllowanceLbl.getAccessibleContext().setAccessibleName("hrEDetailsCltAllowanceLbl");
        hrEDetailsTINLbl.getAccessibleContext().setAccessibleName("hrEDetailsTINLbl");
        hrEDetailsPagIbigLbl.getAccessibleContext().setAccessibleName("hrEDetailsPagIbigLbl");
        hrEDetailsIStatusLbl.getAccessibleContext().setAccessibleName("hrEDetailsIStatusLbl");
        hrEDetailsIStatusCbx.getAccessibleContext().setAccessibleName("hrEDetailsIStatusCbx");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(hrEDetailsSidebarPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(hrEDetailsEDetailsPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(hrEDetailsSearchPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(hrEDetailsEditBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(142, 142, 142)
                            .addComponent(hrEDetailsAddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hrEDetailsDeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(hrEDetailsEDetailsBrdrPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hrEDetailsEDetailsPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hrEDetailsSearchPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(hrEDetailsEDetailsBrdrPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hrEDetailsEditBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hrEDetailsAddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hrEDetailsDeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(hrEDetailsSidebarPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        hrEDetailsSidebarPnl.getAccessibleContext().setAccessibleName("hrEDetailsSidebarPnl");
        hrEDetailsEDetailsPnl.getAccessibleContext().setAccessibleName("hrEDetailsEDetailsPnl");
        hrEDetailsAddBtn.getAccessibleContext().setAccessibleName("hrEDetailsAddBtn");
        hrEDetailsEditBtn.getAccessibleContext().setAccessibleName("hrEDetailsEditBtn");
        hrEDetailsDeleteBtn.getAccessibleContext().setAccessibleName("hrEDetailsDeleteBtn");
        hrEDetailsEDetailsBrdrPnl.getAccessibleContext().setAccessibleName("hrEDetailsEDetailsBrdrPnl");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void hrEDetailsEDetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrEDetailsEDetailsBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hrEDetailsEDetailsBtnActionPerformed

    private void hrEDetailsEditBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrEDetailsEditBtnActionPerformed
        // TODO add your handling code here:
        Employee emp = null;
        
        try {
            emp = empService.findEmployee(hrEDetailsENumberFld.getText());


            if (emp == null) {
                throw new IllegalArgumentException("Enter employee number to edit.");
            }
            
            this.dispose();
            new HREditEmployeeUI(emp).setVisible(true);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
        
        
        
        
    }//GEN-LAST:event_hrEDetailsEditBtnActionPerformed

    private void hrEDetailsAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrEDetailsAddBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
        new HRAddEmployeeUI().setVisible(true);
    }//GEN-LAST:event_hrEDetailsAddBtnActionPerformed

    private void hrEDetailsDeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrEDetailsDeleteBtnActionPerformed
        // TODO add your handling code here:
        try { 
            String employeeNumber = hrEDetailsENumberFld.getText().trim();
            
            if (employeeNumber == null || employeeNumber.isEmpty()) {
                throw new IllegalArgumentException("Enter employee number to delete.");
            }
            
            
             // The message you want to display in the dialog
            String message = "Do you want to delete " + employeeNumber + " ?";
            // The title for the dialog window
            String title = "Confirmation";

            // Display the dialog and store the result
            int reply = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION);

            // Check the user's choice
            if (reply == JOptionPane.YES_OPTION) {
                empService.deleteEmployee(employeeNumber);
                JOptionPane.showMessageDialog(null, "Deleted employee " + employeeNumber);
                
            } else if (reply == JOptionPane.NO_OPTION) {
                JOptionPane.showMessageDialog(null, "You clicked No. Exiting.");
                
            } else {
                // This handles the case where the user closes the dialog without pressing Yes or No
                JOptionPane.showMessageDialog(null, "Dialog closed without a choice.");
            }
        
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
    }//GEN-LAST:event_hrEDetailsDeleteBtnActionPerformed

    private void hrEDetailsEntENumberFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrEDetailsEntENumberFldActionPerformed
        // TODO add your handling code here:
        performSearch();
    }//GEN-LAST:event_hrEDetailsEntENumberFldActionPerformed

    private void hrEDetailsMainDashboardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrEDetailsMainDashboardBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new MainDashboardUI().setVisible(true);
    }//GEN-LAST:event_hrEDetailsMainDashboardBtnActionPerformed

    private void hrEDetailsENumberFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrEDetailsENumberFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hrEDetailsENumberFldActionPerformed

    private void hrEDetailsAddressFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrEDetailsAddressFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hrEDetailsAddressFldActionPerformed

    private void hrEDetailsLNameFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrEDetailsLNameFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hrEDetailsLNameFldActionPerformed

    private void hrEDetailsPositionFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrEDetailsPositionFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hrEDetailsPositionFldActionPerformed

    private void hrEDetailsBasicSalaryFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrEDetailsBasicSalaryFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hrEDetailsBasicSalaryFldActionPerformed

    private void hrEDetailsPhnAllowanceFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrEDetailsPhnAllowanceFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hrEDetailsPhnAllowanceFldActionPerformed

    private void hrEDetailsSSSFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrEDetailsSSSFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hrEDetailsSSSFldActionPerformed

    private void hrEDetailsPhilHealthFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrEDetailsPhilHealthFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hrEDetailsPhilHealthFldActionPerformed

    private void hrEDetailsIFNameFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrEDetailsIFNameFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hrEDetailsIFNameFldActionPerformed

    private void hrEDetailsIPhnNumberFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrEDetailsIPhnNumberFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hrEDetailsIPhnNumberFldActionPerformed

    private void hrEDetailsISupervisorFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrEDetailsISupervisorFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hrEDetailsISupervisorFldActionPerformed

    private void hrEDetailsRiceSubsidyFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrEDetailsRiceSubsidyFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hrEDetailsRiceSubsidyFldActionPerformed

    private void hrEDetailsCltAllowanceFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrEDetailsCltAllowanceFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hrEDetailsCltAllowanceFldActionPerformed

    private void hrEDetailsTINFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrEDetailsTINFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hrEDetailsTINFldActionPerformed

    private void hrEDetailsPagIbigFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrEDetailsPagIbigFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hrEDetailsPagIbigFldActionPerformed

    private void hrEDetailsSearchIconImgLblKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hrEDetailsSearchIconImgLblKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_hrEDetailsSearchIconImgLblKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new HREmployeeDetailsUI().setVisible(true));
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private com.toedter.calendar.JDateChooser hrAEmployeeBirthdayDtChsr;
    private javax.swing.JButton hrEDetailsAddBtn;
    private javax.swing.JTextField hrEDetailsAddressFld;
    private javax.swing.JLabel hrEDetailsAddressLbl;
    private javax.swing.JTextField hrEDetailsBasicSalaryFld;
    private javax.swing.JLabel hrEDetailsBasicSalaryLbl;
    private javax.swing.JLabel hrEDetailsBirthdayLbl;
    private javax.swing.JTextField hrEDetailsCltAllowanceFld;
    private javax.swing.JLabel hrEDetailsCltAllowanceLbl;
    private javax.swing.JButton hrEDetailsDeleteBtn;
    private javax.swing.JPanel hrEDetailsEDetailsBrdrPnl;
    private javax.swing.JButton hrEDetailsEDetailsBtn;
    private javax.swing.JLabel hrEDetailsEDetailsLbl;
    private javax.swing.JPanel hrEDetailsEDetailsPnl;
    private javax.swing.JTextField hrEDetailsENumberFld;
    private javax.swing.JLabel hrEDetailsENumberLbl;
    private javax.swing.JButton hrEDetailsEditBtn;
    private javax.swing.JTextField hrEDetailsEntENumberFld;
    private javax.swing.JTextField hrEDetailsIFNameFld;
    private javax.swing.JLabel hrEDetailsIFNameLbl;
    private javax.swing.JTextField hrEDetailsIPhnNumberFld;
    private javax.swing.JLabel hrEDetailsIPhnNumberLbl;
    private javax.swing.JComboBox<String> hrEDetailsIStatusCbx;
    private javax.swing.JLabel hrEDetailsIStatusLbl;
    private javax.swing.JTextField hrEDetailsISupervisorFld;
    private javax.swing.JLabel hrEDetailsISupervisorLbl;
    private javax.swing.JTextField hrEDetailsLNameFld;
    private javax.swing.JLabel hrEDetailsLNameLbl;
    private javax.swing.JButton hrEDetailsMainDashboardBtn;
    private javax.swing.JLabel hrEDetailsMotorPHIconImgLbl;
    private javax.swing.JTextField hrEDetailsPagIbigFld;
    private javax.swing.JLabel hrEDetailsPagIbigLbl;
    private javax.swing.JTextField hrEDetailsPhilHealthFld;
    private javax.swing.JLabel hrEDetailsPhilHealthLbl;
    private javax.swing.JTextField hrEDetailsPhnAllowanceFld;
    private javax.swing.JLabel hrEDetailsPhnAllowanceLbl;
    private javax.swing.JTextField hrEDetailsPositionFld;
    private javax.swing.JLabel hrEDetailsPositionLbl;
    private javax.swing.JTextField hrEDetailsRiceSubsidyFld;
    private javax.swing.JLabel hrEDetailsRiceSubsidyLbl;
    private javax.swing.JTextField hrEDetailsSSSFld;
    private javax.swing.JLabel hrEDetailsSSSLbl;
    private javax.swing.JLabel hrEDetailsSearchIconImgLbl;
    private javax.swing.JPanel hrEDetailsSearchPnl;
    private javax.swing.JPanel hrEDetailsSidebarPnl;
    private javax.swing.JTextField hrEDetailsTINFld;
    private javax.swing.JLabel hrEDetailsTINLbl;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
