
package com.motorph.ui;

import com.motorph.model.LeaveRequest;
import com.motorph.service.LeaveService;
import com.motorph.util.AppContext;
import com.motorph.util.DateUtils;
import com.motorph.util.GuiUtil;
import com.motorph.util.Session;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class HRLeaveDetailsUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HRLeaveDetailsUI.class.getName());
    private LeaveService leaveService;
    private LeaveRequest request;
    /**
     * Creates new form HRLeaveListFrame
     */
    public HRLeaveDetailsUI(LeaveRequest request) {
        this.leaveService = AppContext.getLeaveService();
        this.request = request;
        initComponents();
        populateFields(request);
    }
    
    private void populateFields(LeaveRequest request) {
        hrRDetailsLTypeFld.setText(request.getLeaveType().toString());
        hrRDetailsLTypeFld1.setText(DateUtils.dateToString(request.getStartDate()));
        hrRDetailsLTypeFld2.setText(DateUtils.dateToString(request.getEndDate()));
        hrLDetailsReasonFld.setText(request.getReason());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hrLDetailsSidebarPnl = new javax.swing.JPanel();
        mainDashboardBtn = new javax.swing.JButton();
        hrLDetailsMotorPHIconImgLbl = new javax.swing.JLabel();
        hrLDetailsLListPnl = new javax.swing.JPanel();
        hrLDetailsLListLbl = new javax.swing.JLabel();
        hrLDetailsLFormBrdrPnl = new javax.swing.JPanel();
        hrLDetailsLFormPnl = new javax.swing.JPanel();
        hrLDetailsLFormLbl = new javax.swing.JLabel();
        hrLDetailsFALeaveBrdrPnl = new javax.swing.JPanel();
        hrLDetailsFALeavePnl = new javax.swing.JPanel();
        hrLDetailsFALeaveLbl = new javax.swing.JLabel();
        hrLDetailsReasonLbl = new javax.swing.JLabel();
        hrLDetailsToLbl = new javax.swing.JLabel();
        hrLDetailsReasonFld = new javax.swing.JTextField();
        hrLDetailsFromLbl = new javax.swing.JLabel();
        hrRDetailsLTypeFld = new javax.swing.JTextField();
        hrRDetailsLTypeFld1 = new javax.swing.JTextField();
        hrRDetailsLTypeFld2 = new javax.swing.JTextField();
        hrLDetailsApproveBtn = new javax.swing.JButton();
        hrLDetailsDenyBtn = new javax.swing.JButton();
        hrLDetailsBackBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        hrLDetailsSidebarPnl.setBackground(new java.awt.Color(30, 58, 138));

        mainDashboardBtn.setBackground(new java.awt.Color(30, 42, 56));
        mainDashboardBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        mainDashboardBtn.setForeground(new java.awt.Color(255, 255, 255));
        mainDashboardBtn.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        mainDashboardBtn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        mainDashboardBtn.setLabel("Main Dashboard");
        mainDashboardBtn.addActionListener(this::mainDashboardBtnActionPerformed);

        hrLDetailsMotorPHIconImgLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/motorph/img/MotorPHIconImg.png"))); // NOI18N

        javax.swing.GroupLayout hrLDetailsSidebarPnlLayout = new javax.swing.GroupLayout(hrLDetailsSidebarPnl);
        hrLDetailsSidebarPnl.setLayout(hrLDetailsSidebarPnlLayout);
        hrLDetailsSidebarPnlLayout.setHorizontalGroup(
            hrLDetailsSidebarPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hrLDetailsSidebarPnlLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(mainDashboardBtn))
            .addGroup(hrLDetailsSidebarPnlLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(hrLDetailsMotorPHIconImgLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        hrLDetailsSidebarPnlLayout.setVerticalGroup(
            hrLDetailsSidebarPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hrLDetailsSidebarPnlLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(hrLDetailsMotorPHIconImgLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mainDashboardBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        hrLDetailsMotorPHIconImgLbl.getAccessibleContext().setAccessibleName("hrLDetailsMotorPHIconImgLbl");

        hrLDetailsLListPnl.setBackground(new java.awt.Color(30, 58, 138));
        hrLDetailsLListPnl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        hrLDetailsLListPnl.setForeground(new java.awt.Color(30, 58, 138));

        hrLDetailsLListLbl.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        hrLDetailsLListLbl.setForeground(new java.awt.Color(255, 255, 255));
        hrLDetailsLListLbl.setText(" Leave Details");

        javax.swing.GroupLayout hrLDetailsLListPnlLayout = new javax.swing.GroupLayout(hrLDetailsLListPnl);
        hrLDetailsLListPnl.setLayout(hrLDetailsLListPnlLayout);
        hrLDetailsLListPnlLayout.setHorizontalGroup(
            hrLDetailsLListPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hrLDetailsLListPnlLayout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(hrLDetailsLListLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        hrLDetailsLListPnlLayout.setVerticalGroup(
            hrLDetailsLListPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(hrLDetailsLListLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        hrLDetailsLListLbl.getAccessibleContext().setAccessibleName("hrLDetailsLListLbl");

        hrLDetailsLFormBrdrPnl.setBackground(new java.awt.Color(255, 255, 255));
        hrLDetailsLFormBrdrPnl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 2, true));

        hrLDetailsLFormPnl.setBackground(new java.awt.Color(30, 58, 138));
        hrLDetailsLFormPnl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        hrLDetailsLFormPnl.setForeground(new java.awt.Color(30, 58, 138));
        hrLDetailsLFormPnl.setPreferredSize(new java.awt.Dimension(126, 40));

        hrLDetailsLFormLbl.setBackground(new java.awt.Color(255, 255, 255));
        hrLDetailsLFormLbl.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        hrLDetailsLFormLbl.setForeground(new java.awt.Color(255, 255, 255));
        hrLDetailsLFormLbl.setText("Leave Form");
        hrLDetailsLFormLbl.setToolTipText("");

        javax.swing.GroupLayout hrLDetailsLFormPnlLayout = new javax.swing.GroupLayout(hrLDetailsLFormPnl);
        hrLDetailsLFormPnl.setLayout(hrLDetailsLFormPnlLayout);
        hrLDetailsLFormPnlLayout.setHorizontalGroup(
            hrLDetailsLFormPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hrLDetailsLFormPnlLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(hrLDetailsLFormLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        hrLDetailsLFormPnlLayout.setVerticalGroup(
            hrLDetailsLFormPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hrLDetailsLFormPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hrLDetailsLFormLbl)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        hrLDetailsLFormLbl.getAccessibleContext().setAccessibleName("hrLDetailsLFormLbl");

        hrLDetailsFALeaveBrdrPnl.setBackground(new java.awt.Color(233, 233, 233));
        hrLDetailsFALeaveBrdrPnl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        hrLDetailsFALeaveBrdrPnl.setForeground(new java.awt.Color(0, 0, 0));

        hrLDetailsFALeavePnl.setBackground(new java.awt.Color(146, 192, 253));
        hrLDetailsFALeavePnl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        hrLDetailsFALeavePnl.setForeground(new java.awt.Color(30, 58, 138));
        hrLDetailsFALeavePnl.setPreferredSize(new java.awt.Dimension(126, 40));

        hrLDetailsFALeaveLbl.setBackground(new java.awt.Color(255, 255, 255));
        hrLDetailsFALeaveLbl.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        hrLDetailsFALeaveLbl.setForeground(new java.awt.Color(31, 41, 55));
        hrLDetailsFALeaveLbl.setText(" Leave Type");
        hrLDetailsFALeaveLbl.setToolTipText("");

        javax.swing.GroupLayout hrLDetailsFALeavePnlLayout = new javax.swing.GroupLayout(hrLDetailsFALeavePnl);
        hrLDetailsFALeavePnl.setLayout(hrLDetailsFALeavePnlLayout);
        hrLDetailsFALeavePnlLayout.setHorizontalGroup(
            hrLDetailsFALeavePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hrLDetailsFALeavePnlLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(hrLDetailsFALeaveLbl)
                .addGap(21, 21, 21))
        );
        hrLDetailsFALeavePnlLayout.setVerticalGroup(
            hrLDetailsFALeavePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(hrLDetailsFALeaveLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        hrLDetailsFALeaveLbl.getAccessibleContext().setAccessibleName("hrLDetailsFALeaveLbl");

        hrLDetailsReasonLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        hrLDetailsReasonLbl.setForeground(new java.awt.Color(31, 41, 55));
        hrLDetailsReasonLbl.setText("Reason");

        hrLDetailsToLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        hrLDetailsToLbl.setForeground(new java.awt.Color(31, 41, 55));
        hrLDetailsToLbl.setText("To");

        hrLDetailsReasonFld.setForeground(new java.awt.Color(31, 41, 55));
        hrLDetailsReasonFld.setText(" ");
        hrLDetailsReasonFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        hrLDetailsReasonFld.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        hrLDetailsReasonFld.setEnabled(false);
        hrLDetailsReasonFld.addActionListener(this::hrLDetailsReasonFldActionPerformed);

        hrLDetailsFromLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        hrLDetailsFromLbl.setForeground(new java.awt.Color(31, 41, 55));
        hrLDetailsFromLbl.setText("From");

        hrRDetailsLTypeFld.setForeground(new java.awt.Color(0, 0, 0));
        hrRDetailsLTypeFld.setText(" ");
        hrRDetailsLTypeFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        hrRDetailsLTypeFld.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        hrRDetailsLTypeFld.setEnabled(false);
        hrRDetailsLTypeFld.setSelectionColor(new java.awt.Color(0, 0, 0));
        hrRDetailsLTypeFld.addActionListener(this::hrRDetailsLTypeFldActionPerformed);

        hrRDetailsLTypeFld1.setForeground(new java.awt.Color(0, 0, 0));
        hrRDetailsLTypeFld1.setText(" ");
        hrRDetailsLTypeFld1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        hrRDetailsLTypeFld1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        hrRDetailsLTypeFld1.setEnabled(false);
        hrRDetailsLTypeFld1.setSelectionColor(new java.awt.Color(0, 0, 0));
        hrRDetailsLTypeFld1.addActionListener(this::hrRDetailsLTypeFld1ActionPerformed);

        hrRDetailsLTypeFld2.setForeground(new java.awt.Color(0, 0, 0));
        hrRDetailsLTypeFld2.setText(" ");
        hrRDetailsLTypeFld2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        hrRDetailsLTypeFld2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        hrRDetailsLTypeFld2.setEnabled(false);
        hrRDetailsLTypeFld2.setSelectionColor(new java.awt.Color(0, 0, 0));
        hrRDetailsLTypeFld2.addActionListener(this::hrRDetailsLTypeFld2ActionPerformed);

        javax.swing.GroupLayout hrLDetailsFALeaveBrdrPnlLayout = new javax.swing.GroupLayout(hrLDetailsFALeaveBrdrPnl);
        hrLDetailsFALeaveBrdrPnl.setLayout(hrLDetailsFALeaveBrdrPnlLayout);
        hrLDetailsFALeaveBrdrPnlLayout.setHorizontalGroup(
            hrLDetailsFALeaveBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hrLDetailsFALeaveBrdrPnlLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(hrLDetailsFALeaveBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(hrLDetailsFALeaveBrdrPnlLayout.createSequentialGroup()
                        .addGroup(hrLDetailsFALeaveBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hrLDetailsFromLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hrLDetailsReasonLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hrLDetailsFALeavePnl, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(hrLDetailsFALeaveBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(hrLDetailsFALeaveBrdrPnlLayout.createSequentialGroup()
                                .addComponent(hrRDetailsLTypeFld1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(hrLDetailsToLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(hrRDetailsLTypeFld2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(hrRDetailsLTypeFld, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(hrLDetailsReasonFld, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 21, Short.MAX_VALUE))
        );
        hrLDetailsFALeaveBrdrPnlLayout.setVerticalGroup(
            hrLDetailsFALeaveBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hrLDetailsFALeaveBrdrPnlLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(hrLDetailsFALeaveBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(hrLDetailsFALeavePnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hrRDetailsLTypeFld, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(hrLDetailsFALeaveBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(hrLDetailsFALeaveBrdrPnlLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hrRDetailsLTypeFld2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(hrLDetailsFALeaveBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hrLDetailsFALeaveBrdrPnlLayout.createSequentialGroup()
                            .addGap(23, 23, 23)
                            .addComponent(hrLDetailsToLbl))
                        .addGroup(hrLDetailsFALeaveBrdrPnlLayout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addGroup(hrLDetailsFALeaveBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(hrLDetailsFromLbl)
                                .addComponent(hrRDetailsLTypeFld1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hrLDetailsReasonLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hrLDetailsReasonFld, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        hrLDetailsFALeavePnl.getAccessibleContext().setAccessibleName("hrLDetailsFALeavePnl");
        hrLDetailsReasonLbl.getAccessibleContext().setAccessibleName("hrLDetailsReasonLbl");
        hrLDetailsToLbl.getAccessibleContext().setAccessibleName("hrLDetailsToLbl");
        hrLDetailsReasonFld.getAccessibleContext().setAccessibleName("hrLDetailsReasonFld");
        hrLDetailsFromLbl.getAccessibleContext().setAccessibleName("hrLDetailsFromLbl");

        javax.swing.GroupLayout hrLDetailsLFormBrdrPnlLayout = new javax.swing.GroupLayout(hrLDetailsLFormBrdrPnl);
        hrLDetailsLFormBrdrPnl.setLayout(hrLDetailsLFormBrdrPnlLayout);
        hrLDetailsLFormBrdrPnlLayout.setHorizontalGroup(
            hrLDetailsLFormBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hrLDetailsLFormBrdrPnlLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(hrLDetailsLFormPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(260, 260, 260))
            .addGroup(hrLDetailsLFormBrdrPnlLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(hrLDetailsFALeaveBrdrPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        hrLDetailsLFormBrdrPnlLayout.setVerticalGroup(
            hrLDetailsLFormBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hrLDetailsLFormBrdrPnlLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(hrLDetailsLFormPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hrLDetailsFALeaveBrdrPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        hrLDetailsLFormPnl.getAccessibleContext().setAccessibleName("hrLDetailsLFormPnl");
        hrLDetailsFALeaveBrdrPnl.getAccessibleContext().setAccessibleName("hrLDetailsFALeaveBrdrPnl");

        hrLDetailsApproveBtn.setBackground(new java.awt.Color(34, 197, 94));
        hrLDetailsApproveBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        hrLDetailsApproveBtn.setForeground(new java.awt.Color(255, 255, 255));
        hrLDetailsApproveBtn.setText("Approve");
        hrLDetailsApproveBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(30, 42, 56)));
        hrLDetailsApproveBtn.addActionListener(this::hrLDetailsApproveBtnActionPerformed);

        hrLDetailsDenyBtn.setBackground(new java.awt.Color(239, 68, 68));
        hrLDetailsDenyBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        hrLDetailsDenyBtn.setForeground(new java.awt.Color(255, 255, 255));
        hrLDetailsDenyBtn.setText("Deny");
        hrLDetailsDenyBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(30, 42, 56)));
        hrLDetailsDenyBtn.addActionListener(this::hrLDetailsDenyBtnActionPerformed);

        hrLDetailsBackBtn.setBackground(new java.awt.Color(30, 58, 138));
        hrLDetailsBackBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        hrLDetailsBackBtn.setForeground(new java.awt.Color(255, 255, 255));
        hrLDetailsBackBtn.setText("Back");
        hrLDetailsBackBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        hrLDetailsBackBtn.addActionListener(this::hrLDetailsBackBtnActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(hrLDetailsSidebarPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(hrLDetailsLFormBrdrPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(hrLDetailsApproveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(hrLDetailsDenyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(362, 362, 362)
                        .addComponent(hrLDetailsBackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(hrLDetailsLListPnl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(hrLDetailsLListPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hrLDetailsLFormBrdrPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hrLDetailsBackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hrLDetailsApproveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hrLDetailsDenyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(241, Short.MAX_VALUE))
            .addComponent(hrLDetailsSidebarPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        hrLDetailsSidebarPnl.getAccessibleContext().setAccessibleName("hrLDetailsSidebarPnl");
        hrLDetailsLListPnl.getAccessibleContext().setAccessibleName("hrLDetailsLListPnl");
        hrLDetailsLFormBrdrPnl.getAccessibleContext().setAccessibleName("hrLDetailsLFormBrdrPnl");
        hrLDetailsApproveBtn.getAccessibleContext().setAccessibleName("hrLDetailsApproveBtn");
        hrLDetailsDenyBtn.getAccessibleContext().setAccessibleName("hrLDetailsDenyBtn");
        hrLDetailsBackBtn.getAccessibleContext().setAccessibleName("hrLDetailsBackBtn");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mainDashboardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainDashboardBtnActionPerformed
        // TODO add your handling code here:
        GuiUtil.openFrame(this);
    }//GEN-LAST:event_mainDashboardBtnActionPerformed

    private void hrLDetailsReasonFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrLDetailsReasonFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hrLDetailsReasonFldActionPerformed

    private void hrLDetailsApproveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrLDetailsApproveBtnActionPerformed
        // TODO add your handling code here:
        try {
            leaveService.approveLeave(request, Session.getCurrentUser().getEmployeeNumber());
            
            JOptionPane.showMessageDialog(this, "Leave Approved!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_hrLDetailsApproveBtnActionPerformed

    private void hrLDetailsDenyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrLDetailsDenyBtnActionPerformed
        // TODO add your handling code here:
        try {
            leaveService.denyLeave(request, Session.getCurrentUser().getEmployeeNumber());
            
            JOptionPane.showMessageDialog(this, "Leave Denied!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_hrLDetailsDenyBtnActionPerformed

    private void hrLDetailsBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrLDetailsBackBtnActionPerformed
        // TODO add your handling code here:
        GuiUtil.openFrame(this, new HRLeaveListUI());
       
    }//GEN-LAST:event_hrLDetailsBackBtnActionPerformed

    private void hrRDetailsLTypeFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrRDetailsLTypeFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hrRDetailsLTypeFldActionPerformed

    private void hrRDetailsLTypeFld1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrRDetailsLTypeFld1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hrRDetailsLTypeFld1ActionPerformed

    private void hrRDetailsLTypeFld2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrRDetailsLTypeFld2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hrRDetailsLTypeFld2ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton hrLDetailsApproveBtn;
    private javax.swing.JButton hrLDetailsBackBtn;
    private javax.swing.JButton hrLDetailsDenyBtn;
    private javax.swing.JPanel hrLDetailsFALeaveBrdrPnl;
    private javax.swing.JLabel hrLDetailsFALeaveLbl;
    private javax.swing.JPanel hrLDetailsFALeavePnl;
    private javax.swing.JLabel hrLDetailsFromLbl;
    private javax.swing.JPanel hrLDetailsLFormBrdrPnl;
    private javax.swing.JLabel hrLDetailsLFormLbl;
    private javax.swing.JPanel hrLDetailsLFormPnl;
    private javax.swing.JLabel hrLDetailsLListLbl;
    private javax.swing.JPanel hrLDetailsLListPnl;
    private javax.swing.JLabel hrLDetailsMotorPHIconImgLbl;
    private javax.swing.JTextField hrLDetailsReasonFld;
    private javax.swing.JLabel hrLDetailsReasonLbl;
    private javax.swing.JPanel hrLDetailsSidebarPnl;
    private javax.swing.JLabel hrLDetailsToLbl;
    private javax.swing.JTextField hrRDetailsLTypeFld;
    private javax.swing.JTextField hrRDetailsLTypeFld1;
    private javax.swing.JTextField hrRDetailsLTypeFld2;
    private javax.swing.JButton mainDashboardBtn;
    // End of variables declaration//GEN-END:variables
}
