/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.motorph.ui;

import com.motorph.model.Employee;
import com.motorph.model.LeaveRequest;
import com.motorph.model.Payslip;
import com.motorph.service.EmployeeService;
import com.motorph.service.LeaveService;
import com.motorph.util.AppContext;
import com.motorph.util.GuiUtil;
import com.motorph.util.Session;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lenovo
 */
public class HRLeaveListUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HRLeaveListUI.class.getName());
    private LeaveService leaveService;
    private EmployeeService empService;
    /**
     * Creates new form HRLeaveListFrame
     */
    public HRLeaveListUI() {
        this.leaveService = AppContext.getLeaveService();
        this.empService = AppContext.getEmployeeService();
        initComponents();
        
        if (leaveService != null && Session.getCurrentUser() != null) {
            populateLeaveRecords();
        } else {
            logger.warning("Service or Session is null! Cannot populate table.");
        }
    }
    
    private void populateLeaveRecords() {
        try {
            
            String employeeNumber = Session.getCurrentUser().getEmployeeNumber();
            Employee emp = empService.findEmployee(employeeNumber);
            
            List<LeaveRequest> list = leaveService.getAllLeave(Session.getCurrentUser().getEmployeeNumber());

            // Ensure the table model exists
            DefaultTableModel model = (DefaultTableModel) hrLListLListTbl.getModel();
            model.setRowCount(0);

            // 4. Fill the rows
            for (LeaveRequest r : list) {

                Object[] row = {
                    r.getRequestId(),
                    r.getEmployeeNumber(),
                    emp.getFullName(),
                    r.getStatus(),
                    "VIEW"
                };

                model.addRow(row);
            }
        } catch (Exception e) {
            logger.severe("Failed to populate table: " + e.getMessage());
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hrLListSidebarPnl = new javax.swing.JPanel();
        hrLListLDetailsBtn = new javax.swing.JButton();
        hrLListMainDashboardBtn = new javax.swing.JButton();
        hrLListMotorPHIconImgLbl = new javax.swing.JLabel();
        hrLListLListBtn = new javax.swing.JButton();
        hrLListLListPnl = new javax.swing.JPanel();
        hrLListLListLbl = new javax.swing.JLabel();
        hrLListLListBrdrScrlPnl = new javax.swing.JScrollPane();
        hrLListLListTbl = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        hrLListSidebarPnl.setBackground(new java.awt.Color(30, 58, 138));

        hrLListLDetailsBtn.setBackground(new java.awt.Color(30, 42, 56));
        hrLListLDetailsBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        hrLListLDetailsBtn.setForeground(new java.awt.Color(255, 255, 255));
        hrLListLDetailsBtn.setText(" Leave Details");
        hrLListLDetailsBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        hrLListLDetailsBtn.addActionListener(this::hrLListLDetailsBtnActionPerformed);

        hrLListMainDashboardBtn.setBackground(new java.awt.Color(30, 42, 56));
        hrLListMainDashboardBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        hrLListMainDashboardBtn.setForeground(new java.awt.Color(255, 255, 255));
        hrLListMainDashboardBtn.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        hrLListMainDashboardBtn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        hrLListMainDashboardBtn.setLabel("Main Dashboard");
        hrLListMainDashboardBtn.addActionListener(this::hrLListMainDashboardBtnActionPerformed);

        hrLListMotorPHIconImgLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/motorph/img/MotorPHIconImg.png"))); // NOI18N

        hrLListLListBtn.setBackground(new java.awt.Color(30, 42, 56));
        hrLListLListBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        hrLListLListBtn.setForeground(new java.awt.Color(255, 255, 255));
        hrLListLListBtn.setText(" Leave List");
        hrLListLListBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        hrLListLListBtn.addActionListener(this::hrLListLListBtnActionPerformed);

        javax.swing.GroupLayout hrLListSidebarPnlLayout = new javax.swing.GroupLayout(hrLListSidebarPnl);
        hrLListSidebarPnl.setLayout(hrLListSidebarPnlLayout);
        hrLListSidebarPnlLayout.setHorizontalGroup(
            hrLListSidebarPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hrLListSidebarPnlLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(hrLListMainDashboardBtn))
            .addGroup(hrLListSidebarPnlLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(hrLListSidebarPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hrLListLListBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(hrLListSidebarPnlLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(hrLListMotorPHIconImgLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(hrLListLDetailsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        hrLListSidebarPnlLayout.setVerticalGroup(
            hrLListSidebarPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hrLListSidebarPnlLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(hrLListSidebarPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hrLListMotorPHIconImgLbl)
                    .addGroup(hrLListSidebarPnlLayout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(hrLListLDetailsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hrLListLListBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 353, Short.MAX_VALUE)
                .addComponent(hrLListMainDashboardBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        hrLListLDetailsBtn.getAccessibleContext().setAccessibleName("hrLListLDetailsBtn");
        hrLListMainDashboardBtn.getAccessibleContext().setAccessibleName("hrLListMainDashboardBtn");
        hrLListMotorPHIconImgLbl.getAccessibleContext().setAccessibleName("hrLListMotorPHIconImgLbl");
        hrLListLListBtn.getAccessibleContext().setAccessibleName("hrLListLListBtn");

        hrLListLListPnl.setBackground(new java.awt.Color(30, 58, 138));
        hrLListLListPnl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        hrLListLListPnl.setForeground(new java.awt.Color(30, 58, 138));
        hrLListLListPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hrLListLListLbl.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        hrLListLListLbl.setForeground(new java.awt.Color(255, 255, 255));
        hrLListLListLbl.setText(" Leave List");
        hrLListLListPnl.add(hrLListLListLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 1, 140, 46));
        hrLListLListLbl.getAccessibleContext().setAccessibleName("hrLListLListLbl");

        hrLListLListBrdrScrlPnl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 2, true));

        hrLListLListTbl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        hrLListLListTbl.setForeground(new java.awt.Color(30, 42, 56));
        hrLListLListTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Leave ID", "Employee #", "Employee Name", "Status", "Leave Details"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        hrLListLListTbl.setColumnSelectionAllowed(true);
        hrLListLListTbl.setGridColor(new java.awt.Color(178, 178, 178));
        hrLListLListTbl.setSelectionForeground(new java.awt.Color(30, 42, 56));
        hrLListLListTbl.getTableHeader().setReorderingAllowed(false);
        hrLListLListTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hrLListLListTblMouseClicked(evt);
            }
        });
        hrLListLListBrdrScrlPnl.setViewportView(hrLListLListTbl);
        hrLListLListTbl.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        hrLListLListTbl.getAccessibleContext().setAccessibleName("hrLListLListTbl");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(hrLListSidebarPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hrLListLListPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hrLListLListBrdrScrlPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 711, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(hrLListLListPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hrLListLListBrdrScrlPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(hrLListSidebarPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        hrLListSidebarPnl.getAccessibleContext().setAccessibleName("hrLListSidebarPnl");
        hrLListLListPnl.getAccessibleContext().setAccessibleName("hrLListLListPnl");
        hrLListLListBrdrScrlPnl.getAccessibleContext().setAccessibleName("hrLListLListBrdrScrlPnl");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hrLListLDetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrLListLDetailsBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
        new EmployeeLeaveUI().setVisible(true);
    }//GEN-LAST:event_hrLListLDetailsBtnActionPerformed

    private void hrLListMainDashboardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrLListMainDashboardBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new MainDashboardUI().setVisible(true);
    }//GEN-LAST:event_hrLListMainDashboardBtnActionPerformed

    private void hrLListLListBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrLListLListBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hrLListLListBtnActionPerformed

    private void hrLListLListTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hrLListLListTblMouseClicked
        // TODO add your handling code here:
        
        System.out.println("EVENT TRIGGERED");
        if (evt.getClickCount() == 2) { // Check for double click
            int row = hrLDetailsLListTbl.getSelectedRow();
            String leaveId = hrLDetailsLListTbl.getValueAt(row, 0).toString().trim();
            LeaveRequest request = leaveService.findById(leaveId.trim());
            GuiUtil.openFrame(this, new HRLeaveDetailsUI(request));
        }
    }//GEN-LAST:event_hrLDetailsLListTblMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new HRLeaveListUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton hrLListLDetailsBtn;
    private javax.swing.JScrollPane hrLListLListBrdrScrlPnl;
    private javax.swing.JButton hrLListLListBtn;
    private javax.swing.JLabel hrLListLListLbl;
    private javax.swing.JPanel hrLListLListPnl;
    private javax.swing.JTable hrLListLListTbl;
    private javax.swing.JButton hrLListMainDashboardBtn;
    private javax.swing.JLabel hrLListMotorPHIconImgLbl;
    private javax.swing.JPanel hrLListSidebarPnl;
    // End of variables declaration//GEN-END:variables
}
