/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.motorph.ui;

import com.motorph.model.Employee;
import com.motorph.model.Role;
import com.motorph.model.UserAccount;
import com.motorph.service.UserManagementService;
import com.motorph.util.AppContext;
import com.motorph.util.GuiUtil;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class ITAddUserAccountUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ITAddUserAccountUI.class.getName());
    private UserAccount user;
    private UserManagementService userService;
  
    /**
     * Creates new form ITAddUserFrame
     */
    public ITAddUserAccountUI(UserAccount user, Employee emp) {
        this.user = user;
        this.userService = AppContext.getUserManagementService();
        initComponents();
        populateFields(emp);
    }
    
    
    private void populateFields(Employee emp) {
        
        itAddUAccENumberFld.setText(emp.getEmployeeNumber());
        itAddUAccENameFld.setText(emp.getFullName());
        itAddUAccPhnNumberFld.setText(emp.getPhoneNumber());
        itAddUAccISupervisorFld.setText(emp.getImmediateSupervisor());
        itAddUAccPositionFld.setText(emp.getPosition());
        itAddUAccStatusFld.setText(emp.getStatus());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        itAddUAccSidebarPnl = new javax.swing.JPanel();
        itAddUAccActLogsBtn = new javax.swing.JButton();
        itAddUAccMainDashboardBtn = new javax.swing.JButton();
        itAddUAccMotorPHIconImgLbl = new javax.swing.JLabel();
        itAddUAccEditUAccBtn = new javax.swing.JButton();
        itAddUAccAddUAccBtn = new javax.swing.JButton();
        itAddUAccAddUAccPnl = new javax.swing.JPanel();
        itAddUAccAddUAccLbl = new javax.swing.JLabel();
        itAddUAccActivateBtn = new javax.swing.JButton();
        itAddUAccUEDetailsBrdrPnl = new javax.swing.JPanel();
        itAddUAccENumberLbl = new javax.swing.JLabel();
        itAddUAccENameLbl = new javax.swing.JLabel();
        itAddUAccENumberFld = new javax.swing.JTextField();
        itAddUAccENameFld = new javax.swing.JTextField();
        itAddUAccPhnNumberFld = new javax.swing.JTextField();
        itAddUAccPositionLbl = new javax.swing.JLabel();
        itAddUAccPhnNumberLbl = new javax.swing.JLabel();
        itAddUAccISupervisorLbl = new javax.swing.JLabel();
        itAddUAccISupervisorFld = new javax.swing.JTextField();
        itAddUAccPositionFld = new javax.swing.JTextField();
        itAddUAccStatusLbl = new javax.swing.JLabel();
        itAddUAccStatusFld = new javax.swing.JTextField();
        itAddUAccUAccDetailsPnl = new javax.swing.JPanel();
        itAddUAccUAccDetailsLbl = new javax.swing.JLabel();
        itAddUAccUAccDetailsBrdrPnl = new javax.swing.JPanel();
        itAddUAccUsernameLbl = new javax.swing.JLabel();
        itAddUAccUsernameFld = new javax.swing.JTextField();
        itAddUAccPasswordLbl = new javax.swing.JLabel();
        itAddUAccPasswordFld = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        itAddUAccSidebarPnl.setBackground(new java.awt.Color(30, 58, 138));

        itAddUAccActLogsBtn.setBackground(new java.awt.Color(30, 42, 56));
        itAddUAccActLogsBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        itAddUAccActLogsBtn.setForeground(new java.awt.Color(255, 255, 255));
        itAddUAccActLogsBtn.setText("Activity Logs");
        itAddUAccActLogsBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        itAddUAccActLogsBtn.addActionListener(this::itAddUAccActLogsBtnActionPerformed);

        itAddUAccMainDashboardBtn.setBackground(new java.awt.Color(30, 42, 56));
        itAddUAccMainDashboardBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        itAddUAccMainDashboardBtn.setForeground(new java.awt.Color(255, 255, 255));
        itAddUAccMainDashboardBtn.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        itAddUAccMainDashboardBtn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        itAddUAccMainDashboardBtn.setLabel("Main Dashboard");
        itAddUAccMainDashboardBtn.addActionListener(this::itAddUAccMainDashboardBtnActionPerformed);

        itAddUAccMotorPHIconImgLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/motorph/img/MotorPHIconImg.png"))); // NOI18N

        itAddUAccEditUAccBtn.setBackground(new java.awt.Color(30, 42, 56));
        itAddUAccEditUAccBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        itAddUAccEditUAccBtn.setForeground(new java.awt.Color(255, 255, 255));
        itAddUAccEditUAccBtn.setText("Edit User Account");
        itAddUAccEditUAccBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        itAddUAccEditUAccBtn.addActionListener(this::itAddUAccEditUAccBtnActionPerformed);

        itAddUAccAddUAccBtn.setBackground(new java.awt.Color(30, 42, 56));
        itAddUAccAddUAccBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        itAddUAccAddUAccBtn.setForeground(new java.awt.Color(255, 255, 255));
        itAddUAccAddUAccBtn.setText("Add User Account");
        itAddUAccAddUAccBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        itAddUAccAddUAccBtn.addActionListener(this::itAddUAccAddUAccBtnActionPerformed);

        javax.swing.GroupLayout itAddUAccSidebarPnlLayout = new javax.swing.GroupLayout(itAddUAccSidebarPnl);
        itAddUAccSidebarPnl.setLayout(itAddUAccSidebarPnlLayout);
        itAddUAccSidebarPnlLayout.setHorizontalGroup(
            itAddUAccSidebarPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itAddUAccSidebarPnlLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(itAddUAccMainDashboardBtn))
            .addGroup(itAddUAccSidebarPnlLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(itAddUAccSidebarPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(itAddUAccAddUAccBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itAddUAccEditUAccBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itAddUAccActLogsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(itAddUAccSidebarPnlLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(itAddUAccMotorPHIconImgLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        itAddUAccSidebarPnlLayout.setVerticalGroup(
            itAddUAccSidebarPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itAddUAccSidebarPnlLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(itAddUAccSidebarPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(itAddUAccMotorPHIconImgLbl)
                    .addGroup(itAddUAccSidebarPnlLayout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(itAddUAccActLogsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(itAddUAccEditUAccBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(itAddUAccAddUAccBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(307, 307, 307)
                .addComponent(itAddUAccMainDashboardBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        itAddUAccActLogsBtn.getAccessibleContext().setAccessibleName("itAddUAccActLogsBtn");
        itAddUAccMainDashboardBtn.getAccessibleContext().setAccessibleName("itAddUAccMainDashboardBtn");
        itAddUAccMotorPHIconImgLbl.getAccessibleContext().setAccessibleName("itAddUAccMotorPHIconImgLbl");
        itAddUAccEditUAccBtn.getAccessibleContext().setAccessibleName("itAddUAccEditUAccBtn");
        itAddUAccAddUAccBtn.getAccessibleContext().setAccessibleName("itAddUAccAddUAccBtn");

        itAddUAccAddUAccPnl.setBackground(new java.awt.Color(30, 58, 138));
        itAddUAccAddUAccPnl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        itAddUAccAddUAccPnl.setForeground(new java.awt.Color(30, 58, 138));
        itAddUAccAddUAccPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        itAddUAccAddUAccLbl.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        itAddUAccAddUAccLbl.setForeground(new java.awt.Color(255, 255, 255));
        itAddUAccAddUAccLbl.setText("Add User Account");
        itAddUAccAddUAccPnl.add(itAddUAccAddUAccLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 1, 220, 46));
        itAddUAccAddUAccLbl.getAccessibleContext().setAccessibleName("itAddUAccAddUAccLbl");

        itAddUAccActivateBtn.setBackground(new java.awt.Color(34, 197, 94));
        itAddUAccActivateBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        itAddUAccActivateBtn.setForeground(new java.awt.Color(255, 255, 255));
        itAddUAccActivateBtn.setText("Activate");
        itAddUAccActivateBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        itAddUAccActivateBtn.addActionListener(this::itAddUAccActivateBtnActionPerformed);

        itAddUAccUEDetailsBrdrPnl.setBackground(new java.awt.Color(255, 255, 255));
        itAddUAccUEDetailsBrdrPnl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 2, true));
        itAddUAccUEDetailsBrdrPnl.setForeground(new java.awt.Color(30, 42, 56));
        itAddUAccUEDetailsBrdrPnl.setFocusable(false);
        itAddUAccUEDetailsBrdrPnl.setPreferredSize(new java.awt.Dimension(700, 469));
        itAddUAccUEDetailsBrdrPnl.setRequestFocusEnabled(false);

        itAddUAccENumberLbl.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        itAddUAccENumberLbl.setForeground(new java.awt.Color(31, 41, 55));
        itAddUAccENumberLbl.setText("Employee #");

        itAddUAccENameLbl.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        itAddUAccENameLbl.setForeground(new java.awt.Color(31, 41, 55));
        itAddUAccENameLbl.setText("Employee Name");

        itAddUAccENumberFld.setForeground(new java.awt.Color(30, 42, 56));
        itAddUAccENumberFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        itAddUAccENumberFld.setCaretColor(new java.awt.Color(31, 41, 55));
        itAddUAccENumberFld.setDisabledTextColor(new java.awt.Color(31, 41, 55));
        itAddUAccENumberFld.setEnabled(false);
        itAddUAccENumberFld.addActionListener(this::itAddUAccENumberFldActionPerformed);

        itAddUAccENameFld.setForeground(new java.awt.Color(30, 42, 56));
        itAddUAccENameFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        itAddUAccENameFld.setCaretColor(new java.awt.Color(31, 41, 55));
        itAddUAccENameFld.setDisabledTextColor(new java.awt.Color(31, 41, 55));
        itAddUAccENameFld.setEnabled(false);
        itAddUAccENameFld.addActionListener(this::itAddUAccENameFldActionPerformed);

        itAddUAccPhnNumberFld.setForeground(new java.awt.Color(30, 42, 56));
        itAddUAccPhnNumberFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        itAddUAccPhnNumberFld.setCaretColor(new java.awt.Color(31, 41, 55));
        itAddUAccPhnNumberFld.setDisabledTextColor(new java.awt.Color(31, 41, 55));
        itAddUAccPhnNumberFld.setEnabled(false);
        itAddUAccPhnNumberFld.addActionListener(this::itAddUAccPhnNumberFldActionPerformed);

        itAddUAccPositionLbl.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        itAddUAccPositionLbl.setForeground(new java.awt.Color(31, 41, 55));
        itAddUAccPositionLbl.setText("Position");

        itAddUAccPhnNumberLbl.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        itAddUAccPhnNumberLbl.setForeground(new java.awt.Color(31, 41, 55));
        itAddUAccPhnNumberLbl.setText("Phone Number");

        itAddUAccISupervisorLbl.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        itAddUAccISupervisorLbl.setForeground(new java.awt.Color(31, 41, 55));
        itAddUAccISupervisorLbl.setText("Immediate Supervisor");

        itAddUAccISupervisorFld.setForeground(new java.awt.Color(30, 42, 56));
        itAddUAccISupervisorFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        itAddUAccISupervisorFld.setCaretColor(new java.awt.Color(31, 41, 55));
        itAddUAccISupervisorFld.setDisabledTextColor(new java.awt.Color(31, 41, 55));
        itAddUAccISupervisorFld.setEnabled(false);
        itAddUAccISupervisorFld.addActionListener(this::itAddUAccISupervisorFldActionPerformed);

        itAddUAccPositionFld.setForeground(new java.awt.Color(30, 42, 56));
        itAddUAccPositionFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        itAddUAccPositionFld.setCaretColor(new java.awt.Color(31, 41, 55));
        itAddUAccPositionFld.setDisabledTextColor(new java.awt.Color(31, 41, 55));
        itAddUAccPositionFld.setEnabled(false);
        itAddUAccPositionFld.addActionListener(this::itAddUAccPositionFldActionPerformed);

        itAddUAccStatusLbl.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        itAddUAccStatusLbl.setForeground(new java.awt.Color(31, 41, 55));
        itAddUAccStatusLbl.setText("Status");

        itAddUAccStatusFld.setForeground(new java.awt.Color(30, 42, 56));
        itAddUAccStatusFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        itAddUAccStatusFld.setCaretColor(new java.awt.Color(31, 41, 55));
        itAddUAccStatusFld.setDisabledTextColor(new java.awt.Color(31, 41, 55));
        itAddUAccStatusFld.setEnabled(false);
        itAddUAccStatusFld.addActionListener(this::itAddUAccStatusFldActionPerformed);

        itAddUAccUAccDetailsPnl.setBackground(new java.awt.Color(146, 192, 253));
        itAddUAccUAccDetailsPnl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        itAddUAccUAccDetailsPnl.setForeground(new java.awt.Color(30, 58, 138));
        itAddUAccUAccDetailsPnl.setPreferredSize(new java.awt.Dimension(126, 40));

        itAddUAccUAccDetailsLbl.setBackground(new java.awt.Color(255, 255, 255));
        itAddUAccUAccDetailsLbl.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        itAddUAccUAccDetailsLbl.setForeground(new java.awt.Color(31, 41, 55));
        itAddUAccUAccDetailsLbl.setText("User Account Details");
        itAddUAccUAccDetailsLbl.setToolTipText("");

        javax.swing.GroupLayout itAddUAccUAccDetailsPnlLayout = new javax.swing.GroupLayout(itAddUAccUAccDetailsPnl);
        itAddUAccUAccDetailsPnl.setLayout(itAddUAccUAccDetailsPnlLayout);
        itAddUAccUAccDetailsPnlLayout.setHorizontalGroup(
            itAddUAccUAccDetailsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itAddUAccUAccDetailsPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(itAddUAccUAccDetailsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        itAddUAccUAccDetailsPnlLayout.setVerticalGroup(
            itAddUAccUAccDetailsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itAddUAccUAccDetailsPnlLayout.createSequentialGroup()
                .addComponent(itAddUAccUAccDetailsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        itAddUAccUAccDetailsLbl.getAccessibleContext().setAccessibleName("itAddUAccUAccDetailsLbl");

        itAddUAccUAccDetailsBrdrPnl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));

        itAddUAccUsernameLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        itAddUAccUsernameLbl.setForeground(new java.awt.Color(31, 41, 55));
        itAddUAccUsernameLbl.setText("Username");

        itAddUAccUsernameFld.setForeground(new java.awt.Color(30, 42, 56));
        itAddUAccUsernameFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        itAddUAccUsernameFld.setCaretColor(new java.awt.Color(31, 41, 55));
        itAddUAccUsernameFld.setDisabledTextColor(new java.awt.Color(31, 41, 55));
        itAddUAccUsernameFld.addActionListener(this::itAddUAccUsernameFldActionPerformed);

        itAddUAccPasswordLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        itAddUAccPasswordLbl.setForeground(new java.awt.Color(31, 41, 55));
        itAddUAccPasswordLbl.setText("Password");

        itAddUAccPasswordFld.setForeground(new java.awt.Color(30, 42, 56));
        itAddUAccPasswordFld.setText("password");
        itAddUAccPasswordFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        itAddUAccPasswordFld.addActionListener(this::itAddUAccPasswordFldActionPerformed);

        javax.swing.GroupLayout itAddUAccUAccDetailsBrdrPnlLayout = new javax.swing.GroupLayout(itAddUAccUAccDetailsBrdrPnl);
        itAddUAccUAccDetailsBrdrPnl.setLayout(itAddUAccUAccDetailsBrdrPnlLayout);
        itAddUAccUAccDetailsBrdrPnlLayout.setHorizontalGroup(
            itAddUAccUAccDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itAddUAccUAccDetailsBrdrPnlLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(itAddUAccUAccDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(itAddUAccPasswordFld, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itAddUAccPasswordLbl)
                    .addComponent(itAddUAccUsernameLbl)
                    .addComponent(itAddUAccUsernameFld, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        itAddUAccUAccDetailsBrdrPnlLayout.setVerticalGroup(
            itAddUAccUAccDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itAddUAccUAccDetailsBrdrPnlLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(itAddUAccUsernameLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(itAddUAccUsernameFld, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(itAddUAccPasswordLbl)
                .addGap(18, 18, 18)
                .addComponent(itAddUAccPasswordFld, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        itAddUAccUsernameLbl.getAccessibleContext().setAccessibleName("itAddUAccUsernameLbl");
        itAddUAccUsernameFld.getAccessibleContext().setAccessibleName("itAddUAccUsernameFld");
        itAddUAccPasswordLbl.getAccessibleContext().setAccessibleName("itAddUAccPasswordLbl");
        itAddUAccPasswordFld.getAccessibleContext().setAccessibleName("itAddUAccPasswordFld");

        javax.swing.GroupLayout itAddUAccUEDetailsBrdrPnlLayout = new javax.swing.GroupLayout(itAddUAccUEDetailsBrdrPnl);
        itAddUAccUEDetailsBrdrPnl.setLayout(itAddUAccUEDetailsBrdrPnlLayout);
        itAddUAccUEDetailsBrdrPnlLayout.setHorizontalGroup(
            itAddUAccUEDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itAddUAccUEDetailsBrdrPnlLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(itAddUAccUEDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(itAddUAccENumberLbl)
                    .addComponent(itAddUAccENameLbl)
                    .addComponent(itAddUAccPhnNumberLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(itAddUAccUEDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(itAddUAccENameFld, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itAddUAccPhnNumberFld, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itAddUAccENumberFld, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(itAddUAccUEDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(itAddUAccUEDetailsBrdrPnlLayout.createSequentialGroup()
                        .addComponent(itAddUAccStatusLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(itAddUAccStatusFld, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(itAddUAccUEDetailsBrdrPnlLayout.createSequentialGroup()
                        .addComponent(itAddUAccPositionLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(itAddUAccPositionFld, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(itAddUAccUEDetailsBrdrPnlLayout.createSequentialGroup()
                        .addComponent(itAddUAccISupervisorLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addComponent(itAddUAccISupervisorFld, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
            .addGroup(itAddUAccUEDetailsBrdrPnlLayout.createSequentialGroup()
                .addGroup(itAddUAccUEDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(itAddUAccUEDetailsBrdrPnlLayout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(itAddUAccUAccDetailsPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(itAddUAccUEDetailsBrdrPnlLayout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(itAddUAccUAccDetailsBrdrPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        itAddUAccUEDetailsBrdrPnlLayout.setVerticalGroup(
            itAddUAccUEDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itAddUAccUEDetailsBrdrPnlLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(itAddUAccUEDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itAddUAccENumberLbl)
                    .addComponent(itAddUAccENumberFld, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itAddUAccISupervisorLbl)
                    .addComponent(itAddUAccISupervisorFld, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(itAddUAccUEDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itAddUAccENameFld, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itAddUAccENameLbl)
                    .addComponent(itAddUAccPositionLbl)
                    .addComponent(itAddUAccPositionFld, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(itAddUAccUEDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itAddUAccPhnNumberLbl)
                    .addComponent(itAddUAccPhnNumberFld, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itAddUAccStatusLbl)
                    .addComponent(itAddUAccStatusFld, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(itAddUAccUAccDetailsPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(itAddUAccUAccDetailsBrdrPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        itAddUAccENumberLbl.getAccessibleContext().setAccessibleName("itAddUAccENumberLbl");
        itAddUAccENameLbl.getAccessibleContext().setAccessibleName("itAddUAccENameLbl");
        itAddUAccENumberFld.getAccessibleContext().setAccessibleName("itAddUAccENumberFld");
        itAddUAccENameFld.getAccessibleContext().setAccessibleName("itAddUAccENameFld");
        itAddUAccPhnNumberFld.getAccessibleContext().setAccessibleName("itAddUAccPhnNumberFld");
        itAddUAccPositionLbl.getAccessibleContext().setAccessibleName("itAddUAccPositionLbl");
        itAddUAccPhnNumberLbl.getAccessibleContext().setAccessibleName("itAddUAccPhnNumberLbl");
        itAddUAccISupervisorLbl.getAccessibleContext().setAccessibleName("itAddUAccISupervisorLbl");
        itAddUAccISupervisorFld.getAccessibleContext().setAccessibleName("itAddUAccISupervisorFld");
        itAddUAccPositionFld.getAccessibleContext().setAccessibleName("itAddUAccPositionFld");
        itAddUAccStatusLbl.getAccessibleContext().setAccessibleName("itAddUAccStatusLbl");
        itAddUAccStatusFld.getAccessibleContext().setAccessibleName("itAddUAccStatusFld");
        itAddUAccUAccDetailsPnl.getAccessibleContext().setAccessibleName("itAddUAccUAccDetailsPnl");
        itAddUAccUAccDetailsBrdrPnl.getAccessibleContext().setAccessibleName("itAddUAccUAccDetailsBrdrPnl");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(itAddUAccActivateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(itAddUAccSidebarPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(itAddUAccAddUAccPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(itAddUAccUEDetailsBrdrPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 712, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(itAddUAccAddUAccPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(itAddUAccUEDetailsBrdrPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(itAddUAccActivateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(itAddUAccSidebarPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        itAddUAccSidebarPnl.getAccessibleContext().setAccessibleName("itAddUAccSidebarPnl");
        itAddUAccAddUAccPnl.getAccessibleContext().setAccessibleName("itAddUAccAddUAccPnl");
        itAddUAccActivateBtn.getAccessibleContext().setAccessibleName("itAddUAccActivateBtn");
        itAddUAccUEDetailsBrdrPnl.getAccessibleContext().setAccessibleName("itAddUAccUEDetailsBrdrPnl");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itAddUAccActivateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itAddUAccActivateBtnActionPerformed
        // TODO add your handling code here:
        try {
            
            String username = itAddUAccUsernameFld.getText();
            if (username == null || username.isBlank() || username.isEmpty()) {
                throw new IllegalArgumentException("Username is required");
            }
            
            String password = itAddUAccPasswordFld.getPassword().toString();
            
            if (password == null || password.isBlank() || password.isEmpty()) {
                throw new IllegalArgumentException("Password is required");
            }
            
            
            
            String message = "Do you want to create and activate " + username + " ?";
            String title = "Confirmation";

            int reply = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION);

            
            if (reply == JOptionPane.YES_OPTION) {
                
                //userService.createUser(reply, username, password, Role.HR, username);
                JOptionPane.showMessageDialog(null, "UNSUPPORTED  " + user.getUsername());
                
            } else if (reply == JOptionPane.NO_OPTION) {
                JOptionPane.showMessageDialog(null, "You clicked No. Exiting.");
                
            } else {
                // This handles the case where the user closes the dialog without pressing Yes or No
                JOptionPane.showMessageDialog(null, "Dialog closed without a choice.");
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
    }//GEN-LAST:event_itAddUAccActivateBtnActionPerformed

    private void itAddUAccActLogsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itAddUAccActLogsBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itAddUAccActLogsBtnActionPerformed

    private void itAddUAccMainDashboardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itAddUAccMainDashboardBtnActionPerformed
        // TODO add your handling code here:
        GuiUtil.openFrame(this);
    }//GEN-LAST:event_itAddUAccMainDashboardBtnActionPerformed

    private void itAddUAccEditUAccBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itAddUAccEditUAccBtnActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_itAddUAccEditUAccBtnActionPerformed

    private void itAddUAccAddUAccBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itAddUAccAddUAccBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itAddUAccAddUAccBtnActionPerformed

    private void itAddUAccENumberFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itAddUAccENumberFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itAddUAccENumberFldActionPerformed

    private void itAddUAccENameFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itAddUAccENameFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itAddUAccENameFldActionPerformed

    private void itAddUAccPhnNumberFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itAddUAccPhnNumberFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itAddUAccPhnNumberFldActionPerformed

    private void itAddUAccISupervisorFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itAddUAccISupervisorFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itAddUAccISupervisorFldActionPerformed

    private void itAddUAccPositionFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itAddUAccPositionFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itAddUAccPositionFldActionPerformed

    private void itAddUAccStatusFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itAddUAccStatusFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itAddUAccStatusFldActionPerformed

    private void itAddUAccUsernameFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itAddUAccUsernameFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itAddUAccUsernameFldActionPerformed

    private void itAddUAccPasswordFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itAddUAccPasswordFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itAddUAccPasswordFldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton itAddUAccActLogsBtn;
    private javax.swing.JButton itAddUAccActivateBtn;
    private javax.swing.JButton itAddUAccAddUAccBtn;
    private javax.swing.JLabel itAddUAccAddUAccLbl;
    private javax.swing.JPanel itAddUAccAddUAccPnl;
    private javax.swing.JTextField itAddUAccENameFld;
    private javax.swing.JLabel itAddUAccENameLbl;
    private javax.swing.JTextField itAddUAccENumberFld;
    private javax.swing.JLabel itAddUAccENumberLbl;
    private javax.swing.JButton itAddUAccEditUAccBtn;
    private javax.swing.JTextField itAddUAccISupervisorFld;
    private javax.swing.JLabel itAddUAccISupervisorLbl;
    private javax.swing.JButton itAddUAccMainDashboardBtn;
    private javax.swing.JLabel itAddUAccMotorPHIconImgLbl;
    private javax.swing.JPasswordField itAddUAccPasswordFld;
    private javax.swing.JLabel itAddUAccPasswordLbl;
    private javax.swing.JTextField itAddUAccPhnNumberFld;
    private javax.swing.JLabel itAddUAccPhnNumberLbl;
    private javax.swing.JTextField itAddUAccPositionFld;
    private javax.swing.JLabel itAddUAccPositionLbl;
    private javax.swing.JPanel itAddUAccSidebarPnl;
    private javax.swing.JTextField itAddUAccStatusFld;
    private javax.swing.JLabel itAddUAccStatusLbl;
    private javax.swing.JPanel itAddUAccUAccDetailsBrdrPnl;
    private javax.swing.JLabel itAddUAccUAccDetailsLbl;
    private javax.swing.JPanel itAddUAccUAccDetailsPnl;
    private javax.swing.JPanel itAddUAccUEDetailsBrdrPnl;
    private javax.swing.JTextField itAddUAccUsernameFld;
    private javax.swing.JLabel itAddUAccUsernameLbl;
    // End of variables declaration//GEN-END:variables
}
