/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.motorph.ui;

import com.motorph.model.Employee;
import com.motorph.model.UserAccount;
import com.motorph.service.EmployeeService;
import com.motorph.service.UserManagementService;
import com.motorph.util.AppContext;
import com.motorph.util.GuiUtil;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class ITUserManagementUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ITUserManagementUI.class.getName());
    private EmployeeService empService;
    private UserManagementService userService;

    /**
     * Creates new form ITDashboardFrame
     */
    public ITUserManagementUI() {
        this.empService = AppContext.getEmployeeService();
        this.userService = AppContext.getUserManagementService();
        initComponents();
    }
    
    
    private void performSearch() {
        String id = itSysToolsEntENumberPnl.getText().trim();
        Employee found = empService.findEmployee(id);
        if (found != null) {
            populateEmployeeData(found);
            populateUserData(found);
            
        } else {
            clearFields();
        }
    }
    
    private void populateUserData(Employee emp) {
        
        UserAccount user = userService.findByEmployeeNumber(emp.getEmployeeNumber());
        if (user == null) {
            itSysToolsUsernameFld.setText("No account found.");
            roleField.setText("");
            activeStatusField.setText("");
        } else {
            itSysToolsUsernameFld.setText(user.getUsername());
            roleField.setText(user.getRole().toString());
            if (user.isActive()) {
               activeStatusField.setText("Active"); 
            } else {
                activeStatusField.setText("Inactive");
            }
        }
        
    }
    
    private void populateEmployeeData(Employee emp) {
        itSysToolsENumberFld.setText(emp.getEmployeeNumber());
        itSysToolsENameFld.setText(emp.getFullName());
        itSysToolsPhnNumberFld.setText(emp.getPhoneNumber());
        itSysToolsISupervisorFld.setText(emp.getImmediateSupervisor());
        itSysToolsPositionFld.setText(emp.getPosition());
        itSysToolsStatusFld.setText(emp.getStatus());
    }
    
    private void clearFields() {
        itSysToolsENumberFld.setText("");
        itSysToolsENameFld.setText("");
        itSysToolsPhnNumberFld.setText("");
        itSysToolsISupervisorFld.setText("");
        itSysToolsPositionFld.setText("");
        itSysToolsStatusFld.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        itSysToolsSidebarPnl = new javax.swing.JPanel();
        itSysToolsUManagementBtn = new javax.swing.JButton();
        itSysToolsMainDashboardBtn = new javax.swing.JButton();
        itSysToolsMotorPHIconImgLbl = new javax.swing.JLabel();
        itSysToolsActLogsPnl = new javax.swing.JPanel();
        itSysToolsActLogsLbl = new javax.swing.JLabel();
        itSysToolsSearchPnl = new javax.swing.JPanel();
        itSysToolsEntENumberPnl = new javax.swing.JTextField();
        itSysToolsSearchIconImgLbl = new javax.swing.JLabel();
        itSysToolsEditBtn = new javax.swing.JButton();
        itSysToolsAddBtn = new javax.swing.JButton();
        itSysToolsUserEDetailsBrdrPnl = new javax.swing.JPanel();
        itSysToolsENumberLbl = new javax.swing.JLabel();
        itSysToolsENameLbl = new javax.swing.JLabel();
        itSysToolsENumberFld = new javax.swing.JTextField();
        itSysToolsENameFld = new javax.swing.JTextField();
        itSysToolsPhnNumberFld = new javax.swing.JTextField();
        itSysToolsPositionLbl = new javax.swing.JLabel();
        itSysToolsPhnNumberLbl = new javax.swing.JLabel();
        itSysToolsISupervisorLbl = new javax.swing.JLabel();
        itSysToolsISupervisorFld = new javax.swing.JTextField();
        itSysToolsPositionFld = new javax.swing.JTextField();
        itSysToolsStatusLbl = new javax.swing.JLabel();
        itSysToolsStatusFld = new javax.swing.JTextField();
        itSysToolsUAccDetailsPnl = new javax.swing.JPanel();
        itSysToolsUAccDetailsLbl = new javax.swing.JLabel();
        itSysToolsUAccDetailsBrdrPnl = new javax.swing.JPanel();
        itSysToolsUsernameLbl = new javax.swing.JLabel();
        itSysToolsUsernameFld = new javax.swing.JTextField();
        itSysToolsPasswordLbl = new javax.swing.JLabel();
        itSysToolsPasswordLbl1 = new javax.swing.JLabel();
        roleField = new javax.swing.JTextField();
        activeStatusField = new javax.swing.JTextField();
        itAddUAccActivateBtn = new javax.swing.JButton();
        itAddUAccActivateBtn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        itSysToolsSidebarPnl.setBackground(new java.awt.Color(30, 58, 138));
        itSysToolsSidebarPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        itSysToolsUManagementBtn.setBackground(new java.awt.Color(30, 42, 56));
        itSysToolsUManagementBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        itSysToolsUManagementBtn.setForeground(new java.awt.Color(255, 255, 255));
        itSysToolsUManagementBtn.setText("User Management");
        itSysToolsUManagementBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        itSysToolsUManagementBtn.addActionListener(this::itSysToolsUManagementBtnActionPerformed);
        itSysToolsSidebarPnl.add(itSysToolsUManagementBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 199, 216, 39));
        itSysToolsUManagementBtn.getAccessibleContext().setAccessibleName("itSysToolsActLogsBtn");

        itSysToolsMainDashboardBtn.setBackground(new java.awt.Color(30, 42, 56));
        itSysToolsMainDashboardBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        itSysToolsMainDashboardBtn.setForeground(new java.awt.Color(255, 255, 255));
        itSysToolsMainDashboardBtn.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        itSysToolsMainDashboardBtn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        itSysToolsMainDashboardBtn.setLabel("Main Dashboard");
        itSysToolsMainDashboardBtn.addActionListener(this::itSysToolsMainDashboardBtnActionPerformed);
        itSysToolsSidebarPnl.add(itSysToolsMainDashboardBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 647, -1, 39));
        itSysToolsMainDashboardBtn.getAccessibleContext().setAccessibleName("itSysToolsMainDashboardBtn");

        itSysToolsMotorPHIconImgLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/motorph/img/MotorPHIconImg.png"))); // NOI18N
        itSysToolsSidebarPnl.add(itSysToolsMotorPHIconImgLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 180, -1));
        itSysToolsMotorPHIconImgLbl.getAccessibleContext().setAccessibleName("itSysToolsMotorPHIconImgLbl");

        itSysToolsActLogsPnl.setBackground(new java.awt.Color(30, 58, 138));
        itSysToolsActLogsPnl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        itSysToolsActLogsPnl.setForeground(new java.awt.Color(30, 58, 138));
        itSysToolsActLogsPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        itSysToolsActLogsLbl.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        itSysToolsActLogsLbl.setForeground(new java.awt.Color(255, 255, 255));
        itSysToolsActLogsLbl.setText(" Activity Logs");
        itSysToolsActLogsPnl.add(itSysToolsActLogsLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 1, 170, 46));
        itSysToolsActLogsLbl.getAccessibleContext().setAccessibleName("itSysToolsActLogsLbl");

        itSysToolsSearchPnl.setBackground(new java.awt.Color(146, 192, 253));
        itSysToolsSearchPnl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        itSysToolsSearchPnl.setForeground(new java.awt.Color(146, 192, 253));
        itSysToolsSearchPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        itSysToolsEntENumberPnl.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        itSysToolsEntENumberPnl.setForeground(new java.awt.Color(31, 41, 55));
        itSysToolsEntENumberPnl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        itSysToolsEntENumberPnl.setCaretColor(new java.awt.Color(31, 41, 55));
        itSysToolsEntENumberPnl.setDisabledTextColor(new java.awt.Color(31, 41, 55));
        itSysToolsEntENumberPnl.addActionListener(this::itSysToolsEntENumberPnlActionPerformed);
        itSysToolsSearchPnl.add(itSysToolsEntENumberPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 7, 170, 31));
        itSysToolsEntENumberPnl.getAccessibleContext().setAccessibleName("itSysToolsEntENumberPnl");

        itSysToolsSearchIconImgLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/motorph/img/SearchIconImg.png"))); // NOI18N
        itSysToolsSearchPnl.add(itSysToolsSearchIconImgLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, -10, 60, 60));
        itSysToolsSearchIconImgLbl.getAccessibleContext().setAccessibleName("itActLogsSearchIconImgLbl");

        itSysToolsEditBtn.setBackground(new java.awt.Color(59, 130, 246));
        itSysToolsEditBtn.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        itSysToolsEditBtn.setForeground(new java.awt.Color(255, 255, 255));
        itSysToolsEditBtn.setText("Edit");
        itSysToolsEditBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        itSysToolsEditBtn.addActionListener(this::itSysToolsEditBtnActionPerformed);

        itSysToolsAddBtn.setBackground(new java.awt.Color(30, 58, 138));
        itSysToolsAddBtn.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        itSysToolsAddBtn.setForeground(new java.awt.Color(255, 255, 255));
        itSysToolsAddBtn.setText("Add");
        itSysToolsAddBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        itSysToolsAddBtn.addActionListener(this::itSysToolsAddBtnActionPerformed);

        itSysToolsUserEDetailsBrdrPnl.setBackground(new java.awt.Color(255, 255, 255));
        itSysToolsUserEDetailsBrdrPnl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 2, true));
        itSysToolsUserEDetailsBrdrPnl.setForeground(new java.awt.Color(30, 42, 56));
        itSysToolsUserEDetailsBrdrPnl.setFocusable(false);
        itSysToolsUserEDetailsBrdrPnl.setPreferredSize(new java.awt.Dimension(700, 469));
        itSysToolsUserEDetailsBrdrPnl.setRequestFocusEnabled(false);

        itSysToolsENumberLbl.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        itSysToolsENumberLbl.setForeground(new java.awt.Color(31, 41, 55));
        itSysToolsENumberLbl.setText("Employee #");

        itSysToolsENameLbl.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        itSysToolsENameLbl.setForeground(new java.awt.Color(31, 41, 55));
        itSysToolsENameLbl.setText("Employee Name");

        itSysToolsENumberFld.setForeground(new java.awt.Color(30, 42, 56));
        itSysToolsENumberFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        itSysToolsENumberFld.setCaretColor(new java.awt.Color(31, 41, 55));
        itSysToolsENumberFld.setDisabledTextColor(new java.awt.Color(31, 41, 55));
        itSysToolsENumberFld.setEnabled(false);
        itSysToolsENumberFld.addActionListener(this::itSysToolsENumberFldActionPerformed);

        itSysToolsENameFld.setForeground(new java.awt.Color(30, 42, 56));
        itSysToolsENameFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        itSysToolsENameFld.setCaretColor(new java.awt.Color(31, 41, 55));
        itSysToolsENameFld.setDisabledTextColor(new java.awt.Color(31, 41, 55));
        itSysToolsENameFld.setEnabled(false);
        itSysToolsENameFld.addActionListener(this::itSysToolsENameFldActionPerformed);

        itSysToolsPhnNumberFld.setForeground(new java.awt.Color(30, 42, 56));
        itSysToolsPhnNumberFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        itSysToolsPhnNumberFld.setCaretColor(new java.awt.Color(31, 41, 55));
        itSysToolsPhnNumberFld.setDisabledTextColor(new java.awt.Color(31, 41, 55));
        itSysToolsPhnNumberFld.setEnabled(false);
        itSysToolsPhnNumberFld.addActionListener(this::itSysToolsPhnNumberFldActionPerformed);

        itSysToolsPositionLbl.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        itSysToolsPositionLbl.setForeground(new java.awt.Color(31, 41, 55));
        itSysToolsPositionLbl.setText("Position");

        itSysToolsPhnNumberLbl.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        itSysToolsPhnNumberLbl.setForeground(new java.awt.Color(31, 41, 55));
        itSysToolsPhnNumberLbl.setText("Phone Number");

        itSysToolsISupervisorLbl.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        itSysToolsISupervisorLbl.setForeground(new java.awt.Color(31, 41, 55));
        itSysToolsISupervisorLbl.setText("Immediate Supervisor");

        itSysToolsISupervisorFld.setForeground(new java.awt.Color(30, 42, 56));
        itSysToolsISupervisorFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        itSysToolsISupervisorFld.setCaretColor(new java.awt.Color(31, 41, 55));
        itSysToolsISupervisorFld.setDisabledTextColor(new java.awt.Color(31, 41, 55));
        itSysToolsISupervisorFld.setEnabled(false);
        itSysToolsISupervisorFld.addActionListener(this::itSysToolsISupervisorFldActionPerformed);

        itSysToolsPositionFld.setForeground(new java.awt.Color(30, 42, 56));
        itSysToolsPositionFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        itSysToolsPositionFld.setCaretColor(new java.awt.Color(31, 41, 55));
        itSysToolsPositionFld.setDisabledTextColor(new java.awt.Color(31, 41, 55));
        itSysToolsPositionFld.setEnabled(false);
        itSysToolsPositionFld.addActionListener(this::itSysToolsPositionFldActionPerformed);

        itSysToolsStatusLbl.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        itSysToolsStatusLbl.setForeground(new java.awt.Color(31, 41, 55));
        itSysToolsStatusLbl.setText("Status");

        itSysToolsStatusFld.setForeground(new java.awt.Color(30, 42, 56));
        itSysToolsStatusFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        itSysToolsStatusFld.setCaretColor(new java.awt.Color(31, 41, 55));
        itSysToolsStatusFld.setDisabledTextColor(new java.awt.Color(31, 41, 55));
        itSysToolsStatusFld.setEnabled(false);
        itSysToolsStatusFld.addActionListener(this::itSysToolsStatusFldActionPerformed);

        itSysToolsUAccDetailsPnl.setBackground(new java.awt.Color(146, 192, 253));
        itSysToolsUAccDetailsPnl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        itSysToolsUAccDetailsPnl.setForeground(new java.awt.Color(30, 58, 138));
        itSysToolsUAccDetailsPnl.setPreferredSize(new java.awt.Dimension(126, 40));

        itSysToolsUAccDetailsLbl.setBackground(new java.awt.Color(255, 255, 255));
        itSysToolsUAccDetailsLbl.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        itSysToolsUAccDetailsLbl.setForeground(new java.awt.Color(31, 41, 55));
        itSysToolsUAccDetailsLbl.setText(" User Account Details");
        itSysToolsUAccDetailsLbl.setToolTipText("");

        javax.swing.GroupLayout itSysToolsUAccDetailsPnlLayout = new javax.swing.GroupLayout(itSysToolsUAccDetailsPnl);
        itSysToolsUAccDetailsPnl.setLayout(itSysToolsUAccDetailsPnlLayout);
        itSysToolsUAccDetailsPnlLayout.setHorizontalGroup(
            itSysToolsUAccDetailsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itSysToolsUAccDetailsPnlLayout.createSequentialGroup()
                .addComponent(itSysToolsUAccDetailsLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                .addContainerGap())
        );
        itSysToolsUAccDetailsPnlLayout.setVerticalGroup(
            itSysToolsUAccDetailsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itSysToolsUAccDetailsPnlLayout.createSequentialGroup()
                .addComponent(itSysToolsUAccDetailsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        itSysToolsUAccDetailsLbl.getAccessibleContext().setAccessibleName("itSysToolsUAccDetailsLbl");

        itSysToolsUAccDetailsBrdrPnl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));

        itSysToolsUsernameLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        itSysToolsUsernameLbl.setForeground(new java.awt.Color(31, 41, 55));
        itSysToolsUsernameLbl.setText("Username");

        itSysToolsUsernameFld.setForeground(new java.awt.Color(30, 42, 56));
        itSysToolsUsernameFld.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        itSysToolsUsernameFld.setCaretColor(new java.awt.Color(31, 41, 55));
        itSysToolsUsernameFld.setDisabledTextColor(new java.awt.Color(31, 41, 55));
        itSysToolsUsernameFld.setEnabled(false);
        itSysToolsUsernameFld.addActionListener(this::itSysToolsUsernameFldActionPerformed);

        itSysToolsPasswordLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        itSysToolsPasswordLbl.setForeground(new java.awt.Color(31, 41, 55));
        itSysToolsPasswordLbl.setText("Active Status");

        itSysToolsPasswordLbl1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        itSysToolsPasswordLbl1.setForeground(new java.awt.Color(31, 41, 55));
        itSysToolsPasswordLbl1.setText("Role");

        roleField.setForeground(new java.awt.Color(30, 42, 56));
        roleField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        roleField.setCaretColor(new java.awt.Color(31, 41, 55));
        roleField.setDisabledTextColor(new java.awt.Color(31, 41, 55));
        roleField.setEnabled(false);
        roleField.addActionListener(this::roleFieldActionPerformed);

        activeStatusField.setForeground(new java.awt.Color(30, 42, 56));
        activeStatusField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        activeStatusField.setCaretColor(new java.awt.Color(31, 41, 55));
        activeStatusField.setDisabledTextColor(new java.awt.Color(31, 41, 55));
        activeStatusField.setEnabled(false);
        activeStatusField.addActionListener(this::activeStatusFieldActionPerformed);

        javax.swing.GroupLayout itSysToolsUAccDetailsBrdrPnlLayout = new javax.swing.GroupLayout(itSysToolsUAccDetailsBrdrPnl);
        itSysToolsUAccDetailsBrdrPnl.setLayout(itSysToolsUAccDetailsBrdrPnlLayout);
        itSysToolsUAccDetailsBrdrPnlLayout.setHorizontalGroup(
            itSysToolsUAccDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itSysToolsUAccDetailsBrdrPnlLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(itSysToolsUAccDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(activeStatusField, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roleField, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itSysToolsPasswordLbl1)
                    .addComponent(itSysToolsPasswordLbl)
                    .addComponent(itSysToolsUsernameLbl)
                    .addComponent(itSysToolsUsernameFld, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        itSysToolsUAccDetailsBrdrPnlLayout.setVerticalGroup(
            itSysToolsUAccDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itSysToolsUAccDetailsBrdrPnlLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(itSysToolsUsernameLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(itSysToolsUsernameFld, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(itSysToolsPasswordLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(activeStatusField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(itSysToolsPasswordLbl1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(roleField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        itSysToolsUsernameLbl.getAccessibleContext().setAccessibleName("itSysToolsUsernameLbl");
        itSysToolsUsernameFld.getAccessibleContext().setAccessibleName("itSysToolsUsernameFld");
        itSysToolsPasswordLbl.getAccessibleContext().setAccessibleName("itSysToolsPasswordLbl");

        javax.swing.GroupLayout itSysToolsUserEDetailsBrdrPnlLayout = new javax.swing.GroupLayout(itSysToolsUserEDetailsBrdrPnl);
        itSysToolsUserEDetailsBrdrPnl.setLayout(itSysToolsUserEDetailsBrdrPnlLayout);
        itSysToolsUserEDetailsBrdrPnlLayout.setHorizontalGroup(
            itSysToolsUserEDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itSysToolsUserEDetailsBrdrPnlLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(itSysToolsUserEDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(itSysToolsENumberLbl)
                    .addComponent(itSysToolsENameLbl)
                    .addComponent(itSysToolsPhnNumberLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(itSysToolsUserEDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(itSysToolsENameFld, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itSysToolsPhnNumberFld, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itSysToolsENumberFld, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(itSysToolsUserEDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(itSysToolsUserEDetailsBrdrPnlLayout.createSequentialGroup()
                        .addComponent(itSysToolsStatusLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(itSysToolsStatusFld, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(itSysToolsUserEDetailsBrdrPnlLayout.createSequentialGroup()
                        .addComponent(itSysToolsPositionLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(itSysToolsPositionFld, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(itSysToolsUserEDetailsBrdrPnlLayout.createSequentialGroup()
                        .addComponent(itSysToolsISupervisorLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(itSysToolsISupervisorFld, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
            .addGroup(itSysToolsUserEDetailsBrdrPnlLayout.createSequentialGroup()
                .addGroup(itSysToolsUserEDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(itSysToolsUserEDetailsBrdrPnlLayout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(itSysToolsUAccDetailsPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(itSysToolsUserEDetailsBrdrPnlLayout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(itSysToolsUAccDetailsBrdrPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        itSysToolsUserEDetailsBrdrPnlLayout.setVerticalGroup(
            itSysToolsUserEDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itSysToolsUserEDetailsBrdrPnlLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(itSysToolsUserEDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itSysToolsENumberLbl)
                    .addComponent(itSysToolsENumberFld, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itSysToolsISupervisorLbl)
                    .addComponent(itSysToolsISupervisorFld, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(itSysToolsUserEDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itSysToolsENameFld, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itSysToolsENameLbl)
                    .addComponent(itSysToolsPositionLbl)
                    .addComponent(itSysToolsPositionFld, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(itSysToolsUserEDetailsBrdrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itSysToolsPhnNumberLbl)
                    .addComponent(itSysToolsPhnNumberFld, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itSysToolsStatusLbl)
                    .addComponent(itSysToolsStatusFld, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(itSysToolsUAccDetailsPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(itSysToolsUAccDetailsBrdrPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        itSysToolsENumberLbl.getAccessibleContext().setAccessibleName("itSysToolsENumberLbl");
        itSysToolsENameLbl.getAccessibleContext().setAccessibleName("itSysToolsENameLbl");
        itSysToolsENumberFld.getAccessibleContext().setAccessibleName("itSysToolsENumberFld");
        itSysToolsENameFld.getAccessibleContext().setAccessibleName("itSysToolsENameFld");
        itSysToolsPhnNumberFld.getAccessibleContext().setAccessibleName("itSysToolsPhnNumberFld");
        itSysToolsPositionLbl.getAccessibleContext().setAccessibleName("itSysToolsPositionLbl");
        itSysToolsPhnNumberLbl.getAccessibleContext().setAccessibleName("itSysToolsPhnNumberLbl");
        itSysToolsISupervisorLbl.getAccessibleContext().setAccessibleName("itSysToolsISupervisorLbl");
        itSysToolsISupervisorFld.getAccessibleContext().setAccessibleName("itSysToolsISupervisorFld");
        itSysToolsPositionFld.getAccessibleContext().setAccessibleName("itSysToolsPositionFld");
        itSysToolsStatusLbl.getAccessibleContext().setAccessibleName("itSysToolsStatusLbl");
        itSysToolsStatusFld.getAccessibleContext().setAccessibleName("itSysToolsStatusFld");
        itSysToolsUAccDetailsPnl.getAccessibleContext().setAccessibleName("itSysToolsUAccDetailsPnl");
        itSysToolsUAccDetailsBrdrPnl.getAccessibleContext().setAccessibleName("itSysToolsUAccDetailsBrdrPnl");

        itAddUAccActivateBtn.setBackground(new java.awt.Color(255, 0, 0));
        itAddUAccActivateBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        itAddUAccActivateBtn.setForeground(new java.awt.Color(255, 255, 255));
        itAddUAccActivateBtn.setText("Deactivate");
        itAddUAccActivateBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        itAddUAccActivateBtn.addActionListener(this::itAddUAccActivateBtnActionPerformed);

        itAddUAccActivateBtn1.setBackground(new java.awt.Color(34, 197, 94));
        itAddUAccActivateBtn1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        itAddUAccActivateBtn1.setForeground(new java.awt.Color(255, 255, 255));
        itAddUAccActivateBtn1.setText("Activate");
        itAddUAccActivateBtn1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 42, 56), 1, true));
        itAddUAccActivateBtn1.addActionListener(this::itAddUAccActivateBtn1ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(itSysToolsSidebarPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(itSysToolsEditBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(itSysToolsAddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(293, 293, 293)
                        .addComponent(itAddUAccActivateBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(itAddUAccActivateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(itSysToolsActLogsPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(12, 12, 12)
                            .addComponent(itSysToolsSearchPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(293, 293, 293))
                        .addComponent(itSysToolsUserEDetailsBrdrPnl, javax.swing.GroupLayout.DEFAULT_SIZE, 702, Short.MAX_VALUE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(itSysToolsSidebarPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(itSysToolsActLogsPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itSysToolsSearchPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(itSysToolsUserEDetailsBrdrPnl, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itSysToolsEditBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itSysToolsAddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itAddUAccActivateBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itAddUAccActivateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55))
        );

        itSysToolsSidebarPnl.getAccessibleContext().setAccessibleName("itSysToolsSidebarPnl");
        itSysToolsActLogsPnl.getAccessibleContext().setAccessibleName("itSysToolsActLogsPnl");
        itSysToolsSearchPnl.getAccessibleContext().setAccessibleName("itSysToolsSearchPnl");
        itSysToolsEditBtn.getAccessibleContext().setAccessibleName("itSysToolsEditBtn");
        itSysToolsAddBtn.getAccessibleContext().setAccessibleName("itSysToolsAddBtn");
        itSysToolsUserEDetailsBrdrPnl.getAccessibleContext().setAccessibleName("itSysToolsUserEDetailsBrdrPnl");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itSysToolsUManagementBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itSysToolsUManagementBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itSysToolsUManagementBtnActionPerformed

    private void itSysToolsMainDashboardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itSysToolsMainDashboardBtnActionPerformed
        // TODO add your handling code here:
        GuiUtil.openFrame(this);
    }//GEN-LAST:event_itSysToolsMainDashboardBtnActionPerformed

    private void itSysToolsAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itSysToolsAddBtnActionPerformed
        // TODO add your handling code here:
        try {
            String empNum = itSysToolsENumberFld.getText().trim();
            if (empNum == null || empNum.isBlank() || empNum.isEmpty()) {
                throw new IllegalArgumentException("Search for a user account to edit.");
            }
            
            
            Employee emp = empService.findEmployee(empNum);
            GuiUtil.openFrame(this, new ITAddUserAccountUI(emp));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_itSysToolsAddBtnActionPerformed

    private void itSysToolsEditBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itSysToolsEditBtnActionPerformed
        // TODO add your handling code here:
        
        try {
            String userName = itSysToolsUsernameFld.getText().trim();
            if (userName == null || userName.isBlank() || userName.isEmpty()) {
                throw new IllegalArgumentException("Search for a user account to edit.");
            }
            UserAccount user = userService.findByUserName(userName);
            Employee emp = empService.findEmployee(user.getEmployeeNumber());
            GuiUtil.openFrame(this, new ITEditUserAccountUI(user, emp));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
       
    }//GEN-LAST:event_itSysToolsEditBtnActionPerformed

    private void itSysToolsEntENumberPnlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itSysToolsEntENumberPnlActionPerformed
        // TODO add your handling code here:
        performSearch();
    }//GEN-LAST:event_itSysToolsEntENumberPnlActionPerformed

    private void itSysToolsENumberFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itSysToolsENumberFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itSysToolsENumberFldActionPerformed

    private void itSysToolsENameFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itSysToolsENameFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itSysToolsENameFldActionPerformed

    private void itSysToolsPhnNumberFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itSysToolsPhnNumberFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itSysToolsPhnNumberFldActionPerformed

    private void itSysToolsISupervisorFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itSysToolsISupervisorFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itSysToolsISupervisorFldActionPerformed

    private void itSysToolsPositionFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itSysToolsPositionFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itSysToolsPositionFldActionPerformed

    private void itSysToolsStatusFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itSysToolsStatusFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itSysToolsStatusFldActionPerformed

    private void itSysToolsUsernameFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itSysToolsUsernameFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itSysToolsUsernameFldActionPerformed

    private void itAddUAccActivateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itAddUAccActivateBtnActionPerformed
        // TODO add your handling code here:
        try {
            String userName = itSysToolsUsernameFld.getText().trim();
            if (userName == null || userName.isBlank() || userName.isEmpty()) {
                throw new IllegalArgumentException("Search for a user account to Deactivate.");
            }
            UserAccount user = userService.findByUserName(userName);
            
            String message = "Do you want to deactivate " + user.getUsername() + " ?";
            String title = "Confirmation";

            int reply = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION);

            
            if (reply == JOptionPane.YES_OPTION) {
                userService.deactivateUser(user.getUserId());
                JOptionPane.showMessageDialog(null, "Deactivated user " + user.getUsername());
                
            } else if (reply == JOptionPane.NO_OPTION) {
                JOptionPane.showMessageDialog(null, "You clicked No. Exiting.");
                
            } else {
                // This handles the case where the user closes the dialog without pressing Yes or No
                JOptionPane.showMessageDialog(null, "Dialog closed without a choice.");
            }
        
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_itAddUAccActivateBtnActionPerformed

    private void itAddUAccActivateBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itAddUAccActivateBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itAddUAccActivateBtn1ActionPerformed

    private void roleFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roleFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roleFieldActionPerformed

    private void activeStatusFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activeStatusFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_activeStatusFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ITUserManagementUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField activeStatusField;
    private javax.swing.JButton itAddUAccActivateBtn;
    private javax.swing.JButton itAddUAccActivateBtn1;
    private javax.swing.JLabel itSysToolsActLogsLbl;
    private javax.swing.JPanel itSysToolsActLogsPnl;
    private javax.swing.JButton itSysToolsAddBtn;
    private javax.swing.JTextField itSysToolsENameFld;
    private javax.swing.JLabel itSysToolsENameLbl;
    private javax.swing.JTextField itSysToolsENumberFld;
    private javax.swing.JLabel itSysToolsENumberLbl;
    private javax.swing.JButton itSysToolsEditBtn;
    private javax.swing.JTextField itSysToolsEntENumberPnl;
    private javax.swing.JTextField itSysToolsISupervisorFld;
    private javax.swing.JLabel itSysToolsISupervisorLbl;
    private javax.swing.JButton itSysToolsMainDashboardBtn;
    private javax.swing.JLabel itSysToolsMotorPHIconImgLbl;
    private javax.swing.JLabel itSysToolsPasswordLbl;
    private javax.swing.JLabel itSysToolsPasswordLbl1;
    private javax.swing.JTextField itSysToolsPhnNumberFld;
    private javax.swing.JLabel itSysToolsPhnNumberLbl;
    private javax.swing.JTextField itSysToolsPositionFld;
    private javax.swing.JLabel itSysToolsPositionLbl;
    private javax.swing.JLabel itSysToolsSearchIconImgLbl;
    private javax.swing.JPanel itSysToolsSearchPnl;
    private javax.swing.JPanel itSysToolsSidebarPnl;
    private javax.swing.JTextField itSysToolsStatusFld;
    private javax.swing.JLabel itSysToolsStatusLbl;
    private javax.swing.JPanel itSysToolsUAccDetailsBrdrPnl;
    private javax.swing.JLabel itSysToolsUAccDetailsLbl;
    private javax.swing.JPanel itSysToolsUAccDetailsPnl;
    private javax.swing.JButton itSysToolsUManagementBtn;
    private javax.swing.JPanel itSysToolsUserEDetailsBrdrPnl;
    private javax.swing.JTextField itSysToolsUsernameFld;
    private javax.swing.JLabel itSysToolsUsernameLbl;
    private javax.swing.JTextField roleField;
    // End of variables declaration//GEN-END:variables
}
